### ISSUE TITLE
Make it easier to Find speakers in the Congregations Database.

### ISSUE THREAD

**Issue by ajtruckle** [ajtruckle/meeting-schedule-assistant-support#102]
**Is your feature request related to a problem? Please describe.**
In Public Talks it has a [Find](https://www.publictalksoftware.co.uk/help-pts/pts-find-entries.html) window:

![image](https://github.com/user-attachments/assets/cf7fb174-7c51-4925-9227-b99c0f335af6)

The Congregations database in MSA is missing this feature. So it is tricky when you want to find a speaker, and don't know which congregation he  is in.

**Describe the solution you'd like**
I suggest that we add a Find menu item here:

![image](https://github.com/user-attachments/assets/64da5c8e-bccd-491f-85ba-a82e973e9b69)

This way we should be able to allow the user to cycle through all possible matches (in theory) and would behave in a similar way to PTS.

**Comment by cengizu** [comment]
Yes, that would be a very good feature! 

Ideally a global search feature:
![MSA-Search](https://github.com/user-attachments/assets/5dd27dba-8ce3-415e-a7fc-c673d43caffe)

**Comment by ajtruckle** [comment]
@cengizu  that is a nice idea. Although I have never used other controls in a toolbar. I am using the `CMFCToolBar` control and it seems that this kind of thing is possible:

https://learn.microsoft.com/en-us/cpp/mfc/walkthrough-putting-controls-on-toolbars?view=msvc-170

I am not sure if it is compatible with `CDialog` derived applications. We will have to investigate! 🥽

**Comment by ajtruckle** [comment]
@cengizu 
I am not sure how the mechanics of this approach would work. In Public Talks we had:

* Find (displayed the dialog)
* Find Next

And, the scope was specific to the database in question and the type of fields in question:

* Congregation
    * Text: Name
    * Text: Coordinator
    * Text: Notes
    * Text: Coordinator Notes
    * Text: Memos
    * Text: Coordinator Memos
    * Text: Speaker Name
    * Text: Speaker Notes
    * Text: Speaker Memos
    * Number: Speaker Talk Number
* Talks
    * Date: Last Heard
    * Date: Outline Date
    * Text: Theme
    * Text: Notes

I appreciate that MSA which a different set of databases to search, but we have to flesh out the logic for doing a search from a single edit box. This is why I would prefer a Find dialog where we have control over the data the user inputs and therefore know which fields to examine etc. I am open to suggestions.

**Comment by ajtruckle** [comment]
@cengizu 
Hi, have you given thought to how the GUI would be implemented for this feature? I know you mentioned a text box on the toolbar, but we do have several types of data to search:

- Date
- Number
- Text

**Comment by cengizu** [comment]
@ajtruckle 
I can only advise on the GUI, but the most important part is what will happen in the background: which databases the search function will search in and writing the appropriate algorithm for it. Determining what kind of data files to include in the search : xml, binary files etc. The last thing is to decide on the GUI implentetion. But the fact is, if you can achieve it, it will be a huge plus to MSA. 

Here is how AI lays it out:

**Recommended Approach**
If the search results are relatively simple and short (e.g., file names, IDs), use a `CComboBox` in the main dialog or a toolbar.
If the results are more complex or require showing more details (e.g., metadata from XML or binary files), use a separate modeless dialog with a `CListCtrl`.

**Backend Implementation for Searching Files**
Here’s how you can implement the backend logic:

**a. Search Functionality:**

1. Reading XML Databases:
- Use MFC's built-in XML handling classes (e.g., `CMarkup `or MSXML) to parse XML files.
- When the user inputs a query, parse the XML files, and search for matches.

2. Searching Binary Files:
- Use standard file I/O (`ifstream`, `CFile`) to read binary files.
- Implement a suitable search algorithm depending on the structure of your binary files.

3. Storing and Filtering Results:
- Store results in an array or a list (e.g., `std::vector<CString>`).
- Filter results based on the input query before displaying them.

4. Populating the UI with Results:
- If using a `CComboBox`, use `AddString `to populate results.
- If using a `CListCtrl`, use `InsertItem `and `SetItemText `to display details.

**b. Event Handling:**
- Implement event handlers for the search bar (EN_CHANGE event for an edit control or CBN_SELCHANGE for a combo box) to trigger the search.
- Use a button or handle the "Enter" key press for initiating the search.

**Conclusion:**
**For simpler searches:** A `CComboBox `drop-down list within the main dialog works well.
**For complex results:** A modeless dialog with a `CListCtrl `provides more flexibility and a better user experience.

**Comment by ajtruckle** [comment]
@cengizu 
Thanks. I think that we should add a **Search** toolbar icon. This will show a **Find** window similar to the PTS one. But, it will have a **Search Scope** radio option:

- Congregation
- Public Talk

We could possibly add other scopes. The window will be modeless. When it finds a match it displays the window with that entry selected. 

The window becomes the parent of the Find window. So finding next entry just shows it in this window.

Closing the window will cause Find window to have main window as parent again.

We could add Search toolbar icon menu on the respective windows. This will show the Find window (if not visible) and set the scope automatically. 

Hitting Find will always show first match.
Hitting Find Next will iterate through the matches. 

This is how I think we should do it. And the data it searches matches the fields that PTS searched. But, we would factor for new info that only MSA has that PTS didn't.

Oh, I need to decide if Congregation includes Speaker, or if it should be separate radio choice.

**Comment by ajtruckle** [comment]
@cengizu 
I am sending you a beta which has a partial implementation:

- Added **Search** menu with Find / Find Next to the Congregation Manager.
- Displays the same Find window as used in PTS.
- Find String (or Text) is operational and it should locate:
    - Congregation
    - Coordinator
    - Congregation Note / Memo info
    - Coordinator Note / Meno info
    - Speaker

In PTS we also examined the speaker note / memo info. But this information was visible in PTS.

![image](https://github.com/user-attachments/assets/70cf814d-44d7-4009-9ad3-f26d3709706b)

In MSA we use a popup Speaker window. So, whilst I can examine the speakers for the congregation, and can trigger the relevant speaker to be displayed in the popup, at this point our searching functionality is going to be on hold. Since you can't click Find Next (or F3) until you close this speaker window. At least, not without further coding changes.

I'd like you to try the finding feature as implemented to see if it works OK and / or if there are any needed GUI enhancements. 🙏

**Comment by ajtruckle** [comment]
@cengizu @stecchio66
I am sending you new betas on Google Drive with the following enhancements:

1. **Introduction of Speaker Notes/Memo Tab**: A new tab has been added to the congregation manager for speaker notes and memos. The fields are read-only.

![image](https://github.com/user-attachments/assets/225e203c-5c87-4d7a-81dd-63e18aed8cc5)


2. **Enhanced Text Search**: Searching for a text string now includes the speaker notes and memo fields.
3. **Rewritten Search Engine**: The search engine has been completely rewritten from the ground up. It became apparent that the previous PTS search engine was lacking.
4. **Improved Field Detection**: The method for detecting when fields have been modified has been rewritten to make it flicker-free.

> [!NOTE]
> Searching for _numbers_ is not supported at this time because the speaker talk numbers are not yet displayed in the congregation manager window.

**Comment by ajtruckle** [comment]
@cengizu @stecchio66
I have taken the existing help topic from PTS and updated it for MSA:

https://github.com/ajtruckle/meeting-schedule-assistant-support/wiki/msa-database-find

Not sure if **Finding Information**  might be a better title for the help topic? 🤔

### Search for Dates ###
I’ve come up with an idea to enhance date searching, building on the features available in PTS. The enhancement involves introducing _Match Options_:

- Exact Date
- Before Date
- After Date

This feature searches the **Last Invited** field in the congregation manager, allowing you to easily identify congregations that have not been invited since a specified date. Thoughts? 🤔

**Comment by ajtruckle** [comment]
@cengizu @stecchio66
> I’ve come up with an idea to enhance date searching, building on the features available in PTS. The enhancement involves introducing Match Options.

This has been implemented:

![image](https://github.com/user-attachments/assets/d8a8fecb-6a6f-4f73-908e-d5c44557e43e)

### Updated Help Topics ###
* https://github.com/ajtruckle/meeting-schedule-assistant-support/wiki/msa-congdb-manage-congregations#search--find
* https://github.com/ajtruckle/meeting-schedule-assistant-support/wiki/msa-congdb-manage-congregations#search--find-next
* https://github.com/ajtruckle/meeting-schedule-assistant-support/wiki/msa-database-find
* https://github.com/ajtruckle/meeting-schedule-assistant-support/wiki/msa-revision-history

**Comment by Fahdeya** [comment]
It works well for Arabic. I can find any speaker in the Database

Question:
When loading the Search box and choosing Find this date\Exact Date it finds the Congregation but the speaker isn't highlighted, should it find both and highlight them, the cong and the speaker?

**Comment by ajtruckle** [comment]
@Fahdeya 
> When loading the Search box and choosing Find this date\Exact Date it finds the Congregation but the speaker isn't highlighted, should it find both and highlight them, the cong and the speaker?

It is a good question. _Find this date \Extact Date_ is specifically looking for a **Congregation** which has that date for the **Last Invited** field. This information is displayed like this in the database:

```xml
<LastInvited>2024-10-13</LastInvited>
```

This functionality is specific to the congregation rather than the speakers. I understand your perspective—you’re suggesting it could display the last speaker who gave the talk on that date. However, this isn't feasible, as it's not possible to focus on more than one control at the same time. The software is functioning as intended.

**Comment by Fahdeya** [comment]
Dear Andrew

I have downloaded the Improved version of 25.3.0 that you sent me via Telegram. Bust I cannot find anymore the data from Congregation Manager. An error is generated as shown in the enclosed screenshot
![image](https://github.com/user-attachments/assets/9b372c2b-7071-444d-a1fc-6c1a6a239a47)

Also, I can search for the Public talks in the Public Talks manager and successfully find any phrase in the talks titles

**Comment by ajtruckle** [comment]
@Fahdeya 
Please back up your settings and send to me _privately_, with the phrase you are attempting to search for.

**Comment by ajtruckle** [comment]
@Fahdeya 
Thank you for bringing this issue to my attention. The error occurs because no congregation has been selected from the list. I’ve updated the code to handle this scenario and will provide you with a new beta version shortly.

In the meantime, you can avoid the popup message by selecting an existing congregation from the list.

**Comment by Fahdeya** [comment]
It worked. Thank you for correcting it
