### ISSUE TITLE
View HTML sources in the Script Editor

### ISSUE THREAD

**Issue by cengizu** [ajtruckle/meeting-schedule-assistant-support#103]
**Is your feature request related to a problem? Please describe.**
In the current operation, WebView2 GUI is used when you want to view the HTML source of a report.  CSS, XML and XSL are displayed with the Script Editor.

**Describe the solution you'd like**
It would be efficient to use the existing Script Editor to display the HTML source.. In this way, users are provided with more usage opportunities.

**Comment by ajtruckle** [comment]
@cengizu 
I have implemented this improvement! But there are some things to be aware of:

* CTRL + U will use the default WebView2 editor if it has focus. I would have to add more coding to re-route the hotkey.
* Right-click > View > View page source will now display in our Script Editor.

> [!NOTE]
> The Assignment Editor needs some attention. It displays the XML transformation and not the HTML itself. So it can't display it in the Script Editor yet.

New beta on it's way to you.

**Comment by ajtruckle** [comment]
@cengizu 
I have made additional improvements to the Assignments Editor:

* It now transforms to HTML (making it consistent with the other editors).
* You can now right-click and view the source in the Script Editor.

>[!Note]
>I have made some tweaks to the way the Menu behaves. It is only possible to perform certain actions with the Preview tab is active.

New beta on it's way to you!

**Comment by cengizu** [comment]
works nice 👍

![image](https://github.com/user-attachments/assets/798885d9-26c2-4b93-a27d-aed997d29d39)
