### ISSUE TITLE
Importing Duties from CSV

### ISSUE THREAD

**Issue by ajtruckle** [ajtruckle/meeting-schedule-assistant-support#105]
**Is your feature request related to a problem? Please describe.**
Support import / export of Duty assignments. We can import the meeting information into MSA but not the duties.

**Describe the solution you'd like**
Two related improvements:

1. Improve the existing Meeting Editor importer to support this CSV file format (eg. Audio / Visual Team).
2. Add a similar feature to the Assignment Editor (all Duties).

**Additional context**
Here is an example CSV file:

```
Date,Person,Type,TypeName
2024/05/26,Brother 1,Duty1P1,Car Park Attendant
2024/05/26,Brother 2,Duty2P1,Entrance Attendant
2024/05/26,Brother 3,Duty3P1,Auditorium Attendant
2024/05/26,Brother 4,Duty4P1,Microphones
2024/05/26,Brother 5,Duty4P2,Microphones
2024/05/26,Brother 6,Duty5P1,Audio Operator
2024/05/26,Brother 7,Duty6P1,Video Operator
2024/05/26,Brother 8,Duty7P1,Platform
2024/05/26,Brother 9,Duty8P1,Zoom Attendant
```

I also also examined a Dutch export of the duties database and can confirm the following:

* The **Type** values are the same (`Duty1P1` etc.)
* The meaning of **Type** is down to the user.
* The **TypeName** value is localized (as input by the user).

**Comment by ajtruckle** [comment]
Proposal:

- Add a **CSV - Duties** radio option
- Display a panel on the right similar to:

![image](https://github.com/user-attachments/assets/e4708196-9040-487a-9725-e8a345c2ee46)

    - Assignment column: **Host**, **Cohost** and **Zoom Operator**
    - Links To column: **TypeName** field

**Comment by ajtruckle** [comment]
@cengizu
I realize that I have to go about this slightly differently now!

* Parsing the CSV
![image](https://github.com/user-attachments/assets/cd1240d5-b1a7-4c9a-916e-c329c602267f)
When we are in the **CSV — Duties** mode we will need to let the user press the **Detect** button.

    * We will need to parse the file to extract a unique list of `TypeName` field values.
    * This unique list will be used to populate the **Links to** drop-list.
    
* Serialize mapping to JSON
We will need to support load / save mapping to JSON file. It will be similar to the existing  one for generic CSV import.

**Comment by ajtruckle** [comment]
@cengizu
Progress:

https://github.com/user-attachments/assets/972cebc8-7def-48d6-a0c2-fa871e4e8302

**Comment by cengizu** [comment]
@ajtruckle 

Looks to be working well👍

**Comment by ajtruckle** [comment]
@cengizu 
We can now save the field mapping to JSON:

```json
{
  "VideoInclude": true,
  "Video": "Video Operator",
  "AudioInclude": true,
  "Audio": "Audio Operator",
  "ZoomInclude": true,
  "Zoom": "Zoom Attendant"
}
```
The left values are hardcoded (think of them as ID's) and the right values are the `TypeName` descriptions that the user selected.
