### ISSUE TITLE
MidWeek Meeting Date

### ISSUE THREAD

**Issue by MarceloJrdaLuz** [ajtruckle/meeting-schedule-assistant-support#108]
"Hello, brothers. Initially, the app allowed us to choose the day of the midweek meeting. Now I can’t find it anymore. It defaults to the meeting being on Thursdays. However, the date for the assignment that goes on the S-89 form shows the Thursday date. Is there still a place where we can change this?"

**Comment by ajtruckle** [comment]
Hi @MarceloJrdaLuz 
Sorry for any confusion. Have you setup your local congregation yet? See the hyperlink (lower right of statusbar):

![image](https://github.com/user-attachments/assets/250207df-edea-46c9-a121-b0bda076f6f1)

Click on the link to add / edit your local congregation. Then, you will be able to configure your meeting days and times:

![image](https://github.com/user-attachments/assets/6d7d3a61-04d1-4585-b324-8dac73fc5c37)

>[!Note]
> Just make sure that you have set the [Local](https://www.publictalksoftware.co.uk/help-msa/msa-congdb-manage-congregations.html#LOCAL) checkbox for your congregation.

**Comment by MarceloJrdaLuz** [comment]
Thank you, brother. I searched so much for that part and couldn't find it.
Now it worked. Thank you very much for the help. And sorry for not finding
it earlier.

Em sex., 6 de set. de 2024, 12:28, ajtruckle ***@***.***>
escreveu:
