### ISSUE TITLE
Layout Meeting Schedule

### ISSUE THREAD

**Issue by ajtruckle** [ajtruckle/meeting-schedule-assistant-support#111]
**Is your feature request related to a problem? Please describe.**
Is it possible to make a layout that looks like it from CLM Explorer?

**Additional context**
Here is a sample template:

[Template.docx](https://github.com/user-attachments/files/17609867/Template.docx)

**Comment by ajtruckle** [comment]
Additional sample templates:

* [Template_Discussion.docx](https://github.com/user-attachments/files/17636467/Template_Discussion.docx)
* [Template_CO.docx](https://github.com/user-attachments/files/17636472/Template_CO.docx)
* [Template_2.docx](https://github.com/user-attachments/files/17636474/Template_2.docx)

**Comment by ajtruckle** [comment]
We have made good progress with the development of a new XSL script. Minor changes had to be made the Meeting Editor, so anyone who wants to test will need a **beta installer**.

Here are the current XSL / CSS files:

[Workbook-S-140-CLM Explorer.zip](https://github.com/user-attachments/files/17636507/Workbook-S-140-CLM.Explorer.zip)

>[!Note]
>This version of the template does not currently support _additional classrooms_ or _special events_.

**Comment by ajtruckle** [comment]
Updated template:

[Workbook-S-140-CLM Explorer.zip](https://github.com/user-attachments/files/17650114/Workbook-S-140-CLM.Explorer.zip)

Corrected code snippet:

```xsl
<!-- Student Item -->
<xsl:template match="StudentItem">
	<tr style="background-color: var(--bg-field)">
		<td> </td>
		<td>
			<span class="box" style="color: var(--color-field)">
				<xsl:value-of select="Time/@Duration"/>
			</span>
		</td>
		<td colspan="2">
			<xsl:value-of select="Type"/>
		</td>
		<td>
			<xsl:value-of select="Students[@Class='1']/Student"/>
			<xsl:if test="@IsTalk='0'">
				<xsl:text> / </xsl:text>
				<xsl:value-of select="Students[@Class='1']/Assistant"/>
			</xsl:if>
		</td>
	</tr>		
</xsl:template>
```

## Handling 1 Extra Class ##
To handle 1 additional class in the TFGW section would be easy enough:

```xsl
<!-- Bible Reading-->
<xsl:template match="BibleReadingItem">
	<tr style="background-color: var(--bg-gems)">
		<td> </td>
		<td>
			<span class="box" style="color: var(--color-gems)">
				<xsl:value-of select="Time/@Duration"/>
			</span>
		</td>
		<td>
			<xsl:value-of select="Type"/>
		</td>
		<!-- Bible Reading - Class 1 -->
		<td>
			<xsl:value-of select="Readers/Reader[@Class='2']"/>
		</td>
		<!-- Bible Reading - Main Hall -->
		<td>
			<xsl:value-of select="Readers/Reader[@Class='1']"/>
		</td>
	</tr>
</xsl:template>
```

And similar changes can be made to support 1 additional class in the AYFM section:

```xsl
<!-- Student Item -->
<xsl:template match="StudentItem">
	<tr style="background-color: var(--bg-field)">
		<td> </td>
		<td>
			<span class="box" style="color: var(--color-field)">
				<xsl:value-of select="Time/@Duration"/>
			</span>
		</td>
		<td>
			<xsl:value-of select="Type"/>
		</td>
                <!-- Student Item - Class 1 -->
		<td>
			<xsl:value-of select="Students[@Class='2']/Student"/>
			<xsl:if test="@IsTalk='0'">
				<xsl:text> / </xsl:text>
				<xsl:value-of select="Students[@Class='2']/Assistant"/>
			</xsl:if>
		</td>
                <!-- Student Item - Main Hall -->
		<td>
			<xsl:value-of select="Students[@Class='1']/Student"/>
			<xsl:if test="@IsTalk='0'">
				<xsl:text> / </xsl:text>
				<xsl:value-of select="Students[@Class='1']/Assistant"/>
			</xsl:if>
		</td>
	</tr>		
</xsl:template>
```

The template (for 1 additional class) that was sent to me looks like this:

![image](https://github.com/user-attachments/assets/96dff7c0-fca6-4a5a-9296-19f9cd7d7f17)

The differences are:

* Main hall students are in the first column and the additional class students are in the second column. 
* It has a (Main) label.
* The Bible Reading text includes the classroom counsellor.

**Comment by ajtruckle** [comment]
## Handling 1 Extra Class - Correction ##
We need to confirm if there is actually 1 extra class or not by examining the `NumberClasses` attribute. And, there are three ways to make this work.

* Method 1
Change the calling code:

```xsl
<xsl:choose>
	<xsl:when test="AYFM/@NumberClasses = '2'">
		<xsl:apply-templates select="AYFM/StudentItem" mode="OneExtraClass"/>
	</xsl:when>
	<xsl:otherwise>
		<xsl:apply-templates select="AYFM/StudentItem"/>
	</xsl:otherwise>
</xsl:choose>
```

Then, we have two versions of the `StudentItem` template (the original and the new one with the mode specified).

* Method 2
We update the `StudentItem` template itself to conditionally add the extra class.

There is no right or wrong way. 🤔

**Comment by ajtruckle** [comment]
This version of the template has the following improvements:

* Supports one extra class
* Names are shown in _italics_

[Workbook-S-140-CLM Explorer.zip](https://github.com/user-attachments/files/17663318/Workbook-S-140-CLM.Explorer.zip)

**Comment by ajtruckle** [comment]
This version of the template has better support for opening the HTML output in Microsoft Word.

This is considered as the final template for now:

[Workbook-S-140-CLM Explorer.zip](https://github.com/user-attachments/files/17679409/Workbook-S-140-CLM.Explorer.zip)

**Comment by cengizu** [comment]
![image](https://github.com/user-attachments/assets/060b42b7-7836-4f48-8f8b-03aa9602ffd4)
it looks great 👍

**Comment by ajtruckle** [comment]
Version 24.14.6 has now been released which includes this template:

https://www.publictalksoftware.co.uk/2024/11/msa-version-24-14-6-news/

**Comment by ajtruckle** [comment]
@cengizu 
I received the following clarifications concerning CLM Explorer:

### Template Settings ###
Under Preferences you can choose the report with **Square Icons**.

![image](https://github.com/user-attachments/assets/03d50a25-cc4f-41f5-b16c-4aeec1bef3a0)

### Special Events ###
Under Congregation Special Dates you can make CO Visit and Special events.

**Comment by ajtruckle** [comment]
### Special Events ###
Special Events looks like this on the Square Icons template in CLM Explorer:

![image](https://github.com/user-attachments/assets/0fe7b328-70b6-4900-ad39-b6dcc67e97b0)

**Comment by ajtruckle** [comment]
@cengizu  Minor changes have been made to MSA to add missing attributes to the Special Events database. You'll have to edit an existing special event to trigger the events database to update with the new attributes.

The templates have been updated to support midweek Memorial events.

[Workbook-S-140-CLM Explorer.zip](https://github.com/user-attachments/files/17776308/Workbook-S-140-CLM.Explorer.zip)

**Comment by cengizu** [comment]
![image](https://github.com/user-attachments/assets/aff9a275-589c-4385-a319-ac5d68866110)

it works nice for the Memorial.
