### ISSUE TITLE
Synchronize with Google Calendar

### ISSUE THREAD

**Issue by Fahdeya** [ajtruckle/meeting-schedule-assistant-support#112]
The midweek overseer reported what seems to be a problem. When we have in the schedule a note stating that it is a CO visit, the system does not synchronize the schedule along with the google calendar. Enclosed is a copy of the MWB document

[06 Nov-Dec.zip](https://github.com/user-attachments/files/17635014/06.Nov-Dec.zip)

**Comment by ajtruckle** [comment]
Hi @Fahdeya 

No one has reported any issues with Google calendar synchronization. Can you please as your brother to make sure that this highlighted option is **not ticked**:

![image](https://github.com/user-attachments/assets/519a562b-9e0b-41e0-9846-eb32264be11b)

Please let me know if his configuration is already set the same as mine.

**Comment by ajtruckle** [comment]
@Fahdeya 

I thought I would give it a go myself and created a **Circuit Visit** special event. It synchronized correctly with Google Calendar:

![image](https://github.com/user-attachments/assets/b16f9d36-1d53-444b-bdd7-452472bc2379)

**Comment by Fahdeya** [comment]
Thank you for your reply, I will send it to the friend that care for the schedule
