### ISSUE TITLE
Improvements to Congregation Management

### ISSUE THREAD

**Issue by ajtruckle** [ajtruckle/meeting-schedule-assistant-support#113]
**Is your feature request related to a problem? Please describe.**
At the moment it is necessary to use the menu system to navigation different congregations and this can be cumbersome.

**Describe the solution you'd like**
Improve the existing Congregation window by adding a list of congregations on the left. This way:

* we will only have a single window for managing all congregations
* no menu navigation required
* consistency with the Publishers / Public Talk database management windows

**Additional context**
![image](https://github.com/user-attachments/assets/7b00e1ad-5c55-4d03-a968-4149573c042d)

**Comment by ajtruckle** [comment]
This is what it looks like now:

![image](https://github.com/user-attachments/assets/8eddd13e-509f-4488-9443-35707a923548)

We need to re-work the buttons to make them work more intuitively. Eg:

* **Apply Changes** (or **Apply**): Updates the selected congregation in the database and then disables. It gets enabled whenever a change is made to the congregation entry.
* **Cancel Changes** (or **Cancel**): Resets the selected congregation back to its original state. It gets enabled whenever a change is made to the congregation entry.
* **Help**: Show help topic.
* **Manage Speakers**: Same as it is now, just relocated.
* **Options**: Display Options window.

I am not sure if we need an OK button. 🤔 Open to proposals!

**Comment by cengizu** [comment]
@ajtruckle 

Here is a suggestion for the GUI:
![image](https://github.com/user-attachments/assets/6df4bea4-9777-484c-9408-5dfb4bdbe891)

**Comment by cengizu** [comment]
@ajtruckle 

Another version with memo fields kept as they are:
![image](https://github.com/user-attachments/assets/26cf50d1-1410-4755-9b13-c3d1a7e992db)

**Comment by ajtruckle** [comment]
Hi @cengizu 

Thanks for the design concepts! 🙏 I am working on implementing.

**Comment by ajtruckle** [comment]
Hi @cengizu 

I have just sent you version 25.0.0 beta with this new **Congregation Manager** for testing.

**Comment by cengizu** [comment]
@ajtruckle 

First impressions are good:
![image](https://github.com/user-attachments/assets/f53aa1a9-d7aa-4830-83ee-959589919964)

Here are my remarks:
- "**Change Congregation**" **button** must be disabled when no speaker is selected.
- If no congregations are selected, which only happens during initial launch of this manager window, **Delete button** + all Speaker panel buttons must be disabled... or maybe right panel can be disabled completely. Normally, it is not possible to Not select a congregation, just happens during first launch of this window.
- **Talk cordinator** text box can be an editable dropdown list, filled with speakers of that congregation + can permit adding unlisted speakers if required. This would facilitate users to select an existing speaker as the coordinator for that congregation.

**Comment by ajtruckle** [comment]
@cengizu 
> Talk coordinator text box can be an editable dropdown list, filled with speakers of that congregation + can permit adding unlisted speakers if required. This would facilitate users to select an existing speaker as the coordinator for that congregation.

This is a nice idea. I'll give it some consideration. 💭

I have made the following improvements:

- The Apply / Cancel buttons are now enabled when you change either meeting time.
- The Apply / Cancel buttons are no longer enabled when all you do is select a different congregation or speaker.
- The Add / Edit / Delete / Change buttons are now only enabled when a congregation / speaker is selected. But they are only enabled if the Apply / Cancel buttons are disabled.

I also think that the Congregation Report Viewer icon on the main toolbar can now be changed to display the Congregation Manager. Since the report viewer can be displayed from within the manager.

**Comment by stecchio66** [comment]
@ajtruckle 
I like this new window.

Thanks also @cengizu for the good ideas including the one in the box for choosing the talks coordinator.

**Comment by stecchio66** [comment]
@ajtruckle 
Another idea: in Location Map field, we can add Google Maps link instead image file?

**Comment by ajtruckle** [comment]
@stecchio66 
> Another idea: in Location Map field, we can add Google Maps link instead image file?

Thanks for the suggestion.  Is it possible for you to use the **Congregation Link** feature and map it to the Google Maps URL? Or are you already using that field for something else? We can turn the location map field into a hyperlink.

**Comment by ajtruckle** [comment]
@cengizu @stecchio66 
I have made the following improvements:

- Updated the Talk Coordinator control to a combo box, allowing selection from a list of speakers while retaining the option to manually enter text.
- Enhanced the Close functionality to check for unsaved changes, prompting users to save or cancel closing if needed.

**Comment by stecchio66** [comment]
@ajtruckle 
> Thanks for the suggestion. Is it possible for you to use the **Congregation Link** feature and map it to the Google Maps URL? Or are you already using that field for something else? We can turn the location map field into a hyperlink.

I use the **Congregation Link** for the link of congregation info from JW.org.

Example: https://apps.jw.org/ui/I/meeting-search.html#/?w=2C2F8A51-05FB-44F4-B085-0840BEF075C3

**Comment by ajtruckle** [comment]
@stecchio66 
> I use the Congregation Link for the link of congregation info from JW.org.

That's an interesting idea! We could transform the Location Map control into a similar hyperlink feature. This would allow users to link to an image file on their PC or provide a suitable URL.

**Comment by ajtruckle** [comment]
@stecchio66 @cengizu 
I have made the following improvement:

* The Location Map has been turned from a browse control (for an image) into a hyperlink control. It now behaves like the Congregation Link.

**Comment by ajtruckle** [comment]
@stecchio66 @cengizu 
The **Weekend Meeting Editor** menu has been updated to include a new **Manage** menu item, which opens the **Congregation Manage**r. This addition aims to enhance the user experience and ensure consistency.

However, this feature is still a work in progress, as updates made through the Congregation Manager can impact several aspects of the Weekend Meeting Editor, including:

* The congregation drop-down list
* The speaker drop-down list
* Assigned talks for speakers

The software is designed to automatically update the congregation and speaker drop-down lists after the manager is closed. However, I anticipate encountering scenarios that may require further adjustments.

New betas are on on their way to you. 😊
