### ISSUE TITLE
Improvements to Speaker Management

### ISSUE THREAD

**Issue by ajtruckle** [ajtruckle/meeting-schedule-assistant-support#114]
**Is your feature request related to a problem? Please describe.**
Public Talks has a feature that allows you to update each [speakers](https://www.publictalksoftware.co.uk/help-pts/pts-new-modify-speaker.html) chosen talks via an edit control:

![image](https://github.com/user-attachments/assets/67bb6c79-47cf-4a97-88ee-4e9565873bdc)

**Describe the solution you'd like**
Add a similar feature be added to Meeting Schedule Assistant speaker window:

![image](https://github.com/user-attachments/assets/fa5f5c7c-742c-4cfe-84ab-2917f732e811)

The button would be renamed to Update List.

**Additional context**
 This would let the user have the option of updating the list of talks via the edit control or pasting in bulk.

**Comment by ajtruckle** [comment]
I have migrated the code from Public Talks and adapted to Meeting Schedule Assistant:

![image](https://github.com/user-attachments/assets/f6bb201a-b472-4a07-a4c0-d66426ce9141)

**Comment by cengizu** [comment]
@ajtruckle 

This looks good. 
![Recording 2024-11-27 152611](https://github.com/user-attachments/assets/629d9be7-5a2c-4bd8-86a3-1dd07110cc53)

**One click:** add talk
**Another click:** make it speaker's favorite talk
**Another click:** remove talk

**Comment by ajtruckle** [comment]
@cengizu Great! And did you try the new approach? Typing in the edit control and clicking Update List?

**Comment by cengizu** [comment]
@ajtruckle 

Yes, it works smoothly. However, an error-correcting / preventive mechanism can be put in there. It can give a small warning if the user enters a period (.) or other similar symbol (/, -, ; etc.) instead of a comma.

Something like Windows Explorer's warning could be nice:
![image](https://github.com/user-attachments/assets/589a09b0-b1b2-4e51-8a1e-eabde7274503)

**Comment by ajtruckle** [comment]
@cengizu 

How about this?

https://github.com/user-attachments/assets/ff94cdd4-02ff-4923-a2f8-4fc0a3e46326

The tooltip is visible for about 10 seconds.
