### ISSUE TITLE
Implement Field Service Manager

### ISSUE THREAD

**Issue by ajtruckle** [ajtruckle/meeting-schedule-assistant-support#116]
**Is your feature request related to a problem? Please describe.**
There is currently no dedicated support for arranging **Field Service Meetings**. Previously, a specific window was available for this purpose, but it was removed when the **Announcement Sheet Editor** was discontinued.

**Describe the solution you'd like**
Create a new window specifically designed for this purpose, allowing users to specify the day, time, and location for each arrangement. The window should also support multiple arrangements per day to accommodate varied schedules.

**Describe alternatives you've considered**
You can create your own XML data file to manage this information independently. Once created, you can integrate the XML file into your schedules by customizing the XSL template.

**Additional context**
The Field Service Meeting Manager should be accessible from:  

- **The Field Service Group Manager window**, with the underlying data saved in the `FieldServiceGroup` section of the Publishers database.  
- **Alternatively, the Congregation Manager window**, with the data stored alongside the local congregation information in the database.  

The choice should align with whichever option is most logical and integrates seamlessly with the existing workflow.

We could also explore the possibility of adding support for Field Service Meeting information to the [Script Builder](https://www.publictalksoftware.co.uk/help-msa/mwb-editor-script-builder.html). However, this would require a separate ticket for further discussion and evaluation.

**Comment by ajtruckle** [comment]
The primary GUI could designate the brother taking the lead as the default option. However, the Meeting Editor could include a feature to override these defaults for a specific week. Just brainstorming ideas!

And I came across an old version of MSA (version 3.08!) that featured the original field service window. Here's what it looked like:

![image](https://github.com/user-attachments/assets/0f4f698a-00fc-4e4f-9bac-ca2c650ad542)

**Comment by ajtruckle** [comment]
@cengizu
Here’s an improved version of your text:  

I came across an old version of MSA (version 3.08!) that featured the original field service window. Here's what it looked like:

This version is slightly more polished and conversational while retaining your intended meaning.

![image](https://github.com/user-attachments/assets/0f4f698a-00fc-4e4f-9bac-ca2c650ad542)

**Comment by cengizu** [comment]
Here is an idea for the GUI

**Weekly Field Service Meeting Manager**

![image](https://github.com/user-attachments/assets/9fce652c-541b-40ba-850d-fa6174db2515)

If there will be another meeting during the day, user can click on the **Add More** button and activate the other field.

**Comment by ajtruckle** [comment]
@cengizu 
Thanks. What is the logic behind the checkboxes against the days of the week?

**Comment by cengizu** [comment]
@ajtruckle 

The boxes can be selected to specify which day the meetings are held. No meeting on non-selected days.

**Comment by ajtruckle** [comment]
@cengizu 
I thought so. So, how do you suggest that we reflect this information, based on that concept of checkboxes in the XML database?

**Comment by cengizu** [comment]
@ajtruckle 

Here is the logic:

When the "**Apply Changes**" button is clicked:
1. Loop through the `CheckedListBox `items to identify checked days.
2. Collect the associated time, conductor and location for checked days.
3. Write this data to an XML file.


Sample XML code
```
<FSM>
  <FieldService>
    <Day>Monday</Day>
    <Time>9.15</Time>
    <Conductor>Bilbo Baggins</Conductor>
    <Location>Bagend</Location>
  </FieldService>
  <FieldService>
    <Day>Wednesday</Day>
    <Time>14.15</Time>
    <Conductor>Barliman Butterbur</Conductor>
    <Place>@The Prancing Pony, Town of Bree</Place>
  </FieldService>
</FSM>
```

**Comment by ajtruckle** [comment]
@cengizu 
I like the XML layout. 

Here are my thoughts:
- Make the list of days just a list. So the user must click each day in turn to configure that day. 
- Place a group box around the first arrangement. 
- Place a group box around the second arrangement and make the caption a check box. If enabled then activate controls. 
- Consider a third group box with similar. This way we could support morning / afternoon / evening.

**Comment by ajtruckle** [comment]
@cengizu 
Got the URL for the clock icon? Transparent PNG Maybe 24 x 24 or 32 x 32.

**Comment by ajtruckle** [comment]
@cengizu 
![image](https://github.com/user-attachments/assets/01b2ce10-42cc-47a9-843e-97a44f524fef)
I made slight layout change to cater for up to 5 meeting arrangements. We have more space for the location but I have lost space for the clock icon.

**Comment by ajtruckle** [comment]
ChatGPT proposes an updated XML format, like this (which can cater for multiple meetings per day):

```xml
<FieldMinistryMeetings>
    <Day name="Sunday">
        <Meeting arrangement="1">
            <Time>9:45</Time>
            <Conductor>Happy Face</Conductor>
            <Location>Kingdom Hall</Location>
        </Meeting>
        <Meeting arrangement="2">
            <Time>11:00</Time>
            <Conductor>Jane Doe</Conductor>
            <Location>Park</Location>
        </Meeting>
    </Day>
    <Day name="Monday">
        <Meeting arrangement="1">
            <Time>10:00</Time>
            <Conductor>John Smith</Conductor>
            <Location>Café</Location>
        </Meeting>
    </Day>
    <Day name="Tuesday">
        <Meeting arrangement="1">
            <Time>8:00</Time>
            <Conductor>Patience Best</Conductor>
            <Location>Library</Location>
        </Meeting>
    </Day>
    <!-- Add more days and meetings as needed -->
</FieldMinistryMeetings>
```

**Comment by cengizu** [comment]
@ajtruckle 
 
Tab control seems the only way to handle multiple meetings per day 👍

Of course, it would be ideal if we could use a tab control like below, so we don't need a tab count list (No. of Meetings):
![image](https://github.com/user-attachments/assets/82e77e7b-c9b9-4269-88ee-ae5baf0194cc)

**Comment by ajtruckle** [comment]
@cengizu 
> It would be ideal if we could use a tab control like below, so we don't need a tab count list (No. of Meetings):

I don't know how to implement that approach where all tabs have a **Close** icon. I could refactor the code to use `CMFCTabCtrl` which allows you to enable a Close button for the active tab, but that's all. There is no way that I know of to include a **Add** button on the tab bar (not without custom rendering).

**Comment by ajtruckle** [comment]
@cengizu 
This is what the new window looks like now:
![image](https://github.com/user-attachments/assets/f260ffa3-2955-42a0-b0a2-d0090346f383)
It is now functional and  you can maintain the list of ministry meetings.

> [!Note]
> I have not done any coding with the MWB file yet or displaying data in the editor.

I have another idea 💡 coming to me:

- We could include a suitable control on the window to let the user specify a hyperlink for the location (eg. Google Maps URL).

**Comment by cengizu** [comment]
@ajtruckle 

Dialog layout is good. Compact and practical.
![image](https://github.com/user-attachments/assets/c59bee5a-1710-4264-9585-44e45bd6a454)
![image](https://github.com/user-attachments/assets/b119d454-9048-4830-b60a-658b5c6dad16)

**Comment by ajtruckle** [comment]
@cengizu 
Thanks for the feedback! 😊 Here are some thoughts:

1. Should we ask the user for confirmation when updating the default arrangements? Since the operation can't be reversed.
2. I think we should update the GUI to allow the user to reset the selected day to the defaults (if any are available).

**Comment by ajtruckle** [comment]
@cengizu 
> Should we ask the user for confirmation when updating the default arrangements? Since the operation can't be reversed.
This have been implemented:

![image](https://github.com/user-attachments/assets/82255a44-e417-4aa4-8549-932185ca4ffa)

**Comment by cengizu** [comment]
**a mini suggestion** 💡 When closing a tab, it would be nice if a simple check like this is possible >> 
If the user did not enter anything or has not changed any of the default values, the warning popup message should not appear.

**Comment by ajtruckle** [comment]
@cengizu 
> a mini suggestion 💡 When closing a tab, it would be nice if a simple check like this is possible >>
> If the user did not enter anything or has not changed any of the default values, the warning popup message should not appear.

This is a great idea! I’ll implement it soon. In the meantime, I’m sending you a new beta version to test. Here are some updates to check out:

- Moved the **Field Ministry Manager** to the **Database** menu.
- Added an **Include Field Ministry information** option to the **Set Defaults** menu.

![image](https://github.com/user-attachments/assets/f36b0b1a-746b-4998-803a-5b5a7de8231a)

**Comment by ajtruckle** [comment]
@cengizu 
> When closing a tab, it would be nice if a simple check like this is possible >>
> If the user did not enter anything or has not changed any of the default values, the warning popup message should not appear.

This improvement has now been implemented and a new beta is on its way to you for testing. 👍

**Comment by ajtruckle** [comment]
@cengizu 
Thanks for sending me the toolbar icon! 🙏 The toolbar has been updated:

![image](https://github.com/user-attachments/assets/823c201e-f9ff-45e9-a3a6-46ce36e96dd5)

A beta is on it's way to you for testing.

## Displaying Field Ministry Arrangements of the Schedule
I know that you wanted to display the information like this:

![image](https://github.com/user-attachments/assets/d9e90539-631e-4eae-b5b9-1af844f579d6)

Here is a modified template that displays the content. But:

- We need to implement styles etc. to make it consistent with the S-140 look n' feel.
- We need to support localization (some labels are hardcoded in English.
- I only modified the code for a normal week. The changes would need to be propagated for relevant special event weeks.

[Workbook-S-140-Ministry.zip](https://github.com/user-attachments/files/18066009/Workbook-S-140-Ministry.zip)

I use the following to display the information:

```xsl
<xsl:apply-templates select="MinistryMeetings" mode="Horizontal"/>
```

And, here are the supporting functions:

```xsl
<xsl:template match="MinistryMeetings" mode="Horizontal">
	<h2>Field Ministry Meetings</h2>
	<table width="100%">
		<tr>
			<td></td>
			<td>MON</td>
			<td>TUE</td>
			<td>WED</td>
			<td>THR</td>
			<td>FRI</td>
			<td>SAT</td>
			<td>SUN</td>
		</tr>
		<!-- Loop through meetings dynamically using recursion -->
		<xsl:call-template name="generate-rows">
			<xsl:with-param name="currentMeeting" select="1"/>
		</xsl:call-template>
	</table>
</xsl:template>

<xsl:template name="generate-rows">
	<xsl:param name="currentMeeting"/>

	<!-- Stop recursion when currentMeeting exceeds MaxMeetingsPerDay -->
	<xsl:if test="$currentMeeting &lt;= @MaxMeetingsPerDay">
		<!-- Time -->
		<tr>
			<td>Time</td>
			<xsl:for-each select="Day">
				<xsl:sort order="ascending" data-type="number" select="MeetingDate/@Day"/>
				<td>
					<xsl:value-of select="Meetings/Meeting[$currentMeeting]/StartTime24"/>
				</td>
			</xsl:for-each>
		</tr>
		<!-- Conductor -->
		<tr>
			<td>Conductor</td>
			<xsl:for-each select="Day">
				<xsl:sort order="ascending" data-type="number" select="MeetingDate/@Day"/>
				<td>
					<xsl:value-of select="Meetings/Meeting[$currentMeeting]/Conductor"/>
				</td>
			</xsl:for-each>
		</tr>
		<!-- Location -->
		<tr>
			<td>Location</td>
			<xsl:for-each select="Day">
				<xsl:sort order="ascending" data-type="number" select="MeetingDate/@Day"/>
				<td>
					<xsl:value-of select="Meetings/Meeting[$currentMeeting]/Location"/>
				</td>
			</xsl:for-each>
		</tr>

		<!-- Recursive call for the next meeting -->
		<xsl:call-template name="generate-rows">
			<xsl:with-param name="currentMeeting" select="$currentMeeting + 1"/>
		</xsl:call-template>
	</xsl:if>
</xsl:template>
```

**Comment by ajtruckle** [comment]
@cengizu 
I am sending you a new beta with the following improvements:

- Menu item icon
- Translation for **Meetings for Field Service**
- Template updated to use localization for:
    - Main heading
    - Day of week column headings
    - Conductor label

Updated script:

```xsl
<xsl:template match="MinistryMeetings" mode="Horizontal">
	<h2>
		<xsl:value-of select="//Labels/MeetingsForFieldService"/>
	</h2>
	<table width="100%">
		<tr>
			<td></td>
			<td>
				<xsl:value-of select="Day[@Name='Monday']/MeetingDate/@DayShort"/>
			</td>
			<td>
				<xsl:value-of select="Day[@Name='Tuesday']/MeetingDate/@DayShort"/>
			</td>
			<td>
				<xsl:value-of select="Day[@Name='Wednesday']/MeetingDate/@DayShort"/>
			</td>
			<td>
				<xsl:value-of select="Day[@Name='Thursday']/MeetingDate/@DayShort"/>
			</td>
			<td>
				<xsl:value-of select="Day[@Name='Friday']/MeetingDate/@DayShort"/>
			</td>
			<td>
				<xsl:value-of select="Day[@Name='Saturday']/MeetingDate/@DayShort"/>
			</td>
			<td>
				<xsl:value-of select="Day[@Name='Sunday']/MeetingDate/@DayShort"/>
			</td>
		</tr>
		<!-- Loop through meetings dynamically using recursion -->
		<xsl:call-template name="generate-rows">
			<xsl:with-param name="currentMeeting" select="1"/>
		</xsl:call-template>
	</table>
</xsl:template>

<xsl:template name="generate-rows">
	<xsl:param name="currentMeeting"/>

	<!-- Stop recursion when currentMeeting exceeds MaxMeetingsPerDay -->
	<xsl:if test="$currentMeeting &lt;= @MaxMeetingsPerDay">
		<!-- Time -->
		<tr>
			<td>Time</td>
			<xsl:for-each select="Day">
				<xsl:sort order="ascending" data-type="number" select="MeetingDate/@Day"/>
				<td>
					<xsl:value-of select="Meetings/Meeting[$currentMeeting]/StartTime24"/>
				</td>
			</xsl:for-each>
		</tr>
		<!-- Conductor -->
		<tr>
			<td>
				<xsl:value-of select="//Labels/PTS_WTConductor"/>
			</td>
			<xsl:for-each select="Day">
				<xsl:sort order="ascending" data-type="number" select="MeetingDate/@Day"/>
				<td>
					<xsl:value-of select="Meetings/Meeting[$currentMeeting]/Conductor"/>
				</td>
			</xsl:for-each>
		</tr>
		<!-- Location -->
		<tr>
			<td>Location</td>
			<xsl:for-each select="Day">
				<xsl:sort order="ascending" data-type="number" select="MeetingDate/@Day"/>
				<td>
					<xsl:value-of select="Meetings/Meeting[$currentMeeting]/Location"/>
				</td>
			</xsl:for-each>
		</tr>

		<!-- Recursive call for the next meeting -->
		<xsl:call-template name="generate-rows">
			<xsl:with-param name="currentMeeting" select="$currentMeeting + 1"/>
		</xsl:call-template>
	</xsl:if>
</xsl:template>
```

Two labels still remain in English:

1. Location
2. Time
I have contacted the partial translation volunteers regarding these phrases. However, for the languages without a translator, we will need to use English. They are:

- Afrikaans
- Armenian
- Aukan
- Bulgarian
- Estonian
- Hindi
- Malagasy
- Maltese
- Saramaccan
- Sranantongo
- Vietnamese

[Workbook-S-140-Ministry.zip](https://github.com/user-attachments/files/18083466/Workbook-S-140-Ministry.zip)

**Comment by ajtruckle** [comment]
@cengizu
I am sending you a new beta with the following improvements:

- Translation for **Location** and **Time**
- Template updated to use localization for:
    - **Location** label
    - **Time** label

Updated script:

```xsl
<xsl:template match="MinistryMeetings" mode="Horizontal">
	<h2>
		<xsl:value-of select="//Labels/MeetingsForFieldService"/>
	</h2>
	<table width="100%">
		<tr>
			<td></td>
			<td>
				<xsl:value-of select="Day[@Name='Monday']/MeetingDate/@DayShort"/>
			</td>
			<td>
				<xsl:value-of select="Day[@Name='Tuesday']/MeetingDate/@DayShort"/>
			</td>
			<td>
				<xsl:value-of select="Day[@Name='Wednesday']/MeetingDate/@DayShort"/>
			</td>
			<td>
				<xsl:value-of select="Day[@Name='Thursday']/MeetingDate/@DayShort"/>
			</td>
			<td>
				<xsl:value-of select="Day[@Name='Friday']/MeetingDate/@DayShort"/>
			</td>
			<td>
				<xsl:value-of select="Day[@Name='Saturday']/MeetingDate/@DayShort"/>
			</td>
			<td>
				<xsl:value-of select="Day[@Name='Sunday']/MeetingDate/@DayShort"/>
			</td>
		</tr>
		<!-- Loop through meetings dynamically using recursion -->
		<xsl:call-template name="generate-rows">
			<xsl:with-param name="currentMeeting" select="1"/>
		</xsl:call-template>
	</table>
</xsl:template>

<xsl:template name="generate-rows">
	<xsl:param name="currentMeeting"/>

	<!-- Stop recursion when currentMeeting exceeds MaxMeetingsPerDay -->
	<xsl:if test="$currentMeeting &lt;= @MaxMeetingsPerDay">
		<!-- Time -->
		<tr>
			<td>
				<xsl:value-of select="//Labels/Time"/>
			</td>
			<xsl:for-each select="Day">
				<xsl:sort order="ascending" data-type="number" select="MeetingDate/@Day"/>
				<td>
					<xsl:value-of select="Meetings/Meeting[$currentMeeting]/StartTime24"/>
				</td>
			</xsl:for-each>
		</tr>
		<!-- Conductor -->
		<tr>
			<td>
				<xsl:value-of select="//Labels/PTS_WTConductor"/>
			</td>
			<xsl:for-each select="Day">
				<xsl:sort order="ascending" data-type="number" select="MeetingDate/@Day"/>
				<td>
					<xsl:value-of select="Meetings/Meeting[$currentMeeting]/Conductor"/>
				</td>
			</xsl:for-each>
		</tr>
		<!-- Location -->
		<tr>
			<td>
				<xsl:value-of select="//Labels/Location"/>
			</td>
			<xsl:for-each select="Day">
				<xsl:sort order="ascending" data-type="number" select="MeetingDate/@Day"/>
				<td>
					<xsl:value-of select="Meetings/Meeting[$currentMeeting]/Location"/>
				</td>
			</xsl:for-each>
		</tr>

		<!-- Recursive call for the next meeting -->
		<xsl:call-template name="generate-rows">
			<xsl:with-param name="currentMeeting" select="$currentMeeting + 1"/>
		</xsl:call-template>
	</xsl:if>
</xsl:template>
```

[Workbook-S-140-Ministry.zip](https://github.com/user-attachments/files/18093135/Workbook-S-140-Ministry.zip)

**Comment by ajtruckle** [comment]
@cengizu 
I made some improvements in the latest beta, including:

* Updated these built-in templates to include support for ministry information:
    * Workbook-S-140
    * Workbook-S-140-Full
    * Workbook-S-140-Legacy
    * Workbook-S-140-Weekend Meeting
* The 12 / 24 hour Meeting Editor setting is now respected.

The following built-in templates have not been updated yet:
* Workbook-S-140-CLM Explorer
* Workbook-S-140-Personal
I think the information could be added to the **Personal** template but the **CLM Explorer** template might need some styling changes. 🤔

## CSS Styling ##
I settled on the following CSS styling:
```css
h2.ministry {
    font-family: Calibri;
    font-size: 10pt;
    background-color: lightgray;
    text-align: center;
    text-transform: uppercase;
    padding: 2mm;
}

table.ministry {
    width: 100%;
    border-collapse: collapse;
    font-family: Calibri;
}

table.ministry th {
    padding: 1mm;
    text-align: left;
    text-transform: uppercase;
    font-size: 10pt;
}

table.ministry td {
    padding: 1mm;
    font-size: 10pt;
}

table.ministry td:first-child {
    text-align: right;
    font-weight: bold;
}

table.ministry tr:nth-child(4) td {
    border-top: solid 2px black;
}

table.ministry tr:nth-child(3n + 4) td {
    border-top: solid 2px black;
}

[dir=rtl] table.ministry th {
    text-align: right;
}

[dir=rtl] table.ministry td:first-child {
    text-align: left;
}

@media screen {
    .ministry td:hover, th:hover {
        box-shadow: inset 0 0 2mm rgba(0, 0, 0, 0.5); /* Inner shadow 2mm thick */
        cursor: pointer; /* Optional: Adds a pointer cursor for better UX */
    }
}
```
