### ISSUE TITLE
Add Jump To Talk control to the Manage Speaker window

### ISSUE THREAD

**Issue by ajtruckle** [ajtruckle/meeting-schedule-assistant-support#117]
**Is your feature request related to a problem? Please describe.**
Sometimes I need to add a talk outline to a speaker when all I have is the theme. This requires me to manually locate the talk in the list, which is time-consuming.

**Describe the solution you'd like**
There is a [Jump To](https://www.publictalksoftware.co.uk/help-pts/pts-public-talks-tab.html#JUMP_TO) feature on the Public Talks maintenance page in PTS (refer to the screenshot provided in the **Additional Context** section below). It would be beneficial to add a similar _Jump To_ edit control just above the list of talk numbers on the **Manage Speaker** window:

![image](https://github.com/user-attachments/assets/13a3572f-0d0d-4538-a0b6-e22d1ef6d51e)

Functionality:

* Entering a number would navigate to that specific number in the list.
* Entering a phrase would navigate to the first occurrence of that phrase in the list.

**Additional context**
Here is where the _Jump To_ control is located in PTS:
![image](https://github.com/user-attachments/assets/53e838aa-d73e-4d04-95ed-c7f83057e287)

**Comment by ajtruckle** [comment]
@cengizu
The feature has been implemented. Please observe its functionality in action:

![399256310-5cc590a5-ba13-432c-ad30-9b7bc06eccd1](https://github.com/user-attachments/assets/81e658c5-f480-4025-b8dc-91e1e790ed59)

I believe it would be beneficial to add a suitable 16 x 16 icon to the left to indicate the purpose of these edit/spinner controls.

**Comment by ajtruckle** [comment]
@cengizu
Updated help documentation:

* https://github.com/ajtruckle/meeting-schedule-assistant-support/wiki/msa-congdb-manage-speakers#jump-to
* https://github.com/ajtruckle/meeting-schedule-assistant-support/wiki/msa-revision-history

**Comment by ajtruckle** [comment]
@cengizu
> I believe it would be beneficial to add a suitable 16 x 16 icon to the left to indicate the purpose of these edit/spinner controls.

I have added the same icon that is used in the **Select Student** window:

![image](https://github.com/user-attachments/assets/fa4f0826-95ac-4ef5-aad7-62aaf63472c9)

**Comment by Fahdeya** [comment]
https://github.com/ajtruckle/meeting-schedule-assistant-support/issues/117#issuecomment-2565200626
I was not able to play this video

**Comment by Fahdeya** [comment]
It seems when I close Chrome and reopen it, the video played successfully

**Comment by ajtruckle** [comment]
@Fahdeya 
> It seems when I close Chrome and reopen it, the video played successfully

Excellent! I have converted it into an animated GIF, which might be more effective.
