### ISSUE TITLE
GUI enhancement suggestion: Main Window

### ISSUE THREAD

**Issue by ajtruckle** [ajtruckle/meeting-schedule-assistant-support#13]
**Is your feature request related to a problem? Please describe.**
I tested the current main window GUI on a novice user and he wasn’t able to figure out what to do after selecting the date range. [^1]

**Describe the solution you'd like**
Help beginners to figure out where to start at first usage. With this revised GUI, when the date range is selected, the user will logically know to click one of the report buttons.

**Additional context**
![Revised Main Window](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/8431d223-2db8-4f06-8fae-0bf577eede73)

Optionally a status bar can contain tooltips etc..

[^1]: Idea proposed by @cengizu.

**Comment by ajtruckle** [comment]
Thanks for the suggestion @cengizu.

> Help beginners to figure out where to start at first usage. With this revised GUI, when the date range is selected, the user will logically know to click one of the report buttons.

I agree with you and it simplifies the toolbar. But, I should point out that for a first time user, they need to:

- Populate the publishers database.
- Optionally populate the congregations database.
- Optionally add in any custom duty assignments.
- Optionally configure the calendar sync.
- Setup a backup pattern (if not already done).

Some of the above is mentioned in the [Getting Started](https://www.publictalksoftware.co.uk/help-msa/msa-quick-start.html) help topic.

> Optionally a status bar can contain tooltips etc..

There is quite a bit of work involved to get a dialog to include a status bar. Some of the other programming languages allow you to drag a toolbar onto the form, but not with Visual C++ MFC. You have to manually create and position the toolbar. It can be done, but I don't think it is worth the effort.

My thoughts:

- We already have an area at the bottom of the main window for a progress bar (backup / restore progress monitoring). Perhaps I will consider turning this into a status bar on another occasion.
- MFC buttons buttons with images and tooltips by design. We use a few of them throughout the software. So I propose using those controls.

Does anyone else have any thoughts about this?

**Comment by cengizu** [comment]
To help first-time users, the following can also be done: When the program is started for the first time, until the database is created, all unavailable options are inactive except the Publishers Database feature. This helps the program to be more intuitive.

Regarding the **status bar:** Instead of a status bar, maybe a label or panel showing the current settings can also be considered. I will prepare a concept and submit. The idea would be to provide the user with some basic information at a glance. For example, when the program is installed for the first time, a text like "You need to create a database" could be displayed.

**Comment by ajtruckle** [comment]
#@cengizu The **At a Glance** concept is a nice idea too.💡 But I think I will treat that as a separate issue. That is because I will need to decide all the phrasing etc. and obtain translations.

Whereas the changes to the toolbar doesn't need translation requests.

**Comment by ajtruckle** [comment]
@cengizu 
I have added the four buttons and removed them from the toolbar:

![New Window](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/3d8433af-1267-463d-b9d8-992ef3ec0970)

But I retained the Create / Open flow-path.

**Comment by ajtruckle** [comment]
@cengizu 
I have decided to make some other changes:

![New Window](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/c4e8e822-a610-46d7-95c0-aa58b13521c7)

- Changed the position of the **Create** / **Open** buttons. Now they are grouped with related controls.
- Added new **Manage Public Talks** toolbar icon (third from left).

**Comment by ajtruckle** [comment]
@cengizu @stecchio66

I have decided to add a **status bar** as per your original proposal! It has three panes:

1. Progress bar (used for **Backup** / **Restore** progress monitoring).
2. Generic text (eg. file names).
3. Congregation Name (as specified in the Congregations Database).

See it in action 🎥:

https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/eba86772-b3cc-49bb-b2df-4ba6e59a9f69

**Comment by ajtruckle** [comment]
> That’s looking really cool. Getting better and better. Keep up the good work!

Thanks! 😊 And I appreciate your nudging me in the right direction to overhaul the main window.

**Comment by ajtruckle** [comment]
@cengizu 
I have turned the two **Open** buttons into _menu buttons_. Both not support a **Recent File List**.

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/b27b3132-dfb4-46a0-ae9d-f4659d33ff16)

**Comment by cengizu** [comment]
That is a nice touch 👍🏻

**Comment by ajtruckle** [comment]
@cengizu 
> That is a nice touch 👍🏻

I am pleased you like these additional improvements. I have started looking at the **help documentation** and bringing them up to date, These can be reviewed:

- [Overview.pdf](https://github.com/ajtruckle/meeting-schedule-assistant-support/files/13241748/Overview.pdf)
- [Using Meeting Schedule Assistant.pdf](https://github.com/ajtruckle/meeting-schedule-assistant-support/files/13241755/Using.Meeting.Schedule.Assistant.pdf)

**Comment by ajtruckle** [comment]
@cengizu 

Here is a revised version of the **Overview** help topic:

[Overview-Version 2.pdf](https://github.com/ajtruckle/meeting-schedule-assistant-support/files/13269938/Overview-Version.2.pdf)

**Comment by fstouma** [comment]
It seems that the **Create** buttons are not working even if I set the date range of the calendar.
Thank you

**Comment by ajtruckle** [comment]
@fstouma 
Thank you for bring this issue to my attention. I forgot to hook up the button click event handlers. Oops! 🤭 I am about to issue you with a beta download link via Telegram.

@cengizu 
I have taken onboard your suggestion (sent privately) to change the window to a single calendar, allowing the user to select a date range. I'll send you the same beta via Telegram.

![Updated window with new calendar](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/9befde2a-fd86-490e-a67d-49bb26351ec9)

**Comment by fstouma** [comment]
Thank you, it worked
