### ISSUE TITLE
Implement the Talk History List

### ISSUE THREAD

**Issue by ajtruckle** [ajtruckle/meeting-schedule-assistant-support#14]
**Is your feature request related to a problem? Please describe.**
In Public Talks it has a [Talk History](https://www.publictalksoftware.co.uk/help-pts/pts-editing-home-talk-entries.html#TALK_HISTORY) list feature.

**Describe the solution you'd like**
Add the Talk History list to the [Weekend Meeting Editor](https://www.publictalksoftware.co.uk/help-msa/mwb-editor-weekend-meeting.html) in Meeting Schedule Assistant. This way we get a better overview of which talks have been heard.

The Talk History list has a context menu which allows you to see a popup **Last Given By...** window which lists who has recently given the selected talk. This would be nice to implement to.

**Additional context**
Talk History List

![Talk History List](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/b39f05be-3479-4694-97e8-1e312c30c65d)

Last Given By Popup

![Last Given By](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/dd3b0bc0-9ef8-4c15-97e1-864a260e101a)

Context Menu

![Context Menu](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/5b22e559-106b-4a42-b491-af5e8a5e4542)

**Comment by ajtruckle** [comment]
This is one possible concept:

![GUI Concept](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/cc6c22f2-2edc-4c05-8bc1-f2eb5a4a07b8)

**Comment by ajtruckle** [comment]
And here is another concept:

![GUI Concept](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/abad37a3-04ec-4768-ad67-d9b0338d823f)

**Comment by cengizu** [comment]
> This is one possible concept:
> 
> ![GUI Concept](https://user-images.githubusercontent.com/7985331/278261263-cc6c22f2-2edc-4c05-8bc1-f2eb5a4a07b8.png)

This one seems like the most logical place. I also looked to see if we could make some of the elements a bit smaller to free up some space, but no. This suggestion is good

**Comment by cengizu** [comment]
> And here is another concept:
> 
> ![GUI Concept](https://user-images.githubusercontent.com/7985331/278263318-af25bae7-6b79-4500-b563-f350b8be8fdf.png)

This one seems like the most logical place. I also looked to see if we could make some of the elements a bit smaller to free up some space, but no. This suggestion is good

**Comment by ajtruckle** [comment]
@cengizu 
I have been working on this feature over the last couple of days. There is still a bit of work to do but I think most of it is done.

Have a look:

![Talk Hist Grid](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/52c7d7ab-4376-43ac-bb85-da9007dc766a)

The following has been implemented

- Speakers _assigned_ / _favourite_ talks are listed first (in the chosen colours) in **bold**.
- Talks that are give _locally_ are indicated with a hash symbol #️⃣.
- _Sort_ by either column, and in both directions, by clicking the header cells.
- _Right-click_ to display a popup menu.

**Comment by ajtruckle** [comment]
@cengizu 
I made some other refinements to this feature and started writing the help documentation. This is adapted from the Public Talks help topic:

[Talk-History-Help.pdf](https://github.com/ajtruckle/meeting-schedule-assistant-support/files/13208129/Talk-History-Help.pdf)

**Comment by stecchio66** [comment]
@ajtruckle 
This is good for me.
Thanks!
