### ISSUE TITLE
Custom Congregations Report — Date Range

### ISSUE THREAD

**Issue by ajtruckle** [ajtruckle/meeting-schedule-assistant-support#15]
**Is your feature request related to a problem? Please describe.**
We can write our own custom scripts but there is no way for us to easily limit information to a chosen **date range**.  This becomes an issue when reading information from the **Assignment History** database for inclusion on a report.

**Describe the solution you'd like**
Can the _Congregations_ > _Report Viewer_ > [Setup](https://www.publictalksoftware.co.uk/help-msa/msa-congdb-report-viewer-setup.html) window be updated to include:

1. A **Custom** report mode option.
2. An area to specify a **date range** (for information read from the **Assignments History** database).

**Additional context**
_Public Talks_ has a [Custom Reports Setup](https://www.publictalksoftware.co.uk/help-pts/pts-new-custom-reports.html) window which has a similar feature:

![Custom Reports Setup](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/66f1ceb5-f234-4072-b4e9-0fb1d0d24b36)

<hr>

Here is one example use case. I wanted to try to replicate this custom report script in _Meeting Schedule Assistant_:

[Custom Report Script — Hospitality List](https://www.publictalksoftware.co.uk/support-forums/topic/custom-report-script-version-of-the-hospitality-list/)

![Sample](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/ceef7ebe-f7b5-4a4a-abee-cf3cd4a447ec)

This could be replicated quite easily using the [Congregations Report Viewer](https://www.publictalksoftware.co.uk/help-msa/msa-congdb-report-viewer.html) by reading the _assignment history database_. But, then it dawned on me that I couldn't limit the data displayed to a specific **date range**. I am sure that this flexibility could be useful for other types of Congregation Reports.

**Comment by ajtruckle** [comment]
I was thinking of something like this:

![Updated Setup window](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/15bbcd3f-1263-4123-bce7-929171872f12)

This report would create a XML file, something like:

```xml
<CongregationDatabaseReport>
    <Settings>
        <LanguageCode>en</LanguageCode>
        <Direction>ltr</Direction>
        <ForeignGroupMode>false</ForeignGroupMode>
        <ReportMode>Custom</ReportMode>
    </Settings>
    <AssignmentHistory>
        <PublicTalkInfo>
            <MeetingDate Day="31" DayShort="Sun" DayFull="Sunday" Month="10" MonthShort="Dec" MonthFull="December" Year="2023">31/12/2023</MeetingDate>
            <PublicTalkChairman>Chairman</PublicTalkChairman>
            <PrayerOpen>Brother</PrayerOpen>
            <PrayerClose/>
            <VideoConferenceHost/>
            <VideoConferenceCohost/>
            <ZoomAttendant/>
            <PublicTalkSpeaker>Name</PublicTalkSpeaker>
            <PublicTalkCongregation>Congregation</PublicTalkCongregation>
            <PublicTalkTheme>Is There a True Religion From God's Standpoint?</PublicTalkTheme>
            <PublicTalkNumber>173</PublicTalkNumber>
            <PublicTalkHospitality/>
            <WatchtowerConductor>Conductor</WatchtowerConductor>
            <WatchtowerReader>Reader</WatchtowerReader>
            <BibleVersesReader/>
            <Interpreter/>
            <AwayTalks>
                <AwayTalk>
                    <Speaker>Speaker</Speaker>
                    <TalkNumber>180</TalkNumber>
                    <Congregation>Congregation</Congregation>
                    <MeetingDate Day="31" DayShort="Sun" DayFull="Sunday" Month="10" MonthShort="Dec" MonthFull="December" Year="2023">31/12/2023</MeetingDate>
                    <MeetingTime>10:00</MeetingTime>
                </AwayTalk>
            </AwayTalks>
            <Misc/>
        </PublicTalkInfo>
    </AssignmentHistory>
</CongregationDatabaseReport>
```

A XSL template can now be written to display the Hospitality Report.

**Comment by ajtruckle** [comment]
Proposed GUI changes:

![New Window](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/a35ef715-2140-4660-9ff7-f8c174b68b5d)

**Comment by ajtruckle** [comment]
@cengizu

I have been giving this some thought 🤔 and have decided to make some addition changes to the GUI. This is what we have now:

![New Window](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/8292d817-0a09-4387-9654-37fe83e97479)

The **Report mode** is now a _combo box_ and makes it easier for me to extend the **built-in** report modes. Also, the _Assignment History_ snippet (extracted using your chosen _date range_) is now included in the XML for _all_ report modes. This allows the user more flexibility for writing their own scripts.

**Comment by ajtruckle** [comment]
@cengizu
Here is updated help documentation:
[Congregations-Setup.pdf](https://github.com/ajtruckle/meeting-schedule-assistant-support/files/13283454/Congregations-Setup.pdf)

**Comment by stecchio66** [comment]
@ajtruckle 
Very good work. The help documentation is simple, clear but complete.
