### ISSUE TITLE
Support for January / February 2024 Workbook Changes

### ISSUE THREAD

**Issue by ajtruckle** [ajtruckle/meeting-schedule-assistant-support#17]
Several changes to the meeting workbooks affect the Meeting Editor (beginning January 2024):

- Different student item descriptions.
- Additional brochure for study point.
- Multiple discussions.
- Explain my Beliefs can be talk or discussion.

I am looking at implementing the following changes:

![New Materials window](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/a44fbe33-9ae7-43ea-9f82-d3f127a70bfa)

1. Add a new drop-list to specify the **source** of the study. There will be two options: _th_ & _lmd_.
2. The drop-list of **study numbers** (for _lmd_) would be like:

1 - 1
1 - 2
1 - 3
1 - 4
1 - 5
2 - 1
2 - 2 etc.

And the **tooltips** for each:

> 1 - Interest in Others (point 1)
> 1 - Interest in Others (point 2)
> 1 - Interest in Others (point 3)
> 1 - Interest in Others (point 4)
> 1 - Interest in Others (point 5)
> 2 - Commitment (point 1)
> 2 - Commitment (point 2)
> 2 - Commitment (point 3)
> 2 - Commitment (point 4)
> 2 - Commitment (point 5)
> 3 - Simplicity (point 1)
> 3 - Simplicity (point 2)
> 3 - Simplicity (point 3)
> 3 - Simplicity (point 4)
> 3 - Simplicity (point 5)
> 4 - Courage (point 1)
> 4 - Courage (point 2)
> 4 - Courage (point 3)
> 4 - Courage (point 4)
> 4 - Courage (point 5)
> 5 - Naturalness (point 1)
> 5 - Naturalness (point 2)
> 5 - Naturalness (point 3)
> 5 - Naturalness (point 4)
> 5 - Naturalness (point 5)
> 6 - Kindness (point 1)
> 6 - Kindness (point 2)
> 6 - Kindness (point 3)
> 6 - Kindness (point 4)
> 6 - Kindness (point 5)
> 7 - Humulity (point 1)
> 7 - Humulity (point 2)
> 7 - Humulity (point 3)
> 7 - Humulity (point 4)
> 7 - Humulity (point 5)
> 8 - Tact (point 1)
> 8 - Tact (point 2)
> 8 - Tact (point 3)
> 8 - Tact (point 4)
> 8 - Tact (point 5)
> 9 - Boldness (point 1)
> 9 - Boldness (point 2)
> 9 - Boldness (point 3)
> 9 - Boldness (point 4)
> 9 - Boldness (point 5)
> 10 - Perseverance (point 1)
> 10 - Perseverance (point 2)
> 10 - Perseverance (point 3)
> 10 - Perseverance (point 4)
> 10 - Perseverance (point 5)
> 11 - Patience (point 1)
> 11 - Patience (point 2)
> 11 - Patience (point 3)
> 11 - Patience (point 4)
> 11 - Patience (point 5)
> 12 - Empathy (point 1)
> 12 - Empathy (point 2)
> 12 - Empathy (point 3)
> 12 - Empathy (point 4)
> 12 - Empathy (point 5)

3. In the list of student item **descriptions** on the far left we would include:

- Starting a Conversation
- Following Up
- Making Disciples
- Explaining Your Beliefs
- Explaining Your Beliefs (Talk)
- Talk

4. The **Discussions** area would be updated to allow for _two_ discussions. Some of the current controls in this area of the window would be removed from view.

<hr>

This concept might need to be revised 🤔  since I am not sure what will happen when there is only _one discussion_. There are potentially three variations:

1. _Before_ student items
2. _In-between_ student items
3. _After_ student items.

**Comment by fstouma** [comment]
It appear it is the best way to update according to the new revision. But, instead of adjusting this every time, can you make it more flexible, I mean, just a field to type the text in it? this is for the Student assignment.

**Comment by ajtruckle** [comment]
@fstouma 

> It appear it is the best way to update according to the new revision. But, instead of adjusting this every time, can you make it more flexible, I mean, just a field to type the text in it? this is for the Student assignment.

Thanks for the suggestion. The lesson number will be a _drop list_. This is for two reasons:

1. This information has to be saved to the _history database_. The data needs to be a specific format. 
2. Consistent with the existing way it works.

**Comment by ajtruckle** [comment]
@fstouma 

Eventually I _might_ be able to let you type, eg 1 - 5 and it automatically select it. Or, _paste_ the reference and it _decode_ it. 

But, my priority is to get the core functionality in place. Then these finer points can be considered.

**Comment by ajtruckle** [comment]
So, when you select _th_ in the combo it will show the regular **Teaching** lessons:

![Teaching Lessons](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/4d4d41e1-8b03-4d13-a2f5-8466504503b4)

And, when you select _lmd_ in the combo it will show the new **Love People** lessons:

![Love People Lessons](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/e4043a4f-9804-4743-863a-74ad68e1a32b)

**Comment by stecchio66** [comment]
@ajtruckle
Your proposals seem correct to me and cover all the needs known so far.

> This concept might need to be revised 🤔 since I am not sure what will happen when there is only one discussion. There are potentially three variations:

We can wait for this?

**Comment by ajtruckle** [comment]
@fstouma @stecchio66 
I have now added the new student item descriptions. At the moment they are hard-coded in English:

![Student item descriptions](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/75788286-adbc-4f1e-963b-689de4814cea)

**Comment by MardoDan** [comment]
Hasta ahora se ve muy bien y a primera vista es la mejor manera de actualizar MSA. Después veremos si se puede ir corrigiendo. Excelente trabajo!!!

**Comment by cengizu** [comment]
Looks good to me, sufficient for at least the first months. Then time will tell which part needs to be revised.

**Comment by ajtruckle** [comment]
Thanks for the feedback brothers. This is turning into a larger task than I have first envisioned.  This is because I need to change the way I store the study points internally. But we will get there!

So, I have completed:

- Allowing the user to specify the student material information on the popup Material window.
- Serialization of the updated student material information (not yet tested) to MWB file.
- Adjusted the monthly workbook data feature to include the new student material information.

Next on my TODO list:

1. Displaying updated student material information on the schedule.
2. Synchronization to online calendars.
3. Multiple Discussions (as per the concept design).

**Comment by ajtruckle** [comment]
I have another update for you for weeks _without_ discussions. 😊.

### Sample Week ###
![Sample](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/4b26641c-4cd3-40e1-a7ce-a3b3b4e8a732)

### Meeting Editor ###
![Meeting Editor](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/369a7614-6065-432f-911d-8b723e0fdfce)

The work continues...

**Comment by ajtruckle** [comment]
I noticed that I noted down the lesson text from the new brochure in the wrong order. This has been corrected.

**Comment by ajtruckle** [comment]
During beta testing we realised that changes needed to be made to the **Students** window to cope with the new _brochure references_. In addition, work has been underway to:

- Update assignment history database.
- Sync to Outlook calendar.

**Comment by ajtruckle** [comment]
I am starting to add in the extra controls for the second Discussion assignment. This is what it looks like:

![Window updated with additional discussion controls](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/28b2ed74-a16f-44c3-bc0b-c11b9e43126f)

**Comment by ajtruckle** [comment]
I am working on the changes needed for the [Discussion with Video](https://www.publictalksoftware.co.uk/help-msa/mwb-editor-section3.html) window. This is my concept:

![Discussion with Video](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/cde8e1c9-1baa-44b2-965c-69ce18dd266c)

There are two things to keep in mind:

1. The Meeting Editor lets you select a brother from the Assignment History popup window if it is visible.
2. The Meeting Editor lets you select a name from the history list on the right.

 So I will need to extend that to work with the new combos. And I now realize that we need to include this second discussion in the assignment history serialization.

**Comment by stecchio66** [comment]
@ajtruckle 
the window with new material assignment for 2 discussion is ok.

**Comment by ajtruckle** [comment]
@cengizu @stecchio66 @fstouma @MardoDan 

I have been thinking 🤔 about the [S-89 Assignment Slip](https://www.publictalksoftware.co.uk/help-msa/mwb-editor-section7.html#Assignment_Slip_Settings) settings window. Here is a design concept:

![Assignment Slip Window](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/81e127fa-8d8a-4a2a-99ad-b9a985d204e6)

We change it so that the user can specify the formatting of the study reference for _both_ brochures:

- Teaching (_th_)
- Love People (_lmd_)

Suggested formatting codes for _lmd_:

- `%l` for **lesson**.
- `%p` for **point**.
- `%d` for **description**.
 
We can discuss what pre-defined samples to include in the drop-down list. I welcome your comments.

**Comment by fstouma** [comment]
good, great idea. thank you

**Comment by ajtruckle** [comment]
@cengizu 

> Slips: duplicate references. Seems to only occur at specific times where reference is within ( ) parenthesis. In other cases, it works fine.
> ![Custom Slips](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/39ca18c7-7476-48b6-84b5-f4bf6064c1f2)

Thanks for the feedback. I was able to reproduce this issue. I am sharing a beta link (no. 13) via Telegram for you to try.

**Comment by ajtruckle** [comment]
@cengizu @stecchio66 @fstouma 

### Workbook Reference ###
(lmd lesson 11 point 3)

Drop-list Choices

- `User Defined`
- `11-3`
- `#11-#3`
- `11-3 Simplicity`
- `11-3 - Simplicity`
- `11-3. Simplicity`
- `#11-#3 Simplicity`
- `#11-#3 - Simplicity`
- `Simplicity (11-3)`

Matching format strings:

- `""`
- `%l-%p`
- `#%l-#%p`
- `%l-%p %d`
- `%l-%p - %d`
- `%l-%p. %d`
- `#%l-#%p %d`
- `#%l-#%p - %d`
- `%d (%l-%p)`

I propose a new **format specifier**: `%b` (_th_ or _lmd_).

Eg:

`%d (%b %l-%p)` = Simplicity (lmd 11-3)

**Comment by ajtruckle** [comment]
@stecchio66 @cengizu @fstouma 

I decided to do it this way:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/992b015a-e4bd-4724-a1ac-5e682ac5031e)

**Comment by ajtruckle** [comment]
@cengizu 
Here are the updated help topics for review please:

- [Section 3 Apply Yourself to the Field Ministry.pdf](https://github.com/ajtruckle/meeting-schedule-assistant-support/files/13395459/Section.3.Apply.Yourself.to.the.Field.Ministry.pdf)

- [Edit Assignment Material.pdf](https://github.com/ajtruckle/meeting-schedule-assistant-support/files/13395457/Edit.Assignment.Material.pdf)

- [Revision History.pdf](https://github.com/ajtruckle/meeting-schedule-assistant-support/files/13395458/Revision.History.pdf)

**Comment by ajtruckle** [comment]
This feature is now implemented and is available in version 24.2.0.

> [!NOTE]  
>  The [online newsletter](https://www.publictalksoftware.co.uk/2023/11/msa-version-24-2-0-news/) for version **24.2.0** is now available.
