### ISSUE TITLE
Updating Public Talks Database using Database Menu

### ISSUE THREAD

**Issue by cengizu** [ajtruckle/meeting-schedule-assistant-support#18]
**Is your feature request related to a problem? Please describe.**
Public Talks Database can be updated by using **Database > Public Talks > Update** menu. The update file (as I understand it) is downloaded and installed again and again each time the user clicks on it, regardless of when it was last downloaded. This creates unnecessary workload on the server and does not clearly inform the user whether local database is up to date (even if it is updated). 
![Screenshot 2023-11-15 112341](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/dbc01705-40b4-4325-9f8a-9ad27839a7fc)

**Describe the solution you'd like**
A simple control mechanism. The program can decide whether an update is available in one of several ways. Here are two that comes to my mind: 
- check if the update file has already been downloaded. If not, download and install as usual. If it already exists, check its date (or version), then display a warning message like "An update was last downloaded on [this date], do you still want to download it?". If user accepts, download and install, otherwise quit. 
- The program first checks the date/version of the local database and then connects to the server to see if there is an update. Then it starts the process or informs the user that there are no updates.

**Comment by ajtruckle** [comment]
@cengizu 
Thanks for the idea 💡. It would make sense to do something along the lines of what you suggest. We could introduce a `Updated `attribute like you said to each public talks database:

`<PublicTalkTitles Update="YYYY-MM-DD">`

And I could maintain a simple XML file on my website that indicates the _latest update date_ for each language. I just have to remember to keep that file accurate or find a way to automate it.

We could then do this:

- Download the XML file from the server.
- Extract the latest update date for the language being used.
- Extract the current update date from the active public talks database.
- Compare the dates:
    - **Newer** - prompt to download and update.
    - **Same** - popup message saying you have the latest public talks database installed.
    - **Older** - have a moan at me because I obviously forgot to update the XML file on the website! 🤭

**Comment by ajtruckle** [comment]
@cengizu 
I'm adding a link to a related StackOverflow question that I asked ([Can we automatically create a XML database during compilation with Inno Setup?](https://stackoverflow.com/q/77514384/2287576)). A suggestion has been provided that will help us automate some of this process.

**Comment by ajtruckle** [comment]
@cengizu 

This is what I have done so far:

- Add a `Version` attribute to all XML files with an initial value of `1.0`.
- Create a PowerShell script that automatically builds the "lookup info" file that we need for the website.
- Run the script whenever I re-build the Public Talk Titles installer.

I just need to remember to increment the version number in the relevant XML file whenever someone informs me of a change. 😊

**Comment by ajtruckle** [comment]
@cengizu 

I have completed implementation of this feature request and sent you a beta for testing.

**Comment by cengizu** [comment]
It works good. Thank you.
