### ISSUE TITLE
The Toolbar is missing after upgrading to 24.2.2

### ISSUE THREAD

**Issue by AutomanRJJ** [ajtruckle/meeting-schedule-assistant-support#20]
**Describe the bug**
After I upgraded to 24.2.2 I now no longer have icons/graphics for each of the sections such as Publisher Database, Calendar Options, Settings and such.  They are all blank.

**To Reproduce**
Upgrade.
Uninstall and reinstall.

**Expected behavior**
I expect to have graphics where they were before.

**Screenshots**
<img width="415" alt="image" src="https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/36166728/1cc0ba63-3d0e-49e8-9394-b9fc081070fb">

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 22H2 (Build 22621.2715)
 - Webview2: Version 119.0.2151.58
 - Webview2 SDK Build: 2088.41

**Additional context**
I tried completely removing the application and the user profile settings under "C:\Users\autom\AppData\Roaming\Meeting Schedule Assistant" and then reinstalled, this did not change the appearance of the icons on the application.
This is post 11-2023 security patching cycle.

**Comment by ajtruckle** [comment]
@AutomanRJJ 
I am sorry for this issue with the toolbar not displaying. And thanks for the information you have provided and detailing the steps you have taken to fix it. 

I know of one other user who has the same issue. Can you please confirming what your display settings are?

- Resolution
- Text scaling

I might to provide you with a debug version of the software to see if we can track down the issue.

**Comment by AutomanRJJ** [comment]
I have 3 monitors, 2 (including the primary monitor) are at 3840x2160 150% Scale Non HDR mode, the 3rd monitor is at 1280x1024 100% Scale.

https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/b095f194-45d3-46d1-b1fa-711bcba6e677

Rick Jones

**Comment by ajtruckle** [comment]
@AutomanRJJ 
Thanks for the extra information. My development PC is using Windows 11 Home, but it has the same build as you reported. And my WebView2 matches yours.

The only thing jumping out at me at the moment is that my configuration is:

- 2 monitors
- 1920 x 1080 display resolution
- 100% text scale

So the only thing jumping out at me is the screen resolution being much higher. But if it used to work before … 🤔

**Comment by ajtruckle** [comment]
@AutomanRJJ 
I have just noticed that my toolbar image has the wrong dimensions:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/25055e16-a168-4ca5-93b5-130baea1df04)

It is 595 x 587 instead of 288 x 32! I must have corrupted it when I removed the toolbar buttons.

Definitely better now:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/8dee053b-dc8e-47f5-9600-e92e616bc596)

I have just re-released 24.2.2 on the website. Please manually download and install it. Let's hope this fixes the issue.

**Comment by AutomanRJJ** [comment]
That was it, the updated version fixed it!

Rick Jones
