### ISSUE TITLE
Add a Summary panel to the main window

### ISSUE THREAD

**Issue by ajtruckle** [ajtruckle/meeting-schedule-assistant-support#21]
**Is your feature request related to a problem? Please describe.**
At the moment, it is difficult to know who is doing what _without_ opening a SRR / MWB data file or viewing an online calendar.

**Describe the solution you'd like**
In Public Talks it has a useful **Summary** panel:

![Public Talks - Summary panel](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/262fa3a5-91e5-4426-a7d8-d884769fb771)

Could we add a similar panel in Meeting Schedule Assistant? Something like this:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/327c57f9-e290-4e62-9e10-e2bf88e773f8)

**Additional context**
The information presented in the summary panel would come from the _assignment history_ database and it would change as you select a different date on the calendar. We could agree what information gets displayed.

**Comment by cengizu** [comment]
Good idea. However, determining what to display would be difficult.

**Comment by ajtruckle** [comment]
@cengizu 

> Good idea. However, determining what to display would be difficult.

I'm thinking about that. 🤔💭

**Comment by ajtruckle** [comment]
@cengizu 

> Good idea. However, determining what to display would be difficult.

I'm thinking about that. 🤔💭 Here is the kind of information we could display:

| Midweek Meeting | Weekend Meeting |
| ------------- | ------------- |
| Chairman  | Chairman |
| Aux Chairman 1  | Opening Prayer |
| Aux Chairman 2  | Speaker |
| Opening Prayer| Speaker Congregation |
| Treasures | Talk Number / Theme |
| Spiritual Gems | Interpreter |
| Living 1 | Hospitality |
| Living 2 | WT Conductor |
| Living 3 | WT Reader |
| CBS | Bible Verses Reader |
| CBS Reader| Closing Prayer|
| Closing Prayer | |

Only their _names_ would be shown (not _themes_ or anything). And I have deliberately excluded _students_ for the time-being. In _Public Talks_ it has settings to control what [Summary Info](https://www.publictalksoftware.co.uk/help-pts/pts-summary-info.html) is displayed:

![Summary Info Settings](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/6ffd13ee-963b-4a8b-992e-b4e682f2040b)

We could do something similar in _Meeting Schedule Assistant_ if it was deemed necessary.

**Comment by ajtruckle** [comment]
@cengizu 
Another concept 💡 for this is a **tree control**. Public Talks uses one of these controls on the talks maintenance page:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/6a3300c7-9c91-49b9-acd3-d0d3c5b51777)

We could have one tree control that covers the whole week. Both meetings could be two expandable trees. And we could possibly come us with some icons to give the feature a bit of life. This way the user can potentially review everything for the meetings irrespective of the date.

And, we could maybe allow the user to directly go to edit a speakers details, or a congregations details by double click the entry. It would also be nice because it is presenting the details differently to Public Talks GUI.

Thought? 🤔

**Comment by cengizu** [comment]
In terms of usability and modern GUI, tree view controls look both outdated and pretty bad. I suggest using simpler/minimalist elements for this summary.

Here is a concept:
![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/d1be06b6-51fa-40f2-b807-b524ec970240)

Why not to use the tree view control:
- https://blog.codinghorror.com/trees-treeviews-and-ui/
- https://ripul.blogspot.com/2005/10/tree-view-removal-surgery_112919819961257081.html

**Comment by ajtruckle** [comment]
@cengizu 
Certainly makes for interesting reading!  I think I'll just stick with my original idea then of using the [`CGridCtrl`](https://www.codeproject.com/Articles/8/MFC-Grid-control-2-27). Since it is already part n parcel of MSA.

**Comment by ajtruckle** [comment]
@cengizu 
Just wanted to show the progress made so far:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/1a5163e6-41ed-4c4e-87a0-c7a935b1b165)

I have decided to use a `CMFCPropertyGridCtrl` to represent the summary information.

Work in progress …

**Comment by ajtruckle** [comment]
@cengizu 
Some improvements have been made:

- Main window is now resizable. This allows you to see more calendar months and a larger summary panel.
- Summary info for this week is automatically displayed then application starts.
- The labels now support localization. Most terms are already used within the software.

Some scenarios we should consider:

- Special Assembly Day / Regional Convention
- Circuit Visit
- Memorial Week
- Branch Visit
- Other events
- No history data yet

**Comment by ajtruckle** [comment]
@cengizu 

* No history data yet

Proposal:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/21d2266f-fbd9-4312-9998-36523c41c988)

**Comment by ajtruckle** [comment]
@cengizu 

* Memorial

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/07c08ed9-6eeb-454d-8dec-8a7a53d4a16d)

* Special Event

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/a65cdddd-6165-488d-bb16-9ebc471ab1a0)

It now tries to find any associated special event in the database for that week. It does this by checking all 7 dates (Monday to Friday). Information is displayed if an event is located.

If it is the Memorial it will show:
* Start Time
* End Time
* Chairman
* Open Prayer
* Speaker
* Theme
* Close Prayer
* Host
* Co-Host
* Zoom Attendant

If it is a Special Event (eg. Circuit Assembly or Regional Convention) it will show:
* All day event
* Start Time
* End Time
(Times only display if it is not an all day event).

I still need to cater for the Bethel Speaker Weekend and Circuit Visit.
I have since updated the Memorial to display the start / end times.

**Comment by ajtruckle** [comment]
@cengizu @stecchio66 
I have been making some minor changes to the way I display the Special Event information.

We display this information for all special events:

- Event description
- Location
- Date
- All day [yes / no]
- Start time [disabled if all day event]
- End time [disabled if all day event]

If it is a Memorial event it also shows:

- Chairman
- Open prayer
- Speaker
- Theme
- Close prayer
- Host
- Co-host
- Zoom attendant

If it is a Bethel Speaker Weekend event it also shows:

- Chairman
- Open prayer
- Speaker
- Theme
- Close prayer (just uses speaker)
- Host
- Co-host

For some reason the Bethel Speaker Window window does not allow you to select a Zoom Attendant.

**Comment by ajtruckle** [comment]
Related StackOverflow Q & A:

[Text position in CMFCPropertyGridCtrl](https://stackoverflow.com/questions/77851227/text-position-in-cmfcpropertygridctrl)
