### ISSUE TITLE
A more informative and functional Slips tab

### ISSUE THREAD

**Issue by cengizu** [ajtruckle/meeting-schedule-assistant-support#22]
**Is your feature request related to a problem? Please describe.**
When clicking on the Slips tab, if the S-89 form is not already installed, it gives a warning in the form of: "Please send an email or contact us to upload the S-89 form". When this message window is ignored or OK button is clicked, the program switches to a different tab other than the Slips tab. A more elegant solution should be placed here to avoid giving the impression that there is a bug in the program.

**Describe the solution you'd like**
Instead of Slips tab displaying an alert/warning message, let the application inform user gently what to do within this tab, displaying the message inside. This lets Slip tab remain functional (as it should) regardless of S-89 slips are installed or not. Since HTML is available in this tab, it may be possible to provide information with a simple html page.

Here is a concept design, but should be improved and simplified:
![MSA-S-89 Slips](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/43e38571-1a68-411d-8174-16dba9320932)

**Comment by ajtruckle** [comment]
@cengizu 

I agree that this is a good idea 💡 and should be implemented. It will be much better than the way I am doing it at the moment.

Displaying a custom page will be easy enough to do. I needed to do some research about the following:

- How to use JavaScript code to change the text displayed on the page to match the user interface.
- How to get the WebView2 browser control to display the Contact Form with the computers default browser.

This feature has now been implemented (translations withstanding) and I have sent a beta to you for testing.

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/3a58299e-6849-427d-a2f5-06734200b845)

**Comment by ajtruckle** [comment]
@cengizu 

I have done a quick review of the **help documentation** and I don't think we specifically say anything about what happens when you click the **Slips** preview tab _when no templates are installed_. So I assume no changes are needed for the help. 😊

And I'll use the wording of this ticket for the **Revision History**:

> A more informative and functional Slips tab

I know that I did a video tutorial ([Using S-89 Assignment Slips](https://www.publictalksoftware.co.uk/videos/using-s-89-assignment-slips/)) back in 2017 but I don't think that needs to be changed either.

**Comment by cengizu** [comment]
@ajtruckle Yes, the help documentation can remain untouched and the Video tutorial is also still valid. With this update, only the way of informing the user has changed: A message embedded in the tab instead of a distracting pop up message.
