### ISSUE TITLE
Make date and time format options 

### ISSUE THREAD

**Issue by srv-999** [ajtruckle/meeting-schedule-assistant-support#23]
Please add some flexible options configurable from the app (instead of having to edit the sheets which sometimes have to be changed globally).

1. Select date for the meeting so maybe Day Date e.g.
Thursday 23rd November

2. Also have the option to choose between either start time or end time for items

Great to see new format in and working though !!!!!!

**Comment by ajtruckle** [comment]
@srv-999 

> Great to see new format in and working though !!!!!!

Thank you! I am glad we managed to get something working in time. 👍
<hr>
Thanks for the suggestions! 💡 I think we could introduce a new popup window to let you customize the **Date and Time** properties:

* **Date** —  Have some controls to let you customize the _date_ format.
* **Time** — Have some radio options to let you choose how to display the _time_:
    * **12 hour**
    * **24 hour**
    * **Start Time**
    * **End Time**

The values of these properties would be included in the `Settings` part of the XML data file. Then I can adjust the XSL templates design to respect these settings. You would need to make similar changes to your own XSL templates to make them compatible. But I'll explain what to do!

**Comment by ajtruckle** [comment]
@srv-999 

I was thinking of a window like this:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/43f81506-6538-4fc6-8a53-7d48c47ee710)

- The _default_ date setting would be how it works now (eg. _November 20-26_)
- Set the **Use Meeting Date** checkbox to activate the other controls.
- **Select** one of the predefined date formats or **customise** as desired.
- Select **Start time** or **End time** from the drop-down list.
- Select **12 hour** or **24 hour** from the drop-down list.

The _date_ will be used in the XML data as a direct replacement so no changes would be needed for XSL templates. But the _time_ preferences would be added to the `Settings` section of the XML data. Eg:

```xml
<Settings>
    <Use24HourFormat>1</<Use24HourFormat>
    <UseStartTime>1</UseStartTime>
</Settings>
```

I will then make the needed changes to the built-in XSL templates and show you what needs to be done to get your templates working with the new time settings.

**Comment by srv-999** [comment]
That sounds really good 👍🏻Thank you.

**Comment by ajtruckle** [comment]
@srv-999 

In terms of changes to XSL templates (_Workbook S-140_) that are needed:

1. Delete these templates as they are obsolete:

``` xml
<!--Display the end time (using 24 hour format)-->
<xsl:template match="Time" mode="End">
	<td class="cellTime">
		<xsl:value-of select="@EndTime24"/>
	</td>
</xsl:template>

<!--Display the start time (using 24 hour format)-->
<xsl:template match="Time" mode="Start">
	<td class="cellTime">
		<xsl:value-of select="@StartTime24"/>
	</td>
</xsl:template>
```

2. Add the following new templates:

```xml
<xsl:template match="Time">
	<td class="cellTime">
		<xsl:call-template name="DisplayTime"/>
	</td>
</xsl:template>

<xsl:template name="DisplayTime">
	<xsl:choose>
		<xsl:when test="//Settings/Use24HourFormat='1'">
			<xsl:choose>
				<xsl:when test="//Settings/UseStartTime='1'">
					<xsl:value-of select="@StartTime24"/>
				</xsl:when>
				<xsl:otherwise>
					<xsl:value-of select="@EndTime24"/>
				</xsl:otherwise>
			</xsl:choose>
		</xsl:when>
		<xsl:otherwise>
			<xsl:choose>
				<xsl:when test="//Settings/UseStartTime='1'">
					<xsl:value-of select="@StartTime12"/>
				</xsl:when>
				<xsl:otherwise>
					<xsl:value-of select="@EndTime12"/>
				</xsl:otherwise>
			</xsl:choose>
		</xsl:otherwise>
	</xsl:choose>
</xsl:template>

<xsl:template name="DisplayTimeEx">
	<xsl:param name="time-node"/>
	<xsl:choose>
		<xsl:when test="//Settings/Use24HourFormat='1'">
			<xsl:choose>
				<xsl:when test="//Settings/UseStartTime='1'">
					<xsl:value-of select="$time-node/@StartTime24"/>
				</xsl:when>
				<xsl:otherwise>
					<xsl:value-of select="$time-node/@EndTime24"/>
				</xsl:otherwise>
			</xsl:choose>
		</xsl:when>
		<xsl:otherwise>
			<xsl:choose>
				<xsl:when test="//Settings/UseStartTime='1'">
					<xsl:value-of select="$time-node/@StartTime12"/>
				</xsl:when>
				<xsl:otherwise>
					<xsl:value-of select="$time-node/@EndTime12"/>
				</xsl:otherwise>
			</xsl:choose>
		</xsl:otherwise>
	</xsl:choose>
</xsl:template>	
```

3. Do a find and replace:

Old: `"Time" mode="End"/>` (yours might say `mode="Start"`).
New: `"Time"`.

4.  Locate the other locations where the script uses `StartTime12`,  `StartTime24`, `EndTime12` or `EndTime24` and update:

Old: `<xsl:value-of select="@EndTime24"/>` (yours might say `@StartTime24`).
New: `<xsl:call-template name="DisplayTime"/>`

5. Finally, there is the Memorial event which needs to be done slightly differently:

Old: `<xsl:value-of select="Speaker/@EndTime24"/>` (yours might say `@StartTime24`).
New:

```xml
<xsl:call-template name="DisplayTimeEx">
	<xsl:with-param name="time-node" select="Speaker"/>
</xsl:call-template>
```

It can be a little daunting to change the XSL templates but the above should work (at-least for the display of _time_ values). You'll be able to follow these steps once I have updated the Meeting Editor. Note that I have not reviewed the _Worksheet_ built-in templates yet.

**Comment by ajtruckle** [comment]
@srv-999 

Changing the _Worksheet_ templates can be done in the same way as the **Memorial** (_step 5_ in the last [comment](https://github.com/ajtruckle/meeting-schedule-assistant-support/issues/23#issuecomment-1825943935)).

The built-in worksheet template uses `EndTime24` in all these locations:

```
Line  170: [<xsl:value-of select="SongOpen/@EndTime24"/>]
Line  193: [<xsl:value-of select="OpeningComments/Time/@EndTime24"/>]
Line  252: [<xsl:value-of select="Treasures1/Time/@EndTime24"/>]
Line  272: [<xsl:value-of select="Treasures2/Time/@EndTime24"/>]
Line  293: [<xsl:value-of select="BibleReadingTime/@EndTime24"/>]
Line  348: [<xsl:value-of select="Time/@EndTime24"/>]
Line  397: [<xsl:value-of select="StudentTalk1Time/@EndTime24"/>]
Line  502: [<xsl:value-of select="StudentTalk2Time/@EndTime24"/>]
Line  607: [<xsl:value-of select="StudentTalk3Time/@EndTime24"/>]
Line  714: [<xsl:value-of select="StudentTalk4Time/@EndTime24"/>]
Line  833: [<xsl:value-of select="SongMiddle/@EndTime24"/>]
Line  848: [<xsl:value-of select="LivingAsChristians/Item1/Time/@EndTime24"/>]
Line  870: [<xsl:value-of select="LivingAsChristians/Item2/Time/@EndTime24"/>]
Line  893: [<xsl:value-of select="LivingAsChristians/Item3/Time/@EndTime24"/>]
Line  915: [<xsl:value-of select="LivingAsChristians/CongregationBibleStudy/Time/@EndTime24"/>]
Line  933: [<xsl:value-of select="ClosingComments/Time/@EndTime24"/>]
Line  972: [<xsl:value-of select="ClosingComments/Time/@EndTime24"/>]
Line 1009: [<xsl:value-of select="LivingAsChristians/ItemCircuitOverseer/Time/@EndTime24"/>]
Line 1037: [<xsl:value-of select="SongEnd/@EndTime24"/>]
```

What you need to do:

1. Add the same `DisplayTimeEx` template:

```xml
<xsl:template name="DisplayTimeEx">
	<xsl:param name="time-node"/>
	<xsl:choose>
		<xsl:when test="//Settings/Use24HourFormat='1'">
			<xsl:choose>
				<xsl:when test="//Settings/UseStartTime">
					<xsl:value-of select="$time-node/@StartTime24"/>
				</xsl:when>
				<xsl:otherwise>
					<xsl:value-of select="$time-node/@EndTime24"/>
				</xsl:otherwise>
			</xsl:choose>
		</xsl:when>
		<xsl:otherwise>
			<xsl:choose>
				<xsl:when test="//Settings/UseStartTime='1'">
					<xsl:value-of select="$time-node/@StartTime12"/>
				</xsl:when>
				<xsl:otherwise>
					<xsl:value-of select="$time-node/@EndTime12"/>
				</xsl:otherwise>
			</xsl:choose>
		</xsl:otherwise>
	</xsl:choose>
</xsl:template>	
```

2. Change all of the locations where `@EndTime24` is used. Example:

Old:  `<xsl:value-of select="SongOpen/@EndTime24"/>`
New:

```xml
<xsl:call-template name="DisplayTimeEx">
	<xsl:with-param name="time-node" select="SongOpen"/>
</xsl:call-template>
```

I will change all _built-in_ templates when I get around to coding this new feature. But at-least you now know what customizations will be needed for your own templates.

**Comment by ajtruckle** [comment]
@srv-999 

_Worksheet_  templates need to be updated slightly differently:

1. Add these new templates:

```xsl
<xsl:template match="Time |
		SongOpen | SongMiddle | SongEnd |
		BibleReadingTime |
		StudentTalk1Time | StudentTalk2Time |
		StudentTalk3Time | StudentTalk4Time" mode="Time">
	<td class="borderDotTimeDuration">
		<xsl:if test="self::SongOpen">
			<xsl:attribute name="Style">
				border-top-style:solid
			</xsl:attribute>
		</xsl:if>
		<xsl:text>[</xsl:text>
		<xsl:call-template name="DisplayTime"/>
		<xsl:text>]</xsl:text>
	</td>
</xsl:template>

<xsl:template name="DisplayTime">
	<xsl:choose>
		<xsl:when test="//Settings/Use24HourFormat='1'">
			<xsl:choose>
				<xsl:when test="//Settings/UseStartTime='1'">
					<xsl:value-of select="@StartTime24"/>
				</xsl:when>
				<xsl:otherwise>
					<xsl:value-of select="@EndTime24"/>
				</xsl:otherwise>
			</xsl:choose>
		</xsl:when>
		<xsl:otherwise>
			<xsl:choose>
				<xsl:when test="//Settings/UseStartTime='1'">
					<xsl:value-of select="@StartTime12"/>
				</xsl:when>
				<xsl:otherwise>
					<xsl:value-of select="@EndTime12"/>
				</xsl:otherwise>
			</xsl:choose>
		</xsl:otherwise>
	</xsl:choose>
</xsl:template>
```

2. Locate all the places where `@EndTime24` is used and update. Example:

Old: 
```xsl
<td class="borderDotTimeDuration">
	[<xsl:value-of select="OpeningComments/Time/@EndTime24"/>]
</td>
```

New:

`<xsl:apply-templates select="OpeningComments/Time" mode="Time"/>`

I'll update all _built-in_ templates when I implement this feature.

**Comment by ajtruckle** [comment]
@srv-999 

I am going to send you a beta via email for you to try. I have added a new **Date and Time Settings** menu item:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/dd3c27be-1da2-47b5-8813-c55ad3790b22)

This displays the new popup window:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/e6e630da-1489-475c-9132-2d4a416b7b46)

The default settings are:

- Use Meeting Date: _Unchecked_
- Display: _End time_
- Format: _24 hour_

The display should automatically refresh when you click OK. I have updated all _built-in_ Workbook / Worksheet templates but would be grateful if you could double-check 👀 for any errors when testing the updated software.

Please add your feedback here. 👍

**Comment by ajtruckle** [comment]
Updated help documentation:

[Options Menu.pdf](https://github.com/ajtruckle/meeting-schedule-assistant-support/files/13472039/Options.Menu.pdf)

**Comment by ajtruckle** [comment]
Feedback from @srv-999 

> Works just great 😊
> No more editing xml for me 😊

**Comment by srv-999** [comment]
That’s great 😊
Today I’ll be doing the Jan/Feb schedule
