### ISSUE TITLE
Include Assignment Number on Workbook S-140

### ISSUE THREAD

**Issue by ajtruckle** [ajtruckle/meeting-schedule-assistant-support#28]
**Is your feature request related to a problem? Please describe.**
The revised _S-140 11/2023_ template has been updated to match the **January 2024** meeting workbook. <sup>[1](#myfootnote1)</sup>

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/a945c4f2-7780-4fec-8107-3c658660b0f4)

**Describe the solution you'd like**
As you can see, the schedule now shows the _assignment number_ from 1 to 10. Can the meeting editor be updated to show these numbers?

<hr>
<a name="myfootnote1">1</a>: This feature was requested by @mardodan

**Comment by MardoDan** [comment]
Sería una buena modificación para que el Informe sea igual a la Plantilla y a la Guía de Actividades que proporciona JW. Apoyo el cambio.

**Comment by ajtruckle** [comment]
S-140 11/23 received for the following languages:

- [ ] Afrikaans
- [ ] Albanian
- [ ] Amharic
- [x] Arabic (A)
- [ ] Armenian
- [ ] Aukan
- [ ] Bulgarian
- [ ] Cebuano
- [x] Chinese Simplified (CHS)
- [ ] Cibemba
- [ ] Croatian
- [ ] Czech
- [ ] Danish
- [ ] Dutch
- [x] English (E)
- [ ] Estonian
- [x] Finnish (FI)
- [x] French (F)
- [x] German (X)
- [x] Greek (G)
- [ ] Gujarati
- [ ] Gun
- [ ] Haitian Creole
- [ ] Hindi
- [ ] Hungarian
- [x] Indonesian (IN)
- [x] Italian (I)
- [x] Japanese (J)
- [ ] Lingala
- [ ] Malagasy
- [ ] Maltese
- [ ] Pidgin English
- [ ] Polish
- [x] Portuguese Brazil (T)
- [ ] Portuguese Portugal
- [ ] Punjabi
- [x] Romanian (M)
- [x] Russian (U)
- [ ] Sesotho South Africa
- [ ] Setswana
- [ ] Slovenian
- [x] Spanish (S)
- [ ] Saramaccan
- [ ] Sranantongo
- [ ] Swahili
- [ ] Tagalog
- [ ] Tamil
- [ ] Tsonga
- [ ] Turkish
- [x] Twi (TW)
- [x] Ukrainian (K)
- [ ] Vietnamese
- [ ] Zulu

**Comment by ajtruckle** [comment]
Referencing ticket: #29 
Reason: The new S-89 11/23 slips have a field for the **No. Part** which means these tickets are related to each other.

**Comment by ajtruckle** [comment]
@MardoDan 

The S-140 templates use **black text** for the assignment numbers, whereas the workbooks use **coloured text**. IMHO I think _black text_ is better for reading and will save on ink if using a printer.

I have made some changes to the underlying XML data and have been testing the output with a modified XSL workbook template. The simplest approach is to add this new template:

```xsl
<xsl:template match="@Index">
	<span style="font-size: 10pt;">
		<xsl:value-of select="."/>
		<xsl:text>. </xsl:text>
	</span>
</xsl:template>
```

Then, whenever we need to show the index, we do something like this:

```xsl
<!--Bible talk and Digging for Spiritual Gems-->
<xsl:template match="TFGWItem">
	<xsl:param name="iSpanCols"/>
	<tr>
		<xsl:apply-templates select="Time"/>
		<td colspan="{$iSpanCols+1}">
			<xsl:apply-templates select="@Index"/>
			<!--<span class="bulletTFGW">&#8226;</span>-->
			<xsl:apply-templates select="Theme"/>
			<xsl:apply-templates select="Time" mode="Duration"/>
			<xsl:apply-templates select="Method"/>
		</td>
		<xsl:apply-templates select="Name"/>
	</tr>
</xsl:template>
```

As you can see, I have commented out the bullet line and inserted:

```xsl
<xsl:apply-templates select="@Index"/>
```

Result:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/8169070c-e5b0-488c-ae79-d9609033d426)

**Comment by MardoDan** [comment]
De a poco va quedando. El tema del texto **negro** para los números de asignación, mientras que los libros de trabajo utilizan **texto coloreado** es sólo en la Guía de Actividades dado que la plantilla S-140 es en **negro**, así que está bien. Excelente trabajo @ajtruckle

**Comment by stecchio66** [comment]
@ajtruckle we can add more space between number and cell border?
If yes, how?
Thanks.

**Comment by ajtruckle** [comment]
@stecchio66 See the sample code in this ticket:

https://github.com/ajtruckle/meeting-schedule-assistant-support/issues/28#issuecomment-1836607601

Then compare against the bullets. Needs _padding_ property. I did a quick test using **Inspect** on the context menu:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/c01e15aa-4d7f-42fe-abc4-367cd8dee544)

This means, changing the code like this:

```xsl
<xsl:template match="@Index">
	<span style="font-size: 10pt; padding-right: 1mm;">
		<xsl:value-of select="."/>
		<xsl:text>. </xsl:text>
	</span>
</xsl:template>
```

That's if I understand your requirement properly. Use `padding-left` if you want a gap on the left.

**Comment by stecchio66** [comment]
@ajtruckle 
Done, thanks!

**Comment by joaofama** [comment]
Congratulations on the excellent work, it was perfect!

![print](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/442f3829-f5e1-483f-9fe4-14940f664c65)

**Comment by ajtruckle** [comment]
@joaofama 
Excellent! Thanks for bringing the issue about the **Workbook-S-140-Legacy** template not having _assignment numbers_ to my attention.
