### ISSUE TITLE
Add support for the S-89 11/23 student assignment slips

### ISSUE THREAD

**Issue by ajtruckle** [ajtruckle/meeting-schedule-assistant-support#29]
S-89 11/23 received for the following languages:

| Language              | Code | Updated    | Notes                                                  |
|-----------------------|------|------------|:--------------------------------------------------------|
|  Afrikaans            | AF   | 05/02/2024 |                                              |
|  Albanian             | AL   | 15/12/2023 |                                                        |
|  Amharic              | AM   | 14/12/2023 |                                                        |
|  Arabic               | A    | 11/12/2023 |                                                        |
|  Armenian             | REA  | 15/12/2023 |                                                        |
|  Aukan                | AKN  |            | S-89 10/18                                             |
|  Bulgarian            | BL   | 15/12/2023 |                                                        |
|  Cebuano              | CV   | 03/12/2023 | Uses English                                           |
|  Chinese Simplified   | CHS  | 14/12/2023 | Missing dotted underscore from the _Part Number_ field |
|  Cibemba              | CW   | 03/12/2023 | Uses English                                           |
|  Croatian             | C    | 15/12/2023 |                                                        |
|  Czech                | B    |            | S-89 10/18                                             |
|  Danish               | D    | 15/12/2023 |                                                        |
|  Dutch                | O    | 12/12/2023 |                                                        |
|  English              | E    | 02/12/2023 |                                                        |
|  Estonian             | ST   |            | S-89 10/17                                             |
|  Finnish              | FI   | 18/02/2024 |                                              |
|  French               | F    | 11/12/2023 |                                                        |
|  German               | X    | 15/12/2023 |                                                        |
|  Greek                | G    | 02/12/2023 |                                                        |
|  Gujarati             | GU   | 30/03/2024 |                                            |
|  Gun                  | EG   |            | S-89 10/17                                             |
|  Haitian Creole       | CR   |            | S-89 11/20                                             |
|  Hindi                | HI   |            | S-89 10/18                                             |
|  Hungarian            | H    | 18/12/2023 |                                                        |
|  Indonesian           | IN   | 12/12/2023 |                                                        |
|  Italian              | I    | 02/12/2023 |                                                        |
|  Japanese             | J    | 12/12/2023 |                                                        |
|  Lingala              | LI   |            | S-89 11/20                                             |
|  Malagasy             | MG   |            | S-89 10/17                                             |
|  Maltese              | MT   |            | S-89 10/18                                             |
|  Pidgin West Africa   | PGW  | 03/12/2023 | Uses English                                           |
|  Polish               | P    | 15/12/2023 |                                                        |
|  Portuguese Brazil    | T    | 11/12/2023 |                                                        |
|  Portuguese Portugal  | TPO  | 12/12/2023 |                                                        |
|  Punjabi              | PJ   |            | S-89 10/19                                             |
|  Romanian             | M    | 15/12/2023 |                                                        |
|  Russian              | U    | 02/12/2023 |                                                        |
|  Sesotho South Africa | SSA  | 27/06/2024 |                                             |
|  Setswana             | TN   |            | S-89 11/20                                             |
|  Slovenian            | SV   |            | No slip                                                |
|  Spanish              | S    | 02/12/2023 |                                                        |
|  Saramaccan           | SRM  |            | S-89 10/18                                             |
|  Sranantongo          | SR   |            | S-89 10/19                                             |
|  Swahili              | SW   | 11/12/2023 |                                                        |
|  Swedish              | Z    | 11/01/2024 |                                             |
|  Tagalog              | TG   | 03/12/2023 | Uses English                                           |
|  Tamil                | TL   |            | S-89 10/18                                             |
|  Tsonga               | TS   | 05/02/2024 |                                              |
|  Turkish              | TK   |            | S-89 11/20                                             |
|  Twi                  | TW   | 11/12/2023 |                                                        |
|  Ukrainian            | K    | 12/12/2023 |                                                        |
|  Vietnamese           | VT   | 11/12/2023 |                                                        |
|  Zulu                 | ZU   | 11/08/2024  |                                            |

Also, update the new S-89 11/23 to the [Export S-89 Data](https://www.publictalksoftware.co.uk/help-msa/mwb-editor-export-s89-data.html) feature.

| Field Name          | Description           |
|---------------------|-----------------------|
| 900_1_Text_SanSerif | Full name             |
| 900_2_Text_SanSerif | Assistant             |
| 900_3_Text_SanSerif | Date                  |
| 900_4_Text_SanSerif | No. Part              |
| 900_5_CheckBox      | Main hall             |
| 900_6_CheckBox      | Auxiliary classroom 1 |
| 900_7_CheckBox      | Auxiliary classroom 2 |

**Comment by ajtruckle** [comment]
The proposal for the **No. Part** field on the slip is:

`[Assignment Number] [Student Item Description]`.

Some example:

> 4. Starting a Conversation
> 5. Following Up
> 6. Making Disciples
> 6. Explaining Your Beliefs
> 6. Explaining Your Beliefs (Talk)
> 6. Talks

The [Counsel Point](https://www.publictalksoftware.co.uk/help-msa/mwb-editor-section7.html#Counsel_Point) (managed via **Slip Settings** window) could continue to be displayed as an optional custom field.

<hr>
My concern is some of the languages that MSA support have been using older slips. So it will be hard to support all types of slips as the content changes a lot. But we will see what we can do.

**Comment by ajtruckle** [comment]
I have made changes to support the new English assignment slip. So all I need to do is replicate those changes for the remaining slips. Hopefully I will receive the remaining slips (single - PDF) by email in the coming days.

**Comment by ajtruckle** [comment]
I noticed that the available width of the _part number_ field on the S-89 11/2023 slip is much shorter in some languages. So we might have to add a new slip setting to let you configure how this field is populated.

**Comment by ajtruckle** [comment]
I am closing this ticket now. I'll keep it up-to-date as and when users send me the remaining S-89 11/23 slips.

**Comment by Nil-nil-0** [comment]
Hello, everything is fine? I would like S-89 11/23 in Brazilian Portuguese. Thank you!

**Comment by ajtruckle** [comment]
@Nil-nil-0 , I am fine thank you. 😀 Please _privately_ email me your S-89 11/23 PDF and I will email you the templates with instructions.

**Comment by Nil-nil-0** [comment]
> @Nil-nil-0, Eu estou bem, obrigado. 😀 Por favor, envie-me por e-mail seu PDF S-89 11/23 _em particular_ e eu lhe enviarei por e-mail os modelos com instruções.

To which email?

**Comment by ajtruckle** [comment]
@Nil-nil-0 

> To which email?

You can use the Contact Form on the website and upload your PDF that way. 

https://www.publictalksoftware.co.uk/contact-form/
