### ISSUE TITLE
How can we handle symposiums?

### ISSUE THREAD

**Issue by ajtruckle** [ajtruckle/meeting-schedule-assistant-support#3]
Sometimes a public talk is given by two brothers. This usually happens when a Ministerial Servant is progressing in the congregation and is assigned his first public talk.

How can _Meeting Schedule Assistant_ handle this?

**Comment by stecchio66** [comment]
Good question!

**Comment by ajtruckle** [comment]
Hi @stecchio66 

Please give the concept some thought 🤔. We need to come up with a proposal for the GUI and consider any impact on other parts of the software.  I am currently working on ticket https://github.com/ajtruckle/meeting-schedule-assistant-support/issues/1.

**Comment by fstouma** [comment]
HI.
You might do this as you did the part of "Living as Christians". There is a pull down menu which indicates how many parts under the main one. Can you make similar to this in the section of public talks?

**Comment by ajtruckle** [comment]
@fstouma 
@stecchio66 
@cengizu
We have been thinking that it might be a good idea to make use of the Speaker **hamburger** context menu for this:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/5e7d3378-b31b-4ab4-9932-8443d7db99cb)

1. We could add a **Symposium** menu item that opens a popup window allowing you to select both speakers (or the second speaker).
2. Including a Symposium image in the popup window could make the selection process clearer and more visually appealing.

**Comment by ajtruckle** [comment]
@cengizu
Concerning: https://github.com/ajtruckle/meeting-schedule-assistant-support/issues/51#issuecomment-2138907882

> If there will be a symposium window, then menu entry has "..." to indicate a dialog is opening.

My idea was to show a popup window to allow the user to select the second brother The first brother could be also shown in a read-only control for reference.

On the main window, the Symposium text (if visible), should show the current name of the second brother.

**Comment by ajtruckle** [comment]
@stecchio66 @cengizu @fstouma 
Just to bring some of the suggestion that were discussed in ticket #51 into this ticket:

### Icon ###
This is the proposed icon as located by Cengiz:
https://www.flaticon.com/free-icon/group_3394744?term=multiple&related_id=3394744

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/8cf3f3b3-0972-460a-bbd5-33fa41759949)

### Placement ###
The icon will be placed as a clickable button, like this:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/94bc3229-9518-430a-b0f0-7a94fa6fd57d)

### Behaviour ###
* Proposal 1
    * Hover mouse over button to see second brother in a tool tip.
    * Click the button to display a popup window:
        * The first speaker will be displayed in a disabled drop-list
        * The second speaker can be selected in a second drop-list
        * There will be a blank entry in the second drop-list. This will in effect switch off the symposium aspect

* Proposal 2
    * The icon is changed into a static icon (not clickable)
    * The icon is disabled when not a symposium
    * Add Symposium … to the hamburger menu
        * This will disable the popup window
        * Again, selecting a blank entry will switch off the symposium aspect

The issue with the second approach is that implementing a tooltip for the static icon is more complex. Therefore, I suggest opting for the first proposal, as the tooltip seems necessary.

### MWB File ###
The second name will be saved to the MWB file, with the default set as an empty text string, indicating the absence of a symposium.

### Calendar Sync ###
The calendar synchronization should be adjusted to incorporate the second name. The precise wording can be settled upon in due time.

### Templates ###
The Workbook/Weekend Worksheet templates require updates to recognize the symposium and display the secondary name. We can decide on this functionality in due time.

### Other Observations ###
* I assume you've already assigned the chosen talk to the second speaker in the congregation database. If not, we could resolve the issue by using the "Add to list of assigned talks" feature and assign it to both speakers simultaneously.
* We may need to adjust our logic concerning moving or swapping home talks to accommodate a symposium.

**Comment by stecchio66** [comment]
@ajtruckle 
Your "Proposal 1" is ok (IMHO).
How do you understand that there is a symposium without hovering the mouse over the button?

**Comment by ajtruckle** [comment]
@stecchio66 

> Your "Proposal 1" is ok (IMHO).
> 
> How do you understand that there is a symposium without hovering the mouse over the button?

How about having a checkbox (with no wording) to the left of the icon?

- Tick checkbox to enable symposium button.
- Untick to switch off symposium feature and disable button.
- This check value will be stored in the MWB etc.
- The default would be false. 

So:

[tick][icon]

**Comment by stecchio66** [comment]
@ajtruckle 
> How about having a checkbox (with no wording) to the left of the icon?

Good solution.

**Comment by ajtruckle** [comment]
@stecchio66 @fstouma @cengizu

> Click the button to display a popup window:
> * The first speaker will be displayed in a disabled drop-list
> * The second speaker can be selected in a second drop-list
> * There will be a blank entry in the second drop-list. This will in effect switch off the symposium aspect

The popup window might be as straightforward as this, with **Speaker 1** _pre-selected and disabled_:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/78304b03-eaac-4779-9dcc-0f92076d68ef)

I don't think it is necessary to include additional information like the talk date or outline information.

**Comment by cengizu** [comment]
![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/4cfc48b1-9946-4772-bbdd-a1f05c327e46)

**Comment by cengizu** [comment]
A simulation of the functioning

**A.** Symposium is disabled by default. Requires user action. The name of the selected speaker appears in the speaker list.

**B.** When Symposium is selected, the dialog prompts the user for 2 speaker names.

When the OK button is pressed, the Speaker list can list the names of two speakers, for ex.: 
- on one line: Speaker 1/ Speaker 2 
![Screenshot 2024-06-03 101410](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/a9b72e35-df9a-46cd-9036-5e0a6deb77ef)

- Speakers in 2 lines
![Screenshot 2024-06-03 101743](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/472fd02b-7c99-40a2-897a-769227962412)

- Or just Symposium
![Screenshot 2024-06-03 101501](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/b3fc00cb-ec0e-4302-ab9f-ac111919791c)

**C.** If the user wants to opt out of the symposium, they must click the Symposium button again and disable the second speaker and things work as before.

**Comment by ajtruckle** [comment]
@cengizu 
I need to work "with what I have". The combo is designed to show the list of speakers for the congregation. I see no reason the complicate it and break the mould. Simply allow the selection of the first participant from this list. The second participant will be selected on the popup.

By having a checkbox on the main window it makes it simple. The user can see immediately if there is a symposium.  And current names on tooltip. This way I keep the changes to a minimum to the respective files.

**Comment by ajtruckle** [comment]
@Fahdeya
@stecchio66 
@cengizu 

* Add checkbox
* Add symposium button
* Enable symposium button when checkbox is ticked

https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/151689c9-8824-45d2-9122-bbc7943ca9ca

**Comment by cengizu** [comment]
https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/8982ae93-8dd9-42a5-be45-18e3785b7e8b

**Comment by ajtruckle** [comment]
@Fahdeya
@stecchio66
@cengizu

Thanks for doing the video snippet Cengiz. 🙏

Update:

* Save to MWB (saved files are not binary compatible with older versions of the software)
* Read from MWB
* Update workbook XSL templates

I replaced a code snippet with:

```xml
<xsl:choose>
	<xsl:when test="Symposium='1'">
		<span class="textPTSLabel">
			<xsl:value-of select="//Labels/PTS_Speakers"/>:
		</span>
		<xsl:text> </xsl:text>
		<span class="textPTSValue">
			<xsl:value-of select="Speaker"/>
		</span>
		<xsl:text> / </xsl:text>
		<span class="textPTSValue">
			<xsl:value-of select="Speaker2"/>
		</span>
	</xsl:when>
	<xsl:otherwise>
		<span class="textPTSLabel">
			<xsl:value-of select="//Labels/PTS_Speaker"/>:
		</span>
		<xsl:text> </xsl:text>
		<span class="textPTSValue">
			<xsl:value-of select="Speaker"/>
		</span>
	</xsl:otherwise>
</xsl:choose>
```

**Comment by ajtruckle** [comment]
@Fahdeya
@stecchio66
@cengizu

Update:

* Save to assignment history database
* Display symposium on Swap content menu
* Handle moving of symposium to another date
* Handle swapping of symposium with another date

I don't think that any changes are needed for the **MWT Transfer** feature. But users will need to use MWT files created with this version (or newer).

**Comment by ajtruckle** [comment]
@Fahdeya
@stecchio66
@cengizu

Update:

* Update weekend worksheet XSL template

I replaced a code snippet with:

```xml
<tr>
	<td class="blank first">
		<xsl:value-of select="HomeTalk/Time/@StartTime24"/>
	</td>
	<td>
		<xsl:choose>
			<xsl:when test="HomeTalk/Symposium=1">
				<xsl:value-of select="//Labels/PTS_Speakers"/>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="//Labels/PTS_Speaker"/>
			</xsl:otherwise>
		</xsl:choose>
		<xsl:text>:</xsl:text>
	</td>
	<td>
		<xsl:choose>
			<xsl:when test="HomeTalk/Symposium=1">
				<xsl:value-of select="HomeTalk/Speaker"/>
				<xsl:text> / </xsl:text>
				<xsl:value-of select="HomeTalk/Speaker2"/>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="HomeTalk/Speaker"/>
			</xsl:otherwise>
		</xsl:choose>
		<xsl:text> (</xsl:text>
		<xsl:value-of select="HomeTalk/Congregation"/>
		<xsl:text>)</xsl:text>
	</td>
</tr>
```

**Comment by ajtruckle** [comment]
@Fahdeya
@stecchio66
@cengizu

In my previous [comment](https://github.com/ajtruckle/meeting-schedule-assistant-support/issues/3#issuecomment-2143511844) I mentioned:
> I assume you've already assigned the chosen talk to the second speaker in the congregation database. If not, we could resolve the issue by using the "Add to list of assigned talks" feature and assign it to both speakers simultaneously.

I have not yet addressed this final issue and am open to your thoughts.

**Comment by ajtruckle** [comment]
@Fahdeya
@stecchio66
@cengizu

> I have not yet addressed this final issue and am open to your thoughts.

Upon reflection, I feel that this is the best way forward:

1. Add hamburger to Symposium window. 
2. Click hamburger to display Add menu. 
3. Add code to add talk for second speaker. 

This is the simplest for me to implement and requires no translations. After all, a symposium is infrequent, so allowing the shortcut to add the talk to the second speaker should be sufficient. 

This is how I want to proceed to complete this feature.

**Comment by ajtruckle** [comment]
@Fahdeya
@stecchio66 
@cengizu 

I have decided to handle it like this:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/1c5b9250-2fec-4bc8-a2b4-52670e2eac49)

We now display this new menu when the talk is a symposium. This allows you to add the talk to either speaker (if required).

**Comment by Fahdeya** [comment]
Hi all,

Thank you for your effort to make this application more practical. But, I have been serving as an elder for 30+ years, and till now, no one in our country uses this arrangement. So, I am not in position to add any comment.

I am not saying that what we are doing is the best, but, sadly this is the case here.

**Comment by ajtruckle** [comment]
@Fahdeya 
That is alright. I appreciate your taking to provide feedback. I understand. 🙏

**Comment by KOUKLHS** [comment]
Σε ευχαριστώ για την προσπάθεια ώστε η εφαρμογή να είναι πιο πρακτική.
Αλλά είναι Λίγο Σπάνιο Στην Εκκλησία να έχουν 2 Αδερφοί την Ίδια Ομιλία.
Πάντως λειτουργεί Καλά.

**Comment by ajtruckle** [comment]
@KOUKLHS 
Thanks for the feedback and testing it out. 🙏 Symposiums have been done in both of the congregations I have been in. There is an official procedure for doing talks as symposiums. 

Infact, my first public talk in about 2008 was a symposium. But I admit they are infrequent. Nice to have the facility now though, for when it is needed.
