### ISSUE TITLE
Erro ao designar participantes

### ISSUE THREAD

**Issue by metaconsultoria** [ajtruckle/meeting-schedule-assistant-support#30]
Tem computador que uso que não é possível designar os participantes, a caixa aparece vazia. Ao trocar de computador já normaliza. Porque isso acontece, em alguns computadores não aparece a lista de participantes cadastrados?

**Comment by ajtruckle** [comment]
@metaconsultoria I don't have enough information to provide you with an answer. You say that:

> There are computers I use that can't assign participants, the box appears empty. When I change computers, it normalizes. Why does this happen, on some computers the list of registered participants doesn't appear?

How are you _changing computer_? Are you using the built-in backup / restore tools to do this? Please confirm.

**Comment by ajtruckle** [comment]
@metaconsultoria I did not get a response. Have you resolved this issue?

**Comment by ajtruckle** [comment]
@metaconsultoria I am going to close this issue as no feedback has been provided.
