### ISSUE TITLE
Meeting Workbook Transfer issue with new discussion items

### ISSUE THREAD

**Issue by stecchio66** [ajtruckle/meeting-schedule-assistant-support#33]
Meeting Workbook Transfer don't clone new discussion items and is not possible restore it.

**Comment by ajtruckle** [comment]
@stecchio66 
Try new beta I put on Google Drive. It now clones the second discussion. Not tested. Let me know if there is still issues.

**Comment by stecchio66** [comment]
@ajtruckle 
The discussions are saved and then restored. But the weeks when there are discussions, are not disabled the other students items.

**Comment by ajtruckle** [comment]
@stecchio66 
Ah, I forgot to clone the _student assignment flags_. These indicate whether student assignments are included or not. I'll send you a new beta tomorrow afternoon.

**Comment by stecchio66** [comment]
@ajtruckle 
With the last beta the problem seems to be solved.
