### ISSUE TITLE
Editor tab zoom issue

### ISSUE THREAD

**Issue by stecchio66** [ajtruckle/meeting-schedule-assistant-support#34]
The zoom level in the Editor tab is not saved and if we close and reopen the meeting editor the zoom level is ever 100%.

**Comment by ajtruckle** [comment]
The zoom factor is actually saved to the registry correctly:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/d61ea005-8c78-42ad-bc4b-ca23611bbe19)

These registry keys are updated immediately whenever you change the zoom factor.

<hr>
I notice that the WebView2 control defaults to 100% when it is initially created. So there may be a race-condition between the initialization and our subsequent attempt to restore the last used zoom factor setting. But I will continue to investigate and see if I can work out a way to resolve it.

**Comment by ajtruckle** [comment]
@stecchio66 
I realise what is going on now.

- When the WebView2 control is _initialised_ it _defaults_ to a zoom factor of 100%. 
- But, when the meeting editor is being displayed, we _update the menu_ and status bar to match the zoom factor in the WebView2.
- This value (from WebView2) then gets _saved again_ to the registry.

Once the editor is displayed the above behaviour is fine. It is only during initialisation where the above logic is flawed.

**Comment by ajtruckle** [comment]
@stecchio66 
I have put a new beta in the Google Drive folder for you to try. It should behave correctly now. 😊

**Comment by stecchio66** [comment]
@ajtruckle 
It looks good
