### ISSUE TITLE
 Import from History Database issue

### ISSUE THREAD

**Issue by stecchio66** [ajtruckle/meeting-schedule-assistant-support#35]
Import from History Database function don't restore new discussion items.

**Comment by ajtruckle** [comment]
@stecchio66 
This one confuses me because I did add code to support the second Teaching assignment. I will have to investigate.

**Comment by ajtruckle** [comment]
@stecchio66 
I am sorry, but I am not able to reproduce this issue.

1. Create new schedule.
2. Download data (F6).
3. Import from Database History  (MWB mode)
4. Refresh (F5)

When I do this I find that the assignees have been correctly read in from the history for the new discussion items.

**Comment by stecchio66** [comment]
@ajtruckle 
You're right, I hadn't downloaded the data (F6).
Everything works.
