### ISSUE TITLE
Viewing future / past talk assignments

### ISSUE THREAD

**Issue by ajtruckle** [ajtruckle/meeting-schedule-assistant-support#4]
**Is your feature request related to a problem? Please describe.**
Just remembered that in Public Talks you can right-click the speaker:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/c8ef8d12-3907-4133-9e80-fff5b4992582)

**Describe the solution you'd like**
Could the [Weekend Meeting Editor](https://www.publictalksoftware.co.uk/help-msa/mwb-editor-weekend-meeting.html) do something similar?

**Describe alternatives you've considered**
N / A

**Additional context**
As long as the data is in the history database. Then pull this information out for display in the context menu.

**Comment by ajtruckle** [comment]
It is a good suggestion, but the **Weekend Meeting Editor** already has a [history list](https://help-msa.publictalksoftware.co.uk/mwb-editor-weekend-meeting.html#ASSIGNMENT_HISTORY) on the right-hand side which we could possibly harness.  🤔

**Comment by ajtruckle** [comment]
I suggest that we add this history to the speaker's popup menu:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/47a8ee26-8357-4671-8bae-27a96b8acdff)

Eg:

- Move Assignment
- Swap Assignment
- [separator]
- **Future Assignments**
- **Past Assignments**
- [separator]
- Manage

**Comment by cengizu** [comment]
or is it possible to use the Assignments History panel for this purpose?

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/5e27d42f-406e-4dcc-8c79-c18c2155abd2)

**Comment by ajtruckle** [comment]
@cengizu 
> or is it possible to use the Assignments History panel for this purpose?

I contemplated utilizing the history panel but decided against it. The initial screenshot I shared was incorrect as it depicted the Away Talk window. The Home Talk window also encompasses the **Congregation** information:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/ffe2f4d8-3fd3-4bac-b63e-2318aabc94b5)

This information won't really fit the design concept of the Assignments History panel.

**Comment by cengizu** [comment]
@ajtruckle 

OK, if it is not possible to display this information in any other way, there is no choice but to use this method.

**Comment by ajtruckle** [comment]
@cengizu 
We could make the following changes to align the concept of this feature with the way the Assignment History panel works:

* Adjusting the history list to show all speakers from the selected Congregation whenever it is changed.
* Displaying the most recent date they gave a talk, whether at home or away, on the left.
* Making the Lookup cell bold if they are scheduled for future talks, either home or away.
* Modifying the popup Lookup window to display upcoming dates in bold.
    * Date
    * Congregation
    * Talk number
    * Talk theme

This would align it with the functionality of the Weekend Meeting window. Thus:

* For your home congregation, it will display the most recent date, whether home or away, and the history will encompass both, including the names of the congregations.
* For congregations that are not your home, it will display the most recent date at home, and the history will contain only home records. There is no need to display the congregation names in the history list.

The benefit is that we are exposing all available history that w have for all speakers in selected congregation.

**Comment by cengizu** [comment]
@ajtruckle 

this would be great!

**Comment by ajtruckle** [comment]
@cengizu 

After consideration, I believe we should omit the history of away talks since we are organizing a home talk. We only need to know the date and talk number of each speaker's last visit to our hall. By selecting 'Lookup', we can access a complete record of all the talks they have delivered here.

We could possibly handle away talk history independently. No promises!

**Comment by ajtruckle** [comment]
@cengizu 
I am sending you a beta version with the following improvements:

- The history list now populates when a different congregation is selected.
- The history list is sorted by date.
- The selected speaker updates when a name is clicked in the grid.

> [!NOTE]
> I have managed to get to the bottom of the quirky behaviour where the history grid kept resetting after clicking on a name 😊. And, I still need to handle the **Lookup** functionality.

**Comment by ajtruckle** [comment]
@cengizu 
I am sending you another beta version with the following improvements:

* Fixed an issue where the talk history item was incorrectly set as a future event.
* Added support for the Lookup window.

Here are some examples:

![image](https://github.com/user-attachments/assets/e4e2b780-0a09-48ca-9085-6eb79c00ccd3)

![image](https://github.com/user-attachments/assets/f122bad6-3577-4704-a973-6e6abcc629ee)

**Comment by ajtruckle** [comment]
@cengizu 
I am sending you another beta version with the following improvements:

- The **Speaker** label is now correctly positioned above the history grid.
- The history grid updates when either the **Congregation** or **Speaker** combo box is clicked.
- The history grid also updates when navigating using the **Tab** key.

**Comment by ajtruckle** [comment]
@cengizu @stecchio66 @Fahdeya @KOUKLHS

I have been thinking about another improvement to this feature! When you set focus to the Congregation combo get the history list to display a sorted list of the last time each congregation was invited. Clicking a congregation will select it. And clicking Lookup will display the full set of dates.

**Comment by ajtruckle** [comment]
@cengizu @stecchio66 @Fahdeya @KOUKLHS

The latest beta has some improvements:

* Set focus to the Congregation combo get the history list to display a sorted list of the last time each congregation was invited..
* Click the Lookup button to see a complete list of who has visited to give a talk, and when.
* Clicking a congregation will select it in the combo.

The above implements similar functionality that was available in [Public Talks](https://www.publictalksoftware.co.uk/help-pts/pts-congregations.html#Congregation_Information_Pane) where you could sort the Congregation list by Last Invited date. We now have the same, via the information panel.

**Comment by KOUKLHS** [comment]
Αδερφέ σε Ευχαριστώ για την Ενημέρωση.

**Comment by ajtruckle** [comment]
@cengizu 
I previously stated:

> We could possibly handle away talk history independently. No promises!

I forgot that we already display information in the panel with you click Away Talk assignments. As documented in the help. 👍

**Comment by ajtruckle** [comment]
Updated help topics:

* https://github.com/ajtruckle/meeting-schedule-assistant-support/wiki/mwb-editor-weekend-meeting#assignment-history
* https://github.com/ajtruckle/meeting-schedule-assistant-support/wiki/mwb-editor-weekend-meeting-hist
* https://github.com/ajtruckle/meeting-schedule-assistant-support/wiki/msa-revision-history

**Comment by cengizu** [comment]
@ajtruckle 

In my opinion, the mission has been successfully accomplished. Thank you for your efforts!
