### ISSUE TITLE
Allow custom text for the middle song

### ISSUE THREAD

**Issue by ajtruckle** [ajtruckle/meeting-schedule-assistant-support#41]
**Is your feature request related to a problem? Please describe.**
In Workbook 5/6 2024 (week 24-30) the middle song is **Give Me Courage**.

**Describe the solution you'd like**
We need a button / checkbox (like for Closing song) to specify the custom song title.

**Additional context**

**Comment by ajtruckle** [comment]
I have made a start of this enhancement and will provide a beta in due course.

**Comment by KOUKLHS** [comment]
Στο Τετράδιο Εργασιών 5/6 2024 (εβδομάδα 24-30) το μεσαίο τραγούδι
Χρειαζόμαστε ένα κουμπί / πλαίσιο ελέγχου (όπως για το Κλείσιμο τραγουδιού) για να καθορίσετε τον προσαρμοσμένο τίτλο του τραγουδιού.

**Comment by KOUKLHS** [comment]
Σε ευχαριστώ πολύ για τον χρόνο που διαθέτεις και την πολύτιμη βοήθεια που μας παρέχεις

**Comment by ajtruckle** [comment]
@KOUKLHS 
Thanks for your kind words my brother!

I have now made most of the required changes to the editor. All I need to do now is make the necessary changes to the built-in _Workbook_ and _Worksheet_ templates. So I hope to have a beta for you to test tomorrow.

**Comment by ajtruckle** [comment]
@KOUKLHS 
Please try beta 6 in the MSA Collaboration folder on Google Drive. Things to test:

- Using the new Custom Text button.
- Save / Load from MWB.
- Export monthly data.
- Workbook templates.
- Worksheet templates.

Please note that MWB files saved with version 24.2.9 can't be opened by older versions of the software. And I still need to update the translations / help documentation.

<hr>

## Template Changes ##
Changes will need to be made to any custom templates as detailed below.

### Workbook ###
New code block:
```xsl
<!--Displays the song information-->
<xsl:template match="SongOpen | SongMiddle | SongEnd">
	<td class="cellTime">
		<xsl:call-template name="DisplayTime"/>
	</td>
	<td class="cellTheme">
		<xsl:if test="self::SongMiddle">
			<xsl:attribute name="colspan">3</xsl:attribute>
			<xsl:attribute name="class"></xsl:attribute>
		</xsl:if>
		<span>
			<xsl:attribute name="class">
				<xsl:choose>
					<xsl:when test="self::SongOpen">bulletTFGW</xsl:when>
					<xsl:otherwise>bulletLAC</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:text>&#8226;</xsl:text>
		</span>
		<xsl:if test="self::SongOpen or (self::SongMiddle and . != '0') or (self::SongEnd and . != '0')">
			<span class="textSongLabel">
				<xsl:value-of select="//Labels/Song"/>
			</span>
			<span class="textSongNumber">
				<xsl:value-of select="."/>
			</span>
		</xsl:if>
		<span class="textSongTitle">
			<xsl:value-of select="@Title"/>
		</span>
	</td>
	<xsl:if test="self::SongOpen or self::SongEnd">
		<td class="cellPosition">
			<xsl:value-of select="//Labels/Prayer"/>
		</td>
	</xsl:if>
</xsl:template>
```
Change:
- from :
```xsl
<xsl:if test="self::SongOpen or self::SongMiddle or (self::SongEnd and . != '0')">
```
- to:
```xsl
<xsl:if test="self::SongOpen or (self::SongMiddle and . != '0') or (self::SongEnd and . != '0')">
```

### Worksheet ###
New code block:
```xsl
<td class="borderDotTheme" colspan="2">
	<xsl:if test="SongMiddle != '0'">
		<xsl:value-of select="//Labels/Song"/>&#160;
		<xsl:value-of select="SongMiddle"/>&#160;
	</xsl:if>
	<span class="textSongTitle">
		<xsl:value-of select="SongMiddle/@Title"/>
	</span>
</td>
```
Change:
- from:
```xsl
<xsl:value-of select="//Labels/Song"/>&#160;
<xsl:value-of select="SongMiddle"/>&#160;
```
- to:
```xsl
<xsl:if test="SongMiddle != '0'">
	<xsl:value-of select="//Labels/Song"/>&#160;
	<xsl:value-of select="SongMiddle"/>&#160;
</xsl:if>
```

These changes only need to be made if you are using your own version of the built-in templates.

**Comment by ajtruckle** [comment]
@KOUKLHS 
Please try beta 7 in the MSA Collaboration folder on Google Drive. I have now updated the translations.
