### ISSUE TITLE
Quick Access to Custom Assignments from Publishers Window

### ISSUE THREAD

**Issue by cengizu** [ajtruckle/meeting-schedule-assistant-support#46]
**Is your feature request related to a problem? Please describe.**
In its current usage, when the user wants to create a Custom Assignment for the Assignments list inside a Publishers window, they must first close the Publishers window and click Options > Custom Assignments from the main menu. After creating the item, open the Publishers window again. This is confusing and can be made more practical.

**Describe the solution you'd like**
With a button placed inside the Publishers window, users can easily access the Custom Assignments window.

**Proposed GUI**
![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/880c3800-e7e9-4524-b3b8-c576c2241112)
With a button placed just below this section, the Custom Assignments window can be opened without leaving Publishers. It makes sense to align the button to the left, but it's up to you.

**Additional context**
It should be noted here that the changes to be made in the Custom Assignments window should be visible in the Publishers window as soon as the OK button is pressed.

**Comment by ajtruckle** [comment]
@cengizu 
This is a good suggestion! 💡 We could turn it into a button with an icon if you wanted.

The button icon can be:

* 16 x 16, 24 x 24 or 32 x 32. I suggest 24 x 24.
* PNG 
* Transparent.

If an image is found and we want to add it as a **menu item**, then we will need a regular 16 x 16 menu item image too (24 bit).

**Comment by cengizu** [comment]
@ajtruckle 
Some ideas for the button:
![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/0335e172-ef04-480a-83b8-170c5f902b2e)

**Comment by ajtruckle** [comment]
@cengizu 
Those are interesting. Maybe the two on the right as we have few page like icons with pencils already. The ones on the right are unique.

**Comment by ajtruckle** [comment]
@cengizu 
I am sending you a beta to try on Google Drive.

**Comment by ajtruckle** [comment]
@cengizu 
Here is the updated help topic. I don't expect you to review the whole topic. Just drill down to the new section about **Custom Assignments**.

[Publishers Database Help Topic.pdf](https://github.com/ajtruckle/meeting-schedule-assistant-support/files/14390018/Publishers.Database.Help.Topic.pdf)

**Comment by cengizu** [comment]
@ajtruckle 

I propose to add some more descriptive text for this **Custom Assignments** section:
For ex.

In the Publisher window, you can choose from a preset list of assignments. The **Custom Assignments** feature allows you to include tasks not included in the default list. This feature accommodates any unique tasks within your congregation or any new assignments that may arise in the future. By using the Custom Assignments window, you can incorporate/remove/edit these assignments as needed.

**Comment by ajtruckle** [comment]
@cengizu 
That's a great suggestion! Agreed. 👍
