### ISSUE TITLE
A more user friendly Calendar Options window

### ISSUE THREAD

**Issue by cengizu** [ajtruckle/meeting-schedule-assistant-support#47]
**Is your feature request related to a problem? Please describe.**
In current use, when the Calendar Options window opens, we see that there are 2 calendar options, Outlook and Google. All settings are active, which is confusing for a first-time user. Logically, no settings should be available unless you are logged in.

**Describe the solution you'd like**
![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/c548165c-1ff2-4d50-b941-88b43714aac3)
All other features in this window should be disabled unless **Sign-In** or **Authorize** is performed. This will allow for a more user-friendly experience and self-explanatory use.

**Possible Challenges**
Since calendars are independent of the program, I don't know if it is possible to check whether the user is logged in or not, which could be a technical challenge.

**Comment by ajtruckle** [comment]
@cengizu 
> Since calendars are independent of the program, I don't know if it is possible to check whether the user is logged in or not, which could be a technical challenge.

One possible solution to this issue is to see if the list of calendars is empty:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/9d233930-efa5-4185-a7f8-d9fdec4e76d4)

The list of calendars will be populated if you are successfully signed into Google or Outlook.

**Comment by ajtruckle** [comment]
@cengizu 
I am sending you a beta to try via Google Drive.

**Comment by cengizu** [comment]
![Recording 2024-02-24 210632](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/76c5bd45-0617-40d1-b21d-cf85a7d6bdd3)

Works great! Thank you 😍
