### ISSUE TITLE
Add Auxiliary Classroom Counsellor assignment to Publisher Database

### ISSUE THREAD

**Issue by ajtruckle** [ajtruckle/meeting-schedule-assistant-support#48]
**Is your feature request related to a problem? Please describe.**
I wanted to talk about the Auxiliary Classroom Counsellor. In our hall the elders are starting to use three Ministerial Servants.  At the moment I had to add these 3 servants as Midweek Chairman.

**Describe the solution you'd like**
So I am wondering about creating a new Auxiliary Class Counsellor assignment that you need to tick in the Publisher Database window. The Meeting Editor would be updated to use the publishers who have this assignment.

**Additional context**
The S-38 2023 does state:

> Each auxiliary class should have a qualified counsellor, preferably an elder. Where necessary, a well-qualified ministerial servant may be assigned.

So it makes sense that we have a distinct assignment for this role.

We would be adding it to this checklist:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/aa8da437-bbe1-4efc-b1c8-30aebee42f87)

**Comment by cengizu** [comment]
@ajtruckle 
yes, definitely, that's the most logical location for this 👍🏻

**Comment by ajtruckle** [comment]
@cengizu 
I did an initial implementation and sent you a beta to try.

**Comment by cengizu** [comment]
@ajtruckle 
yes, it works 👍🏻

**Comment by stecchio66** [comment]
@ajtruckle
I think your idea is right. Better to have separate lists for chairman and auxiliary counselor.
The last beta work well.

**Comment by ajtruckle** [comment]
@cengizu @stecchio66 
Thanks for feedback. I now realise that I also need to:

- Add the label to LabelsInfo.xml. 
- Update Publisher Assignments report to display the new heading for the new assignment column.

**Comment by ajtruckle** [comment]
@cengizu @stecchio66 
I have now added the **Auxiliary Classroom Counsellor** label to the `LabelsInfo.XML` file. And I have revised the `PublisherDB--Publishers Assignments.XSL` report template to include this new assignment:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/9a6ac525-8a1b-4483-840d-ea69cede7a6a)
