### ISSUE TITLE
Consolidate Setting and More Settings windows

### ISSUE THREAD

**Issue by ajtruckle** [ajtruckle/meeting-schedule-assistant-support#49]
**Is your feature request related to a problem? Please describe.**
Users might not realise there are additional application settings in the software, and that you have to click More Settings to view them.

**Describe the solution you'd like**
Simplify the GUI by consolidating these windows into a one:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/a0bebc79-f088-4c7f-86c3-e27a4e1a8521)

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/8308d55e-7d8c-441c-92a0-db25b5e98c89)

**Additional context**
This is what the new settings window would look like:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/f05fab8e-d83b-4307-b12d-beefc966bd10)

**Comment by cengizu** [comment]
@ajtruckle 

This is a great improvement! This way it will be much more efficient when settings are organized in one window, with tabs like this, rather than in two different windows/dialogs. Such improvements will also make users want to use/discover all the features.

**Comment by ajtruckle** [comment]
@cengizu 
I am glad that you like the idea 💡.

Do you think that we could use this opportunity to refresh the look and feel of the icons in the property sheet?

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/4dc493b4-db07-4f5a-bf46-aeb87d028c7d)

**Comment by cengizu** [comment]
@ajtruckle 

Here are some icons that can be used:
![preferences_whitebg](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/0bee5fc8-1b62-4b47-b225-0420c5dbb73c)

**Comment by ajtruckle** [comment]
@cengizu 
Thanks for sending me the new icons. Looks great! 😊

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/299c206c-5f06-401e-a7e8-6b67b9f07c71)

Now, there are another couple of issues that I would like to tackle if possible. The first has to do with the **Congregation** setting:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/a9fd42e8-e3e4-49e5-bcaa-820a3c8f2671)

This is a legacy setting because it has now been superseded by the **Congregation Database** / **Local Congregation** name.  I have examined my code and there are two places where I still use the legacy setting. My proposal:

1. Update both instances to use the new methodology.
2. Remove the legacy Congregation setting from the GUI.

**Comment by cengizu** [comment]
@ajtruckle 

I agree, Congregation setting is not necessary. It should be removed from GUI. 

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/93fbfd86-a79c-471d-a1b8-660908a5bab5)

**Comment by ajtruckle** [comment]
@cengizu 
My thoughts exactly. So this is what the new Settings window looks like now:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/18ebbd22-f396-43ff-9d8f-ac90b5f77006)

**Comment by ajtruckle** [comment]
@cengizu 
The final issue with the Settings window is the **Meeting Times**:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/9ce64529-ed9f-4f8a-afa9-744a38d560b6)

We recently introduced the Congregations Database which has its own settings for the weekend meeting:

- Day of Week
- Time

So some parts of the software make use of this setting. But other parts of the software make use of the legacy Meeting Time settings. My initial thought was to add the Midweek Meeting properties to the Congregation window, to keep it in one place. And then adjust the the software to consistently get the times from here.

The Meeting Editor lets you override the times from the Edit menu and this would still work, because it is held in the MWB data file.

Thoughts? 🤔

**Comment by cengizu** [comment]
@ajtruckle 

One location to manage all times will be much better, less confusing, I agree 👍

**Comment by ajtruckle** [comment]
@cengizu 
OK, there is a bit more work involved to implement the changes, as it affects the tools DLL library. But I will look at it. And I think for clarity the Congregation window should use:

* Midweek Meeting
* Weekend Meeting

Brothers will have to make a one-off change to their congregations database after upgrading.

**Comment by cengizu** [comment]
@ajtruckle 

You mean these labels, right? They need to be updated:
![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/a65768e1-21ec-496d-9b4b-82c26911c801)
Midweek and Weekend.

**Comment by ajtruckle** [comment]
@cengizu 
> You mean these labels, right? 

Yes, but I was meaning this with reference to the **Congregation** window as that would be the place where the settings will be.

One proposal:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/eab5143f-c5db-414d-85da-a4aed56800e4)

**Comment by ajtruckle** [comment]
@cengizu 
Morning! I have made all the needed changes.

## General Settings ##
Legacy settings have been removed and I have adjusted the width of the page:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/58550605-a495-4402-a413-910be81cf2e0)

So all the page widths are now the same on the Settings sheet:

* General
* Email
* Monthly Workbook Data
* Automatic Backup
* Check For Update

## Congregation ##
Now you set the day and time for both meetings:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/9d6d5fd8-e7a1-487e-b497-ed30d72acc23)


## Edit Meeting Times ##
Changed the meeting descriptions on the Edit Meeting Times window for consistency:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/7456a091-2995-4af2-806a-027e8c9dd121)

I am sending you a beta to test.

**Comment by cengizu** [comment]
@ajtruckle 

![Recording-2024-02-27-151814](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/7c2486bd-833f-4388-a5d3-0abff5884101)
Looks good to me 👍
