### ISSUE TITLE
Import / Export Congregation Database Information

### ISSUE THREAD

**Issue by ajtruckle** [ajtruckle/meeting-schedule-assistant-support#5]
**Is your feature request related to a problem? Please describe.**
There is no way to export the Congregation Database. 

**Describe the solution you'd like**
Is it possible to add Export / Import and not only Import?

**Describe alternatives you've considered**
I am aware that the congregation database is stored in a specific XML file. 

**Additional context**
It's good to share the data of the speakers & congregation. Since it took lot of time to add them (if not imported from the PTS application). This feature was originally requested by @fstouma.

**Comment by ajtruckle** [comment]
@fstouma
It is a good idea 💡 and one worthy of consideration. In Public Talks it has the concept of [Synchronization](https://help-pts.publictalksoftware.co.uk/pts-congregations-sync-data.html). To quote the help topic:

> This feature has been implemented to make it easier for Talk Coordinators to transfer their latest details between each other. This is how the feature would work (in theory):
> 
> - Export your congregation data into a INI file
> - Email your INI file to the talk coordinator
> - He synchronizes your INI file into his database
> - He now has your update to date details
> 
> Likewise, a coordinator could email you his latest INI file and you would synchronize it into your database.

Things are somewhat easier in Meeting Schedule Assistant because we don’t have the headache of a Microsoft Access Database. But we can discuss …

**Comment by cengizu** [comment]
That's an important feature. It should be there.

If the database is already in XML, MSA could simply offer user the import/export db option. 

- **Export:** save a copy of the database, prompting user where to save it.
- **Import:** load a database file*, prompting user from where to obtain it.

_** in case a db already exists, will this feature overwrite or append to existing db. Can be prompted to user._

Users then can attach this XML file to emails or copy on USB sticks.

**Comment by ajtruckle** [comment]
@cengizu 
> ** in case a db already exists, will this feature overwrite or append to existing db. Can be prompted to user.
PTS has two modes for import / export of congregation data:

1. Bulk import / export.
    - Exports all congregation data.
    - Imports (or appends) congregation data.
2. Specific import / export.
    - Exports the selected congregation.
    - Imports and merges the selected congregation.

**Comment by ajtruckle** [comment]
@cengizu 
Regarding the exportation of the congregation database:
1. A popup window will display a list of congregations.
2. The user can select one or more congregations for export.
3. After clicking OK, the user will be prompted to provide a filename for the exported XML database.
4. The selected congregations will then be saved to the specified XML data file.

Note:
* The existing serialization code will be utilized. The only change will be filtering the list of congregations before saving.
* Complete congregation information, including all speakers, will be exported.
* The export function could be included in the Congregation database menu, but it should be distinct from the Import menu item, which is meant for importing from Public Talks software.
* An Export button could also be added to the Congregation window, allowing the user to export the currently active congregation to an XML file.

**Comment by cengizu** [comment]
Looks good to me. Let's see it in action

**Comment by ajtruckle** [comment]
@cengizu 
Alright, I'll put something together.

**Comment by ajtruckle** [comment]
@cengizu  @Fahdeya

I have been working on the **Export** functionality. There is now a Export menu item:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/76d7c05a-4fa7-4129-a743-97183fc8f743)

I'll send you a beta to try.

**Comment by ajtruckle** [comment]
@cengizu @Fahdeya

I have been working on the Import functionality. See:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/eaf26571-5205-4f2e-b8d7-4e1e16f09b1e)

New betas on their way to you.

**Comment by cengizu** [comment]
@ajtruckle 

I tried the last beta and import / export works fine. There is no problem when importing, I have imported the same file several times in a row and the congregation names are numbered.
![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/c47ecad5-efdc-4b5d-9e51-2a6e9560ff49)

I also corrupted the XML file I exported and tried it that way. MSA detects the faulty XML file and shows the log records. 
![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/7c8ffc32-b26d-4108-9356-40c1d7899a92)

The process is successful, good job.

**Comment by ajtruckle** [comment]
@cengizu 
Updated help topics for review 👀:

* https://github.com/ajtruckle/meeting-schedule-assistant-support/wiki/msa-revision-history#version-24110---2024-edition-082024
* https://github.com/ajtruckle/meeting-schedule-assistant-support/wiki/msa-congdb-congregation-import
* https://github.com/ajtruckle/meeting-schedule-assistant-support/wiki/msa-congdb-congregation-export
* https://github.com/ajtruckle/meeting-schedule-assistant-support/wiki/msa-database-congregations#import
* https://github.com/ajtruckle/meeting-schedule-assistant-support/wiki/msa-database-congregations#export
