### ISSUE TITLE
Create Congregation Hyperlink on the main Status Bar

### ISSUE THREAD

**Issue by cengizu** [ajtruckle/meeting-schedule-assistant-support#50]
**Is your feature request related to a problem? Please describe.**
The way it currently works, the name of the congregation does not appear in the status bar on the main screen when the program is first installed or if the user does not specify a congregation.

**Describe the solution you'd like**
A hyperlink can be placed in the status bar to encourage users to create a local congregation. Clicking on it will open the Congregations window. When the congregation name is entered and the Local box is checked, the congregation name will be displayed normally in the status bar. This feature allows novice users to discover for themselves what they need to do, or to be gently guided if they have missed it. 

![setCong-status](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/2d16533e-a46a-4225-8aa9-e30ed5e014c4)
Hyperlink may say something like Create congregation, Set congregation, etc.

**Comment by ajtruckle** [comment]
@cengizu 
It is a good idea. In-fact, it is critical that the user:

1. Create an entry for their own congregation.
2. Set it as Local.
3. Indicate meeting days and times.

Since this information is used by the application.

I'll look into it in due course.

**Comment by ajtruckle** [comment]
@cengizu 
The **Meeting Editor** has **drop-down lists** on some of the panes on the status bar. Eg:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/ddca1a5f-0453-4325-b378-0a44b416a20a)

We could replicate the same logic in the main application window and use a [`CMFCLinkCtrl`](https://learn.microsoft.com/en-us/cpp/mfc/reference/cmfclinkctrl-class?view=msvc-170). We already use these controls on the **About** window. And we could add the menu item icon as a bonus. 😊

In-fact, it could be a permanent hyperlink:

- Add Congregation > Display **Add Congregation** window.
- Congregation Name > Display **Edit Congregation** window.

We might have to cater for when the congregation is invalid (ie. deleted from database).

**Comment by ajtruckle** [comment]
@cengizu 
Good news! I now know how to intercept the hyperlink _click_ event to perform my own custom action. See:

[Override `CMFCLinkCtrl `click behaviour](https://stackoverflow.com/questions/78088357/override-cmfclinkctrl-click-behaviour)

**Comment by ajtruckle** [comment]
@cengizu 
I have made a start on this:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/c68e3d60-5a9e-474d-b94d-4d1d50cb2ac5)

* Icon: Same icon as used by the local congregation in the menu.
* Tooltip: **Local Congregation**.
* URL: **Add Congregation** or the **name** of the local congregation.
* Click: Displays the Congregation window.

The URL is refreshed whenever you Add / Edit / Delete a congregation since the link might be affected.

**Comment by ajtruckle** [comment]
Related Q & A:

[Detecting menu item text (and ID)](https://stackoverflow.com/questions/78095881/detecting-menu-item-text-and-id)

**Comment by ajtruckle** [comment]
@cengizu 
I have put a beta on Google Drive for you to test. I have _not_ thoroughly tested it myself.

**Comment by cengizu** [comment]
@ajtruckle 
![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/8377a9f8-4f6e-4d52-ad17-edba105f7e48)
icon is misaligned, link is working when clicked

**Comment by ajtruckle** [comment]
@cengizu 
Good catch! I need to manually move the link control when the window gets resized. Sending you another beta.

**Comment by cengizu** [comment]
@ajtruckle 
![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/b9064829-e13d-47eb-9ef1-57a32ec2a561)
Working well.

💡Two things that could be improved would be: 
- if the status bar link could be updated immediately after the congregation is set, **without the need to restart**. If technically possible.
- if the link icon could be the same as menu Database > Congregations
![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/b2b10394-88cb-496a-87e2-86c4cf79d5bd)

**Comment by ajtruckle** [comment]
@cengizu 
> if the status bar link could be updated immediately after the congregation is set, without the need to restart. If technically possible.

Using the `SetURL` method was supposed to update the hyperlink text (according to the documentation) but it clearly is not working. I eventually found a way around it and will send you a new beta shortly. I added a Q & A on Stackoverflow for my own piece of mind:

[Setting the URL text for a CMFCLinkCtrl](https://stackoverflow.com/questions/78101120/setting-the-url-text-for-a-cmfclinkctrl)

> if the link icon could be the same as menu Database > Congregations

I was originally using that icon. But then it dawned on me that this hyperlink is a short-cut to the **local** congregation. And if you check the GUI the local congregation uses a different image.

**Comment by cengizu** [comment]
@ajtruckle 

Now it looks good with the new icon. Great!
![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/31a6138c-d7ed-4f3d-b6de-ad39cb8410d7)

(_just a cosmetic issue_) is it possible to remove the highligting rectange around the congregation name? It only disappears if I click one of the cells in **Week Overview**

**Comment by ajtruckle** [comment]
@cengizu 
I think I have managed to remove the _focus rectangle_ for you.  I agree that we don't need it on the status bar.

Beta 5 on it's way to you.

**Comment by cengizu** [comment]
@ajtruckle 

Beta 5 works fine 👍

**Comment by ajtruckle** [comment]
@cengizu 
Great! All that's left is making relevant changes to the help documentation.

I suggest:

* Update the image here to include the icon on the status bar:

https://www.publictalksoftware.co.uk/help-msa/

* Update step 2 here:

https://www.publictalksoftware.co.uk/help-msa/msa-quick-start.html
