### ISSUE TITLE
Move / Swap Public Talk Assignment

### ISSUE THREAD

**Issue by ajtruckle** [ajtruckle/meeting-schedule-assistant-support#53]
**Is your feature request related to a problem? Please describe.**
In Public Talks it has a wizard to let you [rearrange](https://www.publictalksoftware.co.uk/help-pts/pts-rearrange-dates.html) a public talk assignment (albeit a local / away talk).

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/ff2194b9-424e-40a9-a6a8-68142fb8ffd3)

**Describe the solution you'd like**
At the moment it is not possible to swap (or move) a public talk assignment in Meeting Schedule Assistant. And I think it would be a useful feature. But, we don't need the complexity of a wizard.

The Meeting Editor already has the ability to swap some assignments for both meetings:

* https://www.publictalksoftware.co.uk/help-msa/mwb-editor-swapassign-references.html
* https://www.publictalksoftware.co.uk/help-msa/mwb-editor-weekend-meeting-swap.html

And, the above includes swapping between schedules by referencing them.

I think we should introduce a similar feature to swap the local (or away) speaker. You would use CTRL + Left mouse button to invoke a similar context menu.

The Local talk menu would offer:

```
Swap
    Date Speaker (Talk#), Congregation
    Date Speaker (Talk#), Congregation
    Date Speaker (Talk#), Congregation
    Date Speaker (Talk#), Congregation
```

The Away talk menu would offer:

```
Move
    Date
    Date
    Date
    Date
    Date
Swap
    Date Speaker (Talk#), Congregation
    Date Speaker (Talk#), Congregation
    Date Speaker (Talk#), Congregation
    Date Speaker (Talk#), Congregation
```

I don't think the local talk needs to support *move*.

**Comment by cengizu** [comment]
@ajtruckle 
Good idea. Need to see it in action though😉

**Comment by ajtruckle** [comment]
@cengizu 
Yes, I think it would be useful for the talk coordinators. But I would like us to agree on the wording for the context menu items. Eg:

> Date Speaker (Talk#), Congregation
> 10/03/2024 Happy Brother (n.1) Arrakis

**Comment by ajtruckle** [comment]
@cengizu 
I made a start on the display of the context menu. I decided to omit the _current meeting_ from the menu. Made no sense to include it. But their are a couple of issues to address / consider.

- Special Events: Some weeks there is no weekend meeting due to a special event. These weeks should not display on the menu.
- Away Talks: Technically, an away talk assignment might need to be moved to a different day on the selected weekend. The Move sub-menu only includes the local congregation meeting dates.
    - So you can move an away talk from one Sunday to another Sunday (or swap).
    - But you can't move an away talk from was Sunday to a Saturday (or vice versa). Unless that date is already in the menu (and thus a swap).

Make sense?

**Comment by ajtruckle** [comment]
@cengizu 
Please give some thought to the way the GUI should look when we are asking the user to confirm a swap between two talk assignments. This will either be:

* A standard message box
* A task dialog

The existing swap feature uses a simple message box:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/a9fa2a29-426a-4901-a0d5-379e61921d79)

But, in this context we will have more information for (source / target):

* Date
* Name
* Congregation
* Talk number

We'll also have to cater for **moving** assignments. But I am concentrating on  **swapping** at the moment.

**Comment by cengizu** [comment]
@ajtruckle 

A task dialog might be better than a simple message box due to complex details this window will display. If the user is well informed, they will adopt such features more quickly and use them more.

**Comment by cengizu** [comment]
@ajtruckle 

An example:
![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/4d630dd9-7e87-4d98-89eb-a922ae415121)

**Comment by ajtruckle** [comment]
@cengizu 
Thanks for the proposal. This will require a custom dialog. I'll look at in in due course. Please provide the BMP for the arrow symbol.

I think I will use the following wording:

> Please confirm that you would like to swap the following home talk assignments:
> Please confirm that you would like to swap the following away talk assignments:
> Buttons: Yes and No.

My original concern still stands for _moving_ a talk assignment, since the target day might not be the normal meeting day, and that date might not be in the menu. So I think _moving_ needs to be give some thought to come up with a simple solution.

**Comment by ajtruckle** [comment]
Linked Q & A:

[Can this code be simplified for adding a structure to a std::map?](https://stackoverflow.com/questions/78112928/can-this-code-be-simplified-for-adding-a-structure-to-a-stdmap)

**Comment by ajtruckle** [comment]
@cengizu 
This is based on your suggestion:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/544ea4c2-9b35-46c5-b73c-5ac98610a9f1)

The edit controls are _read-only_ so the user can't change the text. And I can set the image background as transparent. I just wanted to put something together for you to see.

But, I am wondering if we should have consistency between the icon used on this window and the smaller icon used on the context menu? I admit that I like the brighter colour on the swap menu, but for this window it is logical that the arrows are left / right.

See what you think. 🤔

## Away Talks ##
I have decided that you need to select the away talk you want to swap (so that it is highlighted) _before_ pressing the hotkey:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/a06865c0-a870-42dd-94f5-f4b84f0827e6)

Otherwise, the logic fails because the grid has no focus row for us to extract the talk information from.

**Comment by ajtruckle** [comment]
@cengizu 
I have completed the initial implementation for **swapping** assignments. Sending you beta 6 via Telegram.

**Comment by ajtruckle** [comment]
@cengizu 
* Context menu has a new icon:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/92d77ee6-4a63-480f-8f64-b614aa079c9e)

* Swap window now has a larger icon (complementing the small menu one). And, some of the text has been revised:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/76f5dd5b-c62a-4052-84d4-06afacdb71b9)

Some other minor improvements have been made to the feature. I'll send a beta in due course.

**Comment by cengizu** [comment]
@ajtruckle 
![Recording 2024-03-09 151135](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/71f1f41f-f0b8-45e6-94f2-a1ebae036910)

Works nicely 👍

**Comment by ajtruckle** [comment]
@cengizu 
Thanks for doing the beta testing for **Home Talks**. I look forward to your feedback for swapping **Away Talks** when you have time.

I am sending beta 8 to you via Google Drive. It has been updated so that the **Cancel** button turns into a **Close** button whenever any _swapping_ of assignments has occurred .

**Comment by ajtruckle** [comment]
@cengizu 
Morning! I have now completed implementation for both **Move** and **Swap** and the beta is ready for testing.

* The _context menu_ has a new icon for **Move Assignment**:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/222da29a-bbe3-4a82-9670-2c6cc19d64a1)

* The dates listed for Move Assignment sub-menu will either be:
    * Home Talk: Local Congregation meeting day.
    * Away Talk: Away Congregation meeting day.

* This is the new **Move Assignment** window:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/eb62de9f-7cc4-497f-8043-8b36cbc0640d)

* It is possible to **override** the time for the _moved_ talk assignment.

* The **Swap Assignments** window has been updated:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/9c61f4fc-539f-4c25-9494-74cd21236075)

* The **Cancel** button will change to a **Close** button whenever you perform a _move_ or _swap_ for _any assignment_ on the **Weekend Meeting** window. This is because the operation is modifying two different weeks in the meeting editor.

* Fixed an issue with **deleting** an away talk. The row was staying visible in the away talks list.

Beta 9 is on its way to you! 😊

**Comment by ajtruckle** [comment]
@cengizu 
I have made some minor changes to the help topic. And added Help buttons to the new windows.

[Moving and Swapping Assignments.pdf](https://github.com/ajtruckle/meeting-schedule-assistant-support/files/14575598/Moving.and.Swapping.Assignments.pdf)

**Comment by cengizu** [comment]
@ajtruckle 

All looks good to me. it works. Great job!

**Comment by ajtruckle** [comment]
@cengizu 
I am sending you beta 11 which has some other refinements to the GUI. Both the Meeting Editor and Weekend Meeting Editor now use a hamburger icon  in several locations. Example:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/dc4480e6-5284-4662-8683-38b8c3bb998a)

This makes it clearer to the user that they have the facility to move (or swap) assignments. Just click the hamburger icon to display the context menu. Using CTRL + Left-click is now obsolete.
