### ISSUE TITLE
Meeting day change

### ISSUE THREAD

**Issue by Jonbasso** [ajtruckle/meeting-schedule-assistant-support#54]
After the last update my meeting day appears on Thursdays. however, my meeting is on Wednesdays. I can't find where to fix it. How can i do this?

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Version [24.4.0]

**Comment by ajtruckle** [comment]
@Jonbasso 
Sorry for the confusion. This setting was moved. To update:

1. **Databases** menu
2. **Congregation** sub menu
3. **Edit** sub menu
4. Locate your congregation and click menu item
5. Adjust the midweek meeting day on this window. 

Version 24.5.0 (beta) simplifies the process of managing your local congregation (see #50).

Help: https://www.publictalksoftware.co.uk/help-msa/msa-congdb-manage-congregations.html#Meeting_Day_and_Time

**Comment by Jonbasso** [comment]
Thank you, brother! It's perfect now!
Em Mar 7, 2024, 10:11 AM -0300, ajtruckle ***@***.***> escreveu:
