### ISSUE TITLE
Improving Check for Update 

### ISSUE THREAD

**Issue by ajtruckle** [ajtruckle/meeting-schedule-assistant-support#58]
**Is your feature request related to a problem? Please describe.**
The **Check for Update** feature is very handy. But it is not possible to _re-download the latest version_ with this approach:

![telegram-cloud-document-4-6028316908690870664](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/64728ec0-1111-4ed3-adee-3a32a95cacbf)

**Describe the solution you'd like**
Turn the message box into a task dialog that displays the same message, but include a custom button to let the user opt to download and re-install.

**Additional context**
There are several reasons for needing to re-download the latest version:

- You are using a beta version and now need to upgrade to the official release.
- You downloaded the official release and the translations were not complete. But now you know that the translations are updated and need to re-install.
- A bug was brought to my attention after immediate release and I decided to silently update the existing installer on the website.

**Comment by ajtruckle** [comment]
I have now made some changes for this!

- Step 1
The following **task dialog** is now displayed instead of the message box:

![image_2024-03-17_09-08-55](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/b41d5b75-65c0-4790-b8d9-4e0ab9be35c5)

- Step 2
Clicking **Download and re-install anyway** will display the familiar **Check for Update** window:

![image_2024-03-17_09-09-21](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/201bdb31-b9ba-43d8-af78-88222c5ccc60)

**Comment by cengizu** [comment]
@ajtruckle 

A nice addition, and it works fine. 
![Recording 2024-03-18 123521](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/7a70e93e-81bb-4eaa-b4f0-b15b0c10cb9b)
