### ISSUE TITLE
Add hamburger button to the "Home/Away Speaker — Add to list of speaker talks" feature

### ISSUE THREAD

**Issue by ajtruckle** [ajtruckle/meeting-schedule-assistant-support#62]
**Is your feature request related to a problem? Please describe.**
Currently, you can press the CTRL key and click the drop-down arrow to bring up the context menu; this is not an issue per se.

![Idea1](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/fbbcaa3e-b4ef-43ba-9d82-e06a040630f6)

But this feature is not immediately obvious to the user.

**Describe the solution you'd like**
We've recently added a **hamburger** button to trigger the Swap Assignment feature in both editors for consistency. I propose we narrow the drop-down list width on this window and incorporate a hamburger button. Clicking the hamburger would reveal the context menu, making it more intuitive.

**Comment by ajtruckle** [comment]
I have now added the hamburger button to the **Away Talk** window:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/3c814867-3f37-4065-aa13-cd0ad51999fa)

But, I realised that I could also do the same thing for the _Home Talk_ on the **Weekend Meeting** window:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/ea878c2e-2026-4195-90ed-2597d198ce8b)

There are some issues that I need to address though:

- When the selected talk is _already_ one of his outlines.
- When the Congregation and Speaker roles have _not been selected_.

In these situations we should disable the context menu item. This would keep the button free for any further actions that may be implemented in the future.

**Comment by ajtruckle** [comment]
> In these situations we should disable the context menu item. This would keep the button free for any further actions that may be implemented in the future.

These scenarios have now been catered for. E.g.:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/a82093db-de60-4694-bbf2-a11ac52ecd92)

**Comment by cengizu** [comment]
@ajtruckle 

Yes, the Hamburger button is ideal for all similar situations. It is both easy to recognize and practical.

**Comment by ajtruckle** [comment]
@cengizu 
Very true!

### Help Text ###

Click on the **hamburger** symbol to display this context menu. If the talk number is not yet included in the speakers’ list of assigned talks, the menu item **Add to list of assigned talks** will be available. You will be asked to confirm whether you want to add the talk number to the selected speaker. If you answer Yes, it will automatically add this talk number to their list of talks. This saves you from having to go through the Congregations Database menu navigation to do it.

### Revision History ###

*   Weekend Meeting Editor > **Local Talk** > _Add talk to list of assigned talks_ > now uses Hamburger button. (GitHub _discussion_)
*   Weekend Meeting Editor > **Away Talk** > _Add talk to list of assigned talks_ > now uses Hamburger button. (GitHub _discussion_)
