### ISSUE TITLE
Indicating if the selected talk has multimedia

### ISSUE THREAD

**Issue by ajtruckle** [ajtruckle/meeting-schedule-assistant-support#63]
**Is your feature request related to a problem? Please describe.**
In Public Talks it indicates if the selected talk has digital media:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/96861c75-11b2-411e-aa41-1b77f6ee70fd)

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/3381b393-ca9e-4d0e-a023-43ddffbc41b4)

**Describe the solution you'd like**
Implement the same feature in Meeting Schedule Assistant.

**Comment by ajtruckle** [comment]
I have now implemented this feature.

* Home Talk

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/250cc61e-dfa4-4e3e-91d1-8db1e9d7839e)

* Away Talk

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/a01e47cd-fc47-487e-8683-bdac126b57bb)

**Comment by cengizu** [comment]
@ajtruckle 

it works nicely. 
![Recording 2024-04-15 160914](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/d67f45fa-ee26-49da-8c1f-4893c0fb578f)

**Comment by ajtruckle** [comment]
@cengizu 

Great!

### Revision Text ###

*   Talk Outline > Indicate if it has multimedia. (GitHub _discussion_)

I don't think we need to specifically document this anywhere else. Agreed?

**Comment by cengizu** [comment]
@ajtruckle 

if you wish, you may add a simple text in the help text, under **Speaker Notes and Images** section, briefly mentioning that some talks have "has multimedia" label which is set by the Organization (https://www.publictalksoftware.co.uk/help-msa/mwb-editor-weekend-meeting.html).

**Comment by ajtruckle** [comment]
@cengizu 

Good idea! Implemented. 👍
