### ISSUE TITLE
Importing CSV data for the Midweek Meeting

### ISSUE THREAD

**Issue by ajtruckle** [ajtruckle/meeting-schedule-assistant-support#64]
**Is your feature request related to a problem? Please describe.**
Some scheduling applications have the ability to export assignment information in CSV format. Can the [Import from Database History](https://www.publictalksoftware.co.uk/help-msa/mwb-editor-import-history.html) feature be extended to support importing of CSV data files?

**Describe the solution you'd like**
It would be great if the Meeting Editor could populate the schedule (assignees) from the selected CSV files.

**Describe alternatives you've considered**
At the moment, we have a need to use another scheduling application, I am manually re-inputting the same assignees into MSA. Importing would simplify the process tremendously.

**Comment by ajtruckle** [comment]
I have been working on this feature:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/c46265c6-a664-4512-93c1-0bdeb2f557dc)

> [!IMPORTANT]  
> The text file must be **UTF8 + BOM** encoded.

### Supported Delimiters ###

* Comma
* Semi-colon

### Column Headings ###

* Date
* Person
* PartType
* Assignment
* School

### PartType ###
| Part Type          |
|--------------------|
| Chairman           |
| AuxiliaryCounselor |
| OpeningPrayer      |
| ClosingPrayer      |
| TreasuresTalk      |
| Gems               |
| BibleReading       |
| Apply1             |
| Apply2             |
| Apply3             |
| Apply4             |
| Apply1Assistant    |
| Apply2Assistant    |
| Apply3Assistant    |
| Apply4Assistant    |
| Living1            |
| Living2            |
| Living3            |
| CBS                |
| CBSReader          |
| Host          |
| CoHost          |
| ZoomAttendant          |


### School ###
| Audience | Value |
|-----------|---|
| Main Hall | 1 |
| Class 1   | 2 |
| Class 2   | 3 |

<hr>

### Sample Data  [^footnote]

The data would be comma (or semi-colon) delimited:
| Date       | Person     | PartType           | Assignment                                      | School |
|------------|------------|--------------------|-------------------------------------------------|--------|
| 2024/05/27 | Brother 1  | Chairman           | Chairman                                        | 1      |
| 2024/05/27 | Brother 2  | OpeningPrayer      | Opening Prayer                                  | 1      |
| 2024/05/27 | Brother 3  | ClosingPrayer      | Closing Prayer                                  | 1      |
| 2024/05/27 | Brother 4  | TreasuresTalk      | 1. Benefit Fully From Divine Education          | 1      |
| 2024/05/27 | Brother 5  | Gems               | 2. Spiritual Gems                               | 1      |
| 2024/05/27 | Brother 6  | AuxiliaryCounselor | Auxiliary Counselor                             | 2      |
| 2024/05/27 | Student 1  | BibleReading       | 3. Bible Reading                                | 2      |
| 2024/05/27 | Student 2  | BibleReading       | 3. Bible Reading                                | 1      |
| 2024/05/27 | Student 3  | Apply1             | 4. Starting a Conversation                      | 2      |
| 2024/05/27 | Student 4  | Apply1             | 4. Starting a Conversation                      | 1      |
| 2024/05/27 | Student 5  | Apply2             | 5. Following Up                                 | 2      |
| 2024/05/27 | Student 6  | Apply2             | 5. Following Up                                 | 1      |
| 2024/05/27 | Student 7  | Apply3             | 6. Talk                                         | 2      |
| 2024/05/27 | Student 8  | Apply3             | 6. Talk                                         | 1      |
| 2024/05/27 | Student 9  | Apply1Assistant    | Assistant: 4. Starting a Conversation           | 2      |
| 2024/05/27 | Student 10 | Apply1Assistant    | Assistant: 4. Starting a Conversation           | 1      |
| 2024/05/27 | Student 11 | Apply2Assistant    | Assistant: 5. Following Up                      | 2      |
| 2024/05/27 | Student 12 | Apply2Assistant    | Assistant: 5. Following Up                      | 1      |
| 2024/05/27 | Brother 7  | Living1            | 7. Make Wise Decisions About Work and Education | 1      |
| 2024/05/27 | Brother 8  | CBS                | 8. Congregation Bible Study                     | 1      |
| 2024/05/27 | Brother 9  | CBSReader          | 8. CBS Reader                                   | 1      |

[^footnote]: The Assignment column is not actually imported to MSA. It is assumed that you have already prepared the schedule by downloading the monthly data first.

**Comment by ajtruckle** [comment]
We have been working on an additional **generic importer** for CSV. It uses the concept of **field mapping**.

Progress so far:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/c9129386-fca1-4255-a54f-f956daa01a8d)

**Comment by ajtruckle** [comment]
@cengizu @stecchio66

Some aspects of the field mappings concept need to be discussed. 

- Away Talks
- Students
- Teaching

### Away Talks
MSA supports an unlimited number of away talks. So it would be tricky to import using this system. A The **CSV-Weekend Meeting** importer could be implemented that uses multiple rows. 

### Students 
The **CSV-Midweek Meeting** importer is ideal because it uses _multiple rows_ per meeting. So we don't have an inordinate number of columns in the file.

We potentially have 9 assignments, per school, making it 27 additional columns. I just don't like it.

### Teaching
Most congregations only have the Teaching role in the main hall and no other classes. In which case we could support it. But MSA technically supports a Teaching assignment in all classes.

I am open to suggestions, if you have any. 💡🤔

**Comment by ajtruckle** [comment]
- **Links to** drop lists have been updated with some changes.
- We are currently working on importing the CSV data.

To facilitate the import process, I added extra properties to the JSON mapping file. Example:

```json
{
  "FieldMapping": [
    {
      "Field": "Date",
      "FieldIndex": 0,
      "IncludeField": true,
      "Meeting": "Weekend",
      "MeetingIndex": 1,
      "LinksTo": "Date",
      "LinksToIndex": 0
    },
    {
      "Field": "Congregation",
      "FieldIndex": 1,
      "IncludeField": true,
      "Meeting": "Weekend",
      "MeetingIndex": 1,
      "LinksTo": "Congregation",
      "LinksToIndex": 7
    },
    {
      "Field": "PublicSpeaker",
      "FieldIndex": 2,
      "IncludeField": true,
      "Meeting": "Weekend",
      "MeetingIndex": 1,
      "LinksTo": "Speaker",
      "LinksToIndex": 8
    },
    {
      "Field": "OutlineNumber",
      "FieldIndex": 3,
      "IncludeField": true,
      "Meeting": "Weekend",
      "MeetingIndex": 1,
      "LinksTo": "Talk Number",
      "LinksToIndex": 9
    },
    {
      "Field": "OutlineName",
      "FieldIndex": 4,
      "IncludeField": false
    },
    {
      "Field": "Song",
      "FieldIndex": 5,
      "IncludeField": true,
      "Meeting": "Weekend",
      "MeetingIndex": 1,
      "LinksTo": "Song",
      "LinksToIndex": 6
    },
    {
      "Field": "Confirmed",
      "FieldIndex": 6,
      "IncludeField": false
    },
    {
      "Field": "Hospitality",
      "FieldIndex": 7,
      "IncludeField": false
    },
    {
      "Field": "Notes",
      "FieldIndex": 8,
      "IncludeField": false
    }
  ]
}
```

The importing functionality is now operational, but I still need to incorporate validation checks.

Note:

- One of the fields _must link to_ the **Date** item in the drop-list.
- The file _must_ be **UTF8+BOM** encoded.
- The _first line must_ be the **headings** row.
- Records should be sorted in date ascending order.

**Comment by cengizu** [comment]
![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/ee1b18c2-d6ba-417d-9da2-110ec13ef6b1)

Just a suggestion for the ease of use:

When **CSV** is selected, the user can be better guided if some buttons other than Detect (Check, Uncheck All and Import) are disabled.

**Comment by ajtruckle** [comment]
@cengizu 

> When CSV is selected, the user can be better guided if some buttons other than Detect (Check, Uncheck All and Import) are disabled.

Good idea. Those buttons are now set to disabled when you select the CSV radio option:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/2b024180-059f-41b6-b26d-6a2eac35141c)

Then, the **Check All** / **Uncheck All** buttons get enabled after you have _detected_ the fields:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/951b9096-6d38-495b-913e-e6f726bcb618)

But, the **Import** button is only enabled when you have a valid _field mapping_ configuration:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/812bb829-bb2f-48d2-b00f-a7f9746f5af8)

🤔 The **Date** Links to is mandatory, so I need to cater for that.

<hr>

### Links To ###

I have added these items to the **Weekend Links To** list:

* Middle song number
* Closing song number

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/e4e7c1bd-f41b-4f2c-91bd-52ac8818aa0b)

🤔 Should the Open Prayer / Close Prayer assignments be together in the list?

<hr>

### Validation ###

A certain amount of validation is now being performed for each field:

* Does the **publisher** exist in the database?
* Does the **congregation** exist in the database?
* Is the **song number** valid?
* Is the **talk number** valid?

🤔 It is _not_ an exhaustive validation at the moment. For example, it will not confirm:

- If the publisher has the given assignment in the database.
- If the speaker exists for the given congregation in the database.
- If the talk number is assigned to the given speaker.

New betas are on their way to you for testing.

**Comment by ajtruckle** [comment]
@cengizu 

Not sure what is going on my my commits. They keep closing the ticket!

**Comment by cengizu** [comment]
@ajtruckle 
![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/6a5b60e7-2920-43bb-a130-e29025e58fc3)

**Comment by ajtruckle** [comment]
@cengizu 

I had a bit of a mishap while trying to sort things out—I accidentally lost all my code changes! 😅 But, thankfully, I managed to recover the code. And I opted to switch back to the _stable_ release of **GitHub Desktop** instead of using the _beta_ version. It seems to be working better now.

### Validation ###

> It is not an exhaustive validation at the moment. For example, it will not confirm:
>
> - If the speaker exists for the given congregation in the database.

It became apparent that the fields in the CSV file I have been testing with (an export from another application) have the fields in a specific order:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/21731490-9f57-4711-9f23-fec1875075d8)

This works to our advantage because they are in the right order of priority:

1. Date
2. Congregation
3. PublicSpeaker
4. OutlineNumber

This means that we can do some extra validation (as long as the user selects the relevant fields!):

- If the **speaker** exists for the given **congregation** in the database.

**Comment by ajtruckle** [comment]
@cengizu 

Just corrected another issue. You could _double-click_ the **Field** cell to into _edit mode_. I have now stopped this behaviour.

New betas on their way to you.

**Comment by ajtruckle** [comment]
@cengizu 

The GUI has been simplified:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/071413d0-2ef0-4d17-b036-d589c440641d)

The delimiter setting has been removed because we don't need it anymore. We are now using the [`CkCsvW`](https://www.chilkatsoft.com/refdoc/csCsvRef.html) CSV parser and it automatically detects the comma or semi-colon delimiter for us. 😊

**Comment by ajtruckle** [comment]
@cengizu 

Moved the controls around:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/f657cadf-9810-4613-b0c7-bbefeaafe9d4)

😊

**Comment by cengizu** [comment]
@ajtruckle 

This looks good, you've created a progression from left to right. It is more intuitive for all kinds of users.
