### ISSUE TITLE
Add support for the Scintilla control 

### ISSUE THREAD

**Issue by ajtruckle** [ajtruckle/meeting-schedule-assistant-support#65]
**Is your feature request related to a problem? Please describe.**
Not a problem as such. But MSA has the ability to show text in a dialog.

For example:

* Displaying Error Logs
* Script Builder window
* Speaker Notes & Images
* Possibly viewing underlaying XML / XSL / CSS data

**Describe the solution you'd like**
Add support for the Scintilla control which sponsors syntax highlighting.

**Comment by ajtruckle** [comment]
I am going to use the wrapper class CScintillaCtrl:

https://www.naughter.com/scintilla.html

There are two underlying controls:

- Scintilla
https://www.scintilla.org/

- Lexilla
https://www.scintilla.org/Lexilla.html

Lexilla is also available here on GitHub:

https://github.com/ScintillaOrg/lexilla

**Comment by ajtruckle** [comment]
Linking here for my own reference:

https://github.com/ScintillaOrg/lexilla/issues/243

**Comment by ajtruckle** [comment]
@cengizu

Progress!

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/a49f5a0a-b16d-45b8-9e44-e37245671230)

**Comment by ajtruckle** [comment]
Linking here for my own reference:

https://sourceforge.net/p/scintilla/scite/ci/default/tree/src/css.properties
https://sourceforge.net/p/scintilla/scite/ci/default/tree/src/html.properties
https://sourceforge.net/p/scintilla/scite/ci/default/tree/src/json.properties

**Comment by cengizu** [comment]
Looks great!

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/85148eeb-43cd-4b60-8ac9-e5f8986ea188)

**Comment by ajtruckle** [comment]
@cengizu 

Glad you like it! And now I have been making changes to the Script Builder window:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/57038f7a-6d68-4166-8c80-e76864591095)

**Comment by ajtruckle** [comment]
@cengizu 

I am sending you a new beta:

1. Improved file reading performance. Most noticeable when reading XSL templates.
2. Improved Script Builder window (as previously described).
3. Added all the keywords for CSS / HTML / XML. This affects the syntax highlighting.
4. Updated several translations.

**Comment by ajtruckle** [comment]
@cengizu 

Implemented Edit menu, with the following features:

- Undo
- Redo
- Cut
- Copy
- Paste
- Select All

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/86b2ddcc-a766-4e2e-9486-c42c29a2f39e)

The clipboard features are also available on the right-click context menu.

**Comment by ajtruckle** [comment]
@cengizu 

Updated **View** menu:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/208ce2ae-45d9-4f57-b8a6-7a4a928487bc)

Added:

- Toggle current fold
- Toggle all folds
- Full Screen

**Comment by ajtruckle** [comment]
@cengizu 

Added support for **Word Wrap** to the View menu:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/62964091-94aa-48a7-9821-74feedcfe949)

There are several ways to configure [Line Wrapping](https://www.scintilla.org/ScintillaDoc.html#LineWrapping) in Scintilla, and I opted to use the **Word** mode (as opposed to **Character** or **Whitespace**). It is also possible to show little arrows to indicate the line is word-wrapped, but I have not activated this feature.

**Comment by ajtruckle** [comment]
@cengizu 

I have added **searching** capabilities to the editor.

### Find ###
![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/b0a3e107-891a-4801-bdb4-2cae1c40c2a5)

### Replace ###
![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/e77abd16-ec25-4939-b747-3734402ac13d)

### Menu ###
![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/ec7e645c-0298-4c65-91af-6aef8661feda)

**Comment by ajtruckle** [comment]
@stecchio66
> Displaying CSS does not work in custom styles. Example: Publishers Assignments Report

All template (XSL) files need to specify the HTML namespace, like this:

```xml
xmlns="http://www.w3.org/1999/xhtml"
```

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/238f1770-601c-41d8-999d-6144490817ce)

Otherwise the `link` elements won't be found. I have now corrected all default templates but you will need to edit your own for this feature to work correctly.

###  Database Report Viewer
Please be aware that the _Custom--Publishers Assignments Report_ template is technically obsolete. It was replaced by the the _PublisherDB--Publishers Assignments Report_ template. This latter template can be accessed from the Publisher Database report viewer.

You can continue to duplicate the template with the Custom prefix if  you want it available in the Meeting Editor, but it will never get updated by the installer. So please be aware of this.

I have taken the opportunity to add support for Scintilla to the Database Report Viewer. So selecting CSS / XSL are now behaving in a consistent manner as the other editors.

### Scintilla Editor
There seemed to be a regression with the scintilla editor and it was not detecting when the file had been modified. So it never offered to save your changes. This confused me at first because it used to work. I think I have now resolved it and got it working again.

Also, the editor is supposed to leave the file in a read only state when it is displayed (if the read only flag is set). I have re-instated this behaviour. So if you want to edit an default template you will need to perform a **File Save As** first.

At the moment it is not clear to the user that the file might be read only, other than the fact that they can't edit it. WE could consider adding a status bar. For example:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/bd880381-1760-4c8e-b72c-f62b82133600)

Perhaps such a status bar could indicate if the file is read only. Or we could add it to the file name on the title bar or some other way.

New betas on their way to you.

**Comment by ajtruckle** [comment]
@stecchio66 @cengizu 

> At the moment it is not clear to the user that the file might be read only, other than the fact that they can't edit it.

In NotePad++ It handles this issue like this:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/7babfb64-36b0-4a6d-a08a-c9865770916c)

Fortunately, Notepad++ has their [translations](https://github.com/notepad-plus-plus/notepad-plus-plus/tree/master/PowerEditor/installer/nativeLang) available online! So I have collated the ones we need:

| Language | Translation                                    | Translation                           |
|----------|------------------------------------------------|---------------------------------------|
| eng      | Clear Read-Only Flag                           | Set Read-Only                         |
| csy      | Zrušit příznak Pouze pro čtení                 | Nastavit p&amp;říznak Pouze pro čtení |
| dan      | Fjern skrivebeskyttelse                        | Sæt skrivebeskyttelse                 |
| deu      | Schreibschutz-Attribut löschen                 | Schreibschutz                         |
| ell      | Καθαρισμός μόνο για ανάγνωση μεταβητής flag    | Ορισμός Μόνο για Ανάγνωση             |
| esp      | Desactivar solo lectura                        | Solo lectura                          |
| fin      | Poista kirjoitussuojaus                        | Aseta kirjoitussuojaus                |
| fra      | Enlever l'attribut de lecture seule du fichier | Lecture seule pour le document actuel |
| hun      | Írásvédett attribútum törlése                  | Írásvédett                            |
| ita      | Rimuovi attributo di sola lettura del file     | Sessione documento in sola lettura    |
| jpn      | ファイルの読み取り専用を解除                   | 読み取り専用モード(S)                 |
| nld      | Alleen-lezen opheffen                          | Instellen als alleen-lezen            |
| plk      | Usuń atrybut tylko do odczytu z pliku          | Zablokuj edycję                       |
| ptb      | Desmarcar como somente leitura                 | Definir como somente leitura          |
| ptg      | Limpar o símbolo só de leitura do ficheiro     | Definir como só de leitura            |
| rom      | Eliminare stare doar citire                    | Setare stare doar citire              |
| rus      | Снять "Только Чтение"                          | "Только Чтение" файла                 |
| slv      | Počisti zastavico Samo za branje               | Nastavi samo za branje                |
| sqi      | Pastro flamurin vetëm-lexo                     | Vendos vetëm-lexo                     |
| sve      | Inaktivera skrivskydd                          | Aktivera skrivskydd                   |
| trk      | Salt Okunur İşaretini Kaldır                   | Salt Okunur Yap                       |
| ukr      | Прибрати атрибут «Лише читання»                | Лише читання                          |

I propose implementing the same functionality. This way, it becomes easier for the user:

1. View the read-only template.
2. Save as a new template.
3. Clear the read-only flag.

**Comment by ajtruckle** [comment]
@stecchio66 @cengizu 
Whilst the Set / Clear can still be implemented. The simplest solution was staring me in the face. We simply set the editor and editable whenever you save the file. Job done.

**Comment by ajtruckle** [comment]
@stecchio66 @cengizu 
Whilst I have ideas for new features for the Script Editor, and still have the help topic to write, are we in agreement that we can close the current ticket?
