### ISSUE TITLE
Can we have a field that shows the category of the public talks?

### ISSUE THREAD

**Issue by Fahdeya** [ajtruckle/meeting-schedule-assistant-support#66]
Doing this will allow the public talks coordinator to select according to category

Thank you

**Comment by ajtruckle** [comment]
@Fahdeya 

Thanks for the suggestion. 💡 This is like the feature in the PTS application:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/ce01f3b0-1244-4658-a082-47942d946879)

**Comment by ajtruckle** [comment]
@Fahdeya Has the S-99 been updated recently to indicate the categories for the current set of outlines? Or, are there still some unclassified outlines?

**Comment by ajtruckle** [comment]
@Fahdeya I have managed to compare my current database (from PTS) with the S-99a-E 2/24. So I now have a complete list of categories for talk outlines 1 to 194. 😊👍 I now need to think about the best way to implement this feature in MSA.

**Comment by ajtruckle** [comment]
@Fahdeya Thanks for the information you sent me privately.

So, this is what we can implement so far:

- Add a talk categories snippet to each talks database. I have the existing category descriptions from PTS but there will be some languages that I will need help with by the brothers.
- Update the talk databases to have a category attribute. The good news is that this data will be the same for all databases.
- Update the Public Talks Database Manager window to display the category in a read-only edit control.
- Possibly update the Submit Update window to allow you to change the category the talk is associated with.

We would have to agree which existing reports need to be updated to include the category. And, I will most likely have to prepare an equivalent S-99a report.

But, beyond the above, how do you envisage using the category information? You mentioned:

> Doing this will allow the public talks coordinator to select according to category

I don't think that even PTS allows you to select a talk based on category. So, what did you have in mind?

**Comment by Fahdeya** [comment]
Hi,
Thank you for your hard work. I like the idea to have the coordinator select the talk according to category, but, also if he wants he can see them according to number
Thank you

**Comment by ajtruckle** [comment]
@Fahdeya 
> I like the idea to have the coordinator select the talk according to category, but, also if he wants he can see them according to number

This is the current GUI:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/b063e2e9-05b9-4eb5-a567-0365ec860308)

One possible solution is to update the hamburger context menu:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/e21ed0da-600b-41af-b16f-589027c9bf54)

It could have a Filter with a check-list of categories. But this is just one idea.

**Comment by Fahdeya** [comment]
I like to mention one thing, when we receive a new public talk, it will not be included in S-99 directly. so, we have to have the possibility to have a talk that is not under any category.

**Comment by ajtruckle** [comment]
@Fahdeya 
> I like to mention one thing, when we receive a new public talk, it will not be included in S-99 directly. so, we have to have the possibility to have a talk that is not under any category.

I was thinking about that. At this point in time the talk databases are read-only. So no one is allowed to add new talks into it themselves. This makes it so much easier for maintenance. But I agree that we might need a generic category for some outlines in the interim.

```xml
<PublicTalkCategories>
	<PublicTalkCategory id="BG">Bible/God</PublicTalkCategory>
	<PublicTalkCategory id="SQ">Christian Standards/Qualities</PublicTalkCategory>
	<PublicTalkCategory id="EM">Evangelizing/Ministry</PublicTalkCategory>
	<PublicTalkCategory id="FS">Faith/Spirituality</PublicTalkCategory>
	<PublicTalkCategory id="FY">Family/Youth</PublicTalkCategory>
	<PublicTalkCategory id="KP">Kingdom/Paradise</PublicTalkCategory>
	<PublicTalkCategory id="LJ">Last Days/Gods Judgements</PublicTalkCategory>
	<PublicTalkCategory id="NS">Not Specified</PublicTalkCategory>
	<PublicTalkCategory id="RW">Religion/Worship</PublicTalkCategory>
	<PublicTalkCategory id="TP">Trials/Problems</PublicTalkCategory>
	<PublicTalkCategory id="WD">World, No part of</PublicTalkCategory>
</PublicTalkCategories>
```

The `id` values match the original ones used in PTS and these would stay the same fr all talk databases. Only the descriptions would change. And, we have a `NS` category in the list.

The actual talk categories (based on the S-99a 2/24) will be:

```xml
TalkNo="1" CategoryId="FS"    
TalkNo="2" CategoryId="LJ"    
TalkNo="3" CategoryId="RW"    
TalkNo="4" CategoryId="BG"    
TalkNo="5" CategoryId="FY"    
TalkNo="6" CategoryId="LJ"    
TalkNo="7" CategoryId="SQ"    
TalkNo="8" CategoryId="RW"    
TalkNo="9" CategoryId="FS"    
TalkNo="10" CategoryId="SQ"    
TalkNo="11" CategoryId="WD"    
TalkNo="12" CategoryId="SQ"    
TalkNo="13" CategoryId="FY"    
TalkNo="14" CategoryId="SQ"    
TalkNo="15" CategoryId="SQ"    
TalkNo="16" CategoryId="FS"    
TalkNo="17" CategoryId="EM"    
TalkNo="18" CategoryId="FS"    
TalkNo="19" CategoryId="KP"    
TalkNo="20" CategoryId="LJ"    
TalkNo="21" CategoryId="KP"    
TalkNo="22" CategoryId="FS"    
TalkNo="23" CategoryId="KP"    
TalkNo="24" CategoryId="KP"    
TalkNo="25" CategoryId="WD"    
TalkNo="26" CategoryId="BG"    
TalkNo="27" CategoryId="FY"    
TalkNo="28" CategoryId="FY"    
TalkNo="29" CategoryId="FY"    
TalkNo="30" CategoryId="FY"    
TalkNo="31" CategoryId="FS"    
TalkNo="32" CategoryId="TP"    
TalkNo="33" CategoryId="WD"    
TalkNo="34" CategoryId="LJ"    
TalkNo="35" CategoryId="KP"    
TalkNo="36" CategoryId="RW"    
TalkNo="37" CategoryId="BG"    
TalkNo="38" CategoryId="LJ"    
TalkNo="39" CategoryId="WD"    
TalkNo="40" CategoryId="LJ"    
TalkNo="41" CategoryId="LJ"    
TalkNo="42" CategoryId="SQ"    
TalkNo="43" CategoryId="RW"    
TalkNo="44" CategoryId="FS"    
TalkNo="45" CategoryId="RW"    
TalkNo="46" CategoryId="FS"    
TalkNo="47" CategoryId="KP"    
TalkNo="48" CategoryId="SQ"    
TalkNo="49" CategoryId="KP"    
TalkNo="50" CategoryId="TP"    
TalkNo="51" CategoryId="WD"    
TalkNo="52" CategoryId="RW"    
TalkNo="53" CategoryId="WD"    
TalkNo="54" CategoryId="BG"    
TalkNo="55" CategoryId="RW"    
TalkNo="56" CategoryId="RW"    
TalkNo="57" CategoryId="TP"    
TalkNo="58" CategoryId="RW"    
TalkNo="59" CategoryId="WD"    
TalkNo="60" CategoryId="FS"    
TalkNo="61" CategoryId="KP"    
TalkNo="62" CategoryId="KP"    
TalkNo="63" CategoryId="EM"    
TalkNo="64" CategoryId="WD"    
TalkNo="65" CategoryId="TP"    
TalkNo="66" CategoryId="EM"    
TalkNo="67" CategoryId="FS"    
TalkNo="68" CategoryId="SQ"    
TalkNo="69" CategoryId="SQ"    
TalkNo="70" CategoryId="BG"    
TalkNo="71" CategoryId="FS"    
TalkNo="72" CategoryId="SQ"    
TalkNo="73" CategoryId="TP"    
TalkNo="74" CategoryId="FS"    
TalkNo="75" CategoryId="SQ"    
TalkNo="76" CategoryId="BG"    
TalkNo="77" CategoryId="SQ"    
TalkNo="78" CategoryId="SQ"    
TalkNo="79" CategoryId="WD"    
TalkNo="80" CategoryId="BG"    
TalkNo="81" CategoryId="EM"    
TalkNo="82" CategoryId="RW"    
TalkNo="83" CategoryId="RW"    
TalkNo="84" CategoryId="LJ"    
TalkNo="85" CategoryId="KP"    
TalkNo="86" CategoryId="RW"    
TalkNo="87" CategoryId="FS"    
TalkNo="88" CategoryId="BG"    
TalkNo="89" CategoryId="RW"    
TalkNo="90" CategoryId="KP"    
TalkNo="91" CategoryId="KP"    
TalkNo="92" CategoryId="RW"    
TalkNo="93" CategoryId="TP"    
TalkNo="94" CategoryId="RW"    
TalkNo="95" CategoryId="RW"    
TalkNo="96" CategoryId="RW"    
TalkNo="97" CategoryId="WD"    
TalkNo="98" CategoryId="LJ"    
TalkNo="99" CategoryId="BG"    
TalkNo="100" CategoryId="SQ"    
TalkNo="101" CategoryId="BG"    
TalkNo="102" CategoryId="LJ"    
TalkNo="103" CategoryId="SQ"    
TalkNo="104" CategoryId="FY"    
TalkNo="105" CategoryId="TP"    
TalkNo="106" CategoryId="LJ"    
TalkNo="107" CategoryId="WD"    
TalkNo="108" CategoryId="TP"    
TalkNo="109" CategoryId="KP"    
TalkNo="110" CategoryId="FY"    
TalkNo="111" CategoryId="KP"    
TalkNo="112" CategoryId="SQ"    
TalkNo="113" CategoryId="FY"    
TalkNo="114" CategoryId="BG"    
TalkNo="115" CategoryId="WD"    
TalkNo="116" CategoryId="WD"    
TalkNo="117" CategoryId="TP"    
TalkNo="118" CategoryId="FY"    
TalkNo="119" CategoryId="WD"    
TalkNo="120" CategoryId="KP"    
TalkNo="121" CategoryId="LJ"    
TalkNo="122" CategoryId="KP"    
TalkNo="123" CategoryId="WD"    
TalkNo="124" CategoryId="BG"    
TalkNo="125" CategoryId="RW"    
TalkNo="126" CategoryId="RW"    
TalkNo="127" CategoryId="RW"    
TalkNo="128" CategoryId="RW"    
TalkNo="129" CategoryId="RW"    
TalkNo="130" CategoryId="KP"    
TalkNo="131" CategoryId="WD"    
TalkNo="132" CategoryId="KP"    
TalkNo="133" CategoryId="BG"    
TalkNo="134" CategoryId="RW"    
TalkNo="135" CategoryId="RW"    
TalkNo="136" CategoryId="RW"    
TalkNo="137" CategoryId="BG"    
TalkNo="138" CategoryId="WD"    
TalkNo="139" CategoryId="BG"    
TalkNo="140" CategoryId="RW"    
TalkNo="141" CategoryId="TP"    
TalkNo="142" CategoryId="FS"    
TalkNo="143" CategoryId="TP"    
TalkNo="144" CategoryId="SQ"    
TalkNo="145" CategoryId="BG"    
TalkNo="146" CategoryId="FY"    
TalkNo="147" CategoryId="FS"    
TalkNo="148" CategoryId="SQ"    
TalkNo="149" CategoryId="FS"    
TalkNo="150" CategoryId="LJ"    
TalkNo="151" CategoryId="FS"    
TalkNo="152" CategoryId="LJ"    
TalkNo="153" CategoryId="LJ"    
TalkNo="154" CategoryId="KP"    
TalkNo="155" CategoryId="RW"    
TalkNo="156" CategoryId="LJ"    
TalkNo="157" CategoryId="SQ"    
TalkNo="158" CategoryId="FS"    
TalkNo="159" CategoryId="FS"    
TalkNo="160" CategoryId="WD"    
TalkNo="161" CategoryId="RW"    
TalkNo="162" CategoryId="KP"    
TalkNo="163" CategoryId="RW"    
TalkNo="164" CategoryId="BG"    
TalkNo="165" CategoryId="SQ"    
TalkNo="166" CategoryId="FS"    
TalkNo="167" CategoryId="WD"    
TalkNo="168" CategoryId="FS"    
TalkNo="169" CategoryId="BG"    
TalkNo="170" CategoryId="KP"    
TalkNo="171" CategoryId="SQ"    
TalkNo="172" CategoryId="FS"    
TalkNo="173" CategoryId="RW"    
TalkNo="174" CategoryId="KP"    
TalkNo="175" CategoryId="BG"    
TalkNo="176" CategoryId="LJ"    
TalkNo="177" CategoryId="TP"    
TalkNo="178" CategoryId="WD"    
TalkNo="179" CategoryId="WD"    
TalkNo="180" CategoryId="KP"    
TalkNo="181" CategoryId="LJ"    
TalkNo="182" CategoryId="KP"    
TalkNo="183" CategoryId="WD"    
TalkNo="184" CategoryId="TP"    
TalkNo="185" CategoryId="SQ"    
TalkNo="186" CategoryId="TP"    
TalkNo="187" CategoryId="BG"    
TalkNo="188" CategoryId="FS"    
TalkNo="189" CategoryId="FS"    
TalkNo="190" CategoryId="FY"    
TalkNo="191" CategoryId="WD"    
TalkNo="192" CategoryId="FS"    
TalkNo="193" CategoryId="LJ"    
TalkNo="194" CategoryId="TP"    
```

**Comment by Fahdeya** [comment]
great, I think it would be a good start

**Comment by cengizu** [comment]
![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/139487d9-f0ef-44d8-90e5-f7d2c2eb4dbd)

Maybe the current layout can be pushed a bit to incorporate the Categories list which should act as a filter. User selects a category and then only themes in this category displays below.

**Comment by ajtruckle** [comment]
@cengizu 
I like that idea. Would be nice if it would work!

I have collated all the existing PTS categories together:

[Talk Cats.xlsx](https://github.com/ajtruckle/meeting-schedule-assistant-support/files/15355334/Talk.Cats.xlsx)

Some of them have their own category ID  so I have to determine what is what (since I now want a hardcoded ID per category across all databases).

Also, I don't have official talk categories for these languages:

- ~Amharic~
- Armenian
- Aukan
- Cibemba
- Croatian
- Czech
- Estonian
- ~Gujarati~
- Gun
- Haitian Creole
- Hindi
- Hungarian
- Malagasy
- Maltese
- ~Pidgin English West Africa~
- ~Portuguese Portugal~
- ~Punjabi~
- Saramaccan
- ~Sesotho South Africa~ (using English)
- Setswana
- Slovenian
- Tamil
- ~Tsonga~
- Zulu

We would have to reach out for this information as I want to use official phrases for this kind of thing.

**Comment by ajtruckle** [comment]
@Fahdeya, I have updated most of the databases.

## No Public Talks Database ##
There are some languages for which I lack public talk outline or category information.

- Amharic
- Aukan
- Czech
- Estonian
- Gujarati
- Hindi
- Malagasy
- Maltese
- Pidgin English (West Africa)
- Saramaccan
- Sesotho (South Africa)
- Setswana
- Slovenian
- Tamil

## Incomplete Public Talk Databases ##
The databases listed below are incomplete. It would be wonderful if we could include the missing outlines.

| Language | Maximum Outline |
|----------|-----------------|
| Albanian  | 187             |
| Cebuano  | 183             |
| Gun      | 192             |
| Swedish  | 187             |
| Vietnamese  | 193             |

Note that some of the above languages are also missing additional outlines.

## No Public Talk Categories ##
Finally, these languages lack the public talk category translations:

- Armenian
- Cibemba
- Croatian
- Haitian Creole
- Hungarian
- Zulu

**Comment by ajtruckle** [comment]
@Fahdeya @cengizu 
Thanks for the advice Cengiz concerning the new layout for the **Public Talks Database** window. 👍🙏

Fahd, the controls have been re-organized to make room for:

- Talk Category Filter Combo
- Talk Category

The _filter combo_ is populated with the list of categories but the filtering mechanism does not actually work yet. However, the _talk category_ does update as you select each outline in the list. For example:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/ab4247ed-b2f5-44c1-8a1e-0e53005d6ca5)

I have also identified a bug with editing existing away talk entries (the date changes when you have to select a different congregation). I might need to release 24.8.3 with that correction. We will see.

**Comment by ajtruckle** [comment]
@Fahdeya 
https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/43baf697-165e-4c9d-9ff1-549fd901fcb9

**Comment by ajtruckle** [comment]
@Fahdeya 

https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/1713fb7d-29d5-4a7a-b167-852a8f20b8f3

**Comment by ajtruckle** [comment]
@Fahdeya @cengizu 
I have now sent you a beta to try.

Things to test:

- Public Talks Database window
- Public Talks Database (Submit Update window)
- Weekend Meeting window

I have not made any changes for reports yet. I would like us to concentrate on this side of things first and make sure it is all OK.

**Comment by Fahdeya** [comment]
Hi,
in the Meeting Editor, Weekend Meeting, I have tried to choose a talk, so I did what follows:
1. chose a congregation
2. chose a speaker
3. without editing the Category, I chose the Theme
Should here have the Category changes according to what is linked to the talk?
while in the Public Talks Database, the Category changes according to the talk, which is more logic
Thank you,
Fahd

**Comment by ajtruckle** [comment]
@Fahdeya 

> without editing the Category, I chose the Theme
> Should here have the Category changes according to what is linked to the talk?

Ah, I see what you mean. The category droplist is a filter. It is not a field so-to-speak. The PT database window has both. 

I am actually getting pushed for space on the WM meeting window for extra controls. 

@cengizu What do you think about this solution? I turn the category into a read-only field. Then. add a hamburger on the right which shows a list of categories on a menu? It is all I can think of. But if you have a simpler solution where I can keep the droplist …

**Comment by cengizu** [comment]
@ajtruckle 
Here is an idea:
![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/56188925-892e-45a6-a2bf-885b2937e629)

Notes:

1. **Category** field remains a filter. When nothing selected, displays all talks. When specific filter clicked, only talks within this cat displays. 
2. Next to category is a **read-only field**. Displays category of a selected talk. 💡This funcltionality already exist in the new PT Db window, so nothing new.
3. As a bonus, an Hamburger button can be added to include a shortcut to **Public Talks Database** (main window menu Database > Public Talks > Manage).

**Comment by ajtruckle** [comment]
@cengizu 
> As a bonus, an Hamburger button can be added to include a shortcut to Public Talks Database (main window menu Database > Public Talks > Manage).

Thanks for your idea! 😀 As for the hamburger idea… I don’t mind implementing it, but:

1. Using a menu item called Manage is not going to be clear. And I have only just asked for translations from our brothers. 

2. What specific benefit will users gain by having this shortcut?

3. Will there be repercussions to the data on the WM window itself as a result of any changes made by the user in the talks DB?

At the moment I think I won’t add a hamburger button until the above concerns are cleared up.

**Comment by ajtruckle** [comment]
@Fahdeya @cengizu 
I have just sent you both a new beta version. 

- In the **Weekend Meeting** window, we now have a control for the _talk category field_.
- In the **Public Talks** database window, I have renamed _Last invited:_ to _Last given:_.

**Comment by Fahdeya** [comment]
hi,

I found the adjustment for the Weekend meeting, but for the Public Talks database window, I think I should send the translation of this phrase in Arabic, right?
If yes it should be:

قُدم مؤخرا بتاريخ:‏

and this phrase should be changed also in the Report of the Public talks

thank you

**Comment by ajtruckle** [comment]
@Fahdeya 
> I think I should send the translation of this phrase in Arabic, right?

I am not sure what phrase you are referring to? Arabic is a partial translation as you know so the GUI stays in English for the main part. Screen shot?

Also, don't forget to re-submit the changes for talk 71 via the updated GUI please.

**Comment by ajtruckle** [comment]
@Fahdeya @cengizu 
I think that the _filter_ should also be applied to the **talk history** list:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/7f46e450-ad78-4454-8b9f-608fc9111e64)

There will be some complications if we decide to cater for this that I will need to address.

**Comment by Fahdeya** [comment]
> @Fahdeya
> 
> > I think I should send the translation of this phrase in Arabic, right?
> 
> I am not sure what phrase you are referring to? Arabic is a partial translation as you know so the GUI stays in English for the main part. Screen shot?
> 
> Also, don't forget to re-submit the changes for talk 71 via the updated GUI please.

Yes you are right. sorry

**Comment by ajtruckle** [comment]
@Fahdeya @cengizu 
I think there is one change to the _existing_ reports. The category could be displayed on the **Talk List** report in PTS:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/cb40f0e2-f728-4185-919b-4b8d0e6f956e)

We can add a similar option to the **List** report in MSA:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/7a247fad-cc61-4d0f-8b53-69c36dc5e102)

But we might have to reduce the font size to make room for the additional column.

**Comment by ajtruckle** [comment]
@cengizu @Fahdeya 
Finally, there is the possibility of one new report. In PTS it has the **Talks by Categor**y report:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/44f0a5b0-1277-409d-8099-787576f977a2)

We could consider replicating this in MSA.

**Comment by cengizu** [comment]
Instead of a new column for categories, how about putting them in a row? E.g. When sort by categories is selected, all talks are put into rows in categories and the category name is displayed above the relevant row blocks. It is possible on paper, but I don't know how it works in practice.

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/3d1581ba-3004-40b5-902c-2d9b180c14dd)

**Comment by ajtruckle** [comment]
@cengizu 
> Instead of a new column for categories, how about putting them in a row? E.g. When sort by categories is selected, all talks are put into rows in categories and the category name is displayed above the relevant row blocks. It is possible on paper, but I don't know how it works in practice.

The idea is good, but I believe the original report should continue to use a column to maintain consistency with the corresponding report in PTS. However, we could introduce a second template to the application that organizes the talks by category.
