### ISSUE TITLE
Separate name fields for Platform and Roving Microphone and Entrance and Auditorium Attendants

### ISSUE THREAD

**Issue by DVanEyck** [ajtruckle/meeting-schedule-assistant-support#67]
At present the schedule has an option to enter Platform/Roving and only 1 name can be entered,
Same for Attendant, whereas we have 2 brothers assigned - Entrance and Auditorium.

How can we have 2 name fields for each of the above Assignments?

**Comment by ajtruckle** [comment]
@DVanEyck 

Sorry for any confusion. Please double check the **General Options**:

https://www.publictalksoftware.co.uk/help-msa/msa-options-settings.html#NUMBER_OF_USERS

This is where you set the number allocated to each of those assignments.

**Comment by DVanEyck** [comment]
Thank you.

**Comment by DVanEyck** [comment]
Thank you. I went through that. It adjusts the way the Assignments schedule is displayed but does not affect the way names can be selected on the Midweek Meeting Schedule.

Only 1 name can be selected for each of the assignments although the label is Platform/Roving.

**Comment by ajtruckle** [comment]
@DVanEyck 
Is it possible to provide a screen shot to give me some context? Thank you.

**Comment by DVanEyck** [comment]
[image: Capture.PNG]
Only 1 name can be entered whereas we have separate brothers from Platform and Roving Mic, and also 2 Attendants, Entrance Attendant and Auditorium Attendant. I have specified them in the Custom Assignments.
[image: Capture1.PNG]

But I have to enter names manually because there is only 1 drop-down box available.

**Comment by ajtruckle** [comment]
I can't see the images?

**Comment by ajtruckle** [comment]
@DVanEyck 
Please attach images using either the GitHub app or GitHub website. Responses by email will strip images.

**Comment by DVanEyck** [comment]
I don’t know how to do that so I will send them on WhatsApp

**Comment by ajtruckle** [comment]
Got your images:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/f255e310-d67b-48bd-864f-aeae0794cf66)

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/86d92c48-98bb-4daf-af57-9e901f5a5249)

Now I understand. The area of the editor you are using is specifically for these roles:

- Host
- Cohost
- Zoom Attendant

The other duties, such as:

- Attendants
- Platform
- Platform Mike
- Mike

They are actually managed using the [Assignments Editor](https://www.publictalksoftware.co.uk/help-msa/srr-editor.html). Create a new assignment schedule with that editor for the chosen date range. Then, from within the Meeting Editor you can use the [Duty Assignments](https://www.publictalksoftware.co.uk/help-msa/mwb-editor-edit-duty-assign.html) feature on the **Edit** menu if needed. 

There is no need to create custom assignments for this.

**Comment by DVanEyck** [comment]
OK. Thank you.
Especially for the quick response.
David

**Comment by ajtruckle** [comment]
You're welcome! I'll close this issue now. 👍
