### ISSUE TITLE
Labels overlapped to button

### ISSUE THREAD

**Issue by stecchio66** [ajtruckle/meeting-schedule-assistant-support#68]
**Describe the bug**
When the interface is in italian, the buttons "Custom Text" (for songs), overlap the nearby labels.

**To Reproduce**
Open midweek schedule

**Expected behavior**
Buttons and labels are spaced correctly

**Screenshots**
![2024-04-27_14-57-56](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/118082203/6e5de093-781c-47fd-a75b-7a4f60e1da23)

**Desktop (please complete the following information):**
 - OS: Win 10

**Comment by ajtruckle** [comment]
@stecchio66 

I have just sent you a beta to try.

**Comment by stecchio66** [comment]
Now all is ok.
![2024-04-27_20-31-17](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/118082203/58ff1fbf-27aa-4ec3-a30a-4c41743eb1fd)

Thanks!
