### ISSUE TITLE
Increase width of some textboxes

### ISSUE THREAD

**Issue by stecchio66** [ajtruckle/meeting-schedule-assistant-support#69]
**Is your feature request related to a problem? Please describe.**
The follows textboxes often can't show the full name:
- Chairman
- Initial prayer
- Aux Counsellor 1
- Aux Counsellor 2
- Host
- Co-Host
- Zoom Attendant

**Describe the solution you'd like**
Shrink the width of the following text boxes:
- Note
- Bible reading for week
- Opening song

To increase the space available for other textboxes with names.

**Describe alternatives you've considered**
I don't see any alternatives

**Additional context**
Textboxes in the blue outline to be enlarged and textboxes in the red outline to be shrink.
![2024-04-27_18-06-17](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/118082203/ec7c385e-abdf-482a-83e3-2a51aa106f92)

**Comment by ajtruckle** [comment]
@stecchio66 

I concur that the width of the drop-down lists is suboptimal. The issue arises when the window is at its minimum size; the notes field becomes quite small. We need to reorganize the controls to ensure they function well at the default window size.

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/90db8c05-83b1-4037-be6b-a3b1f03d314f)

I am open to ideas!

**Comment by cengizu** [comment]
@stecchio66 @ajtruckle 

Here is a first attempt:
![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/16a06115-68cc-47f3-bfeb-7a655b331854)

**Comment by cengizu** [comment]
@ajtruckle @stecchio66 

A second attempt with a slight difference:
![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/35796a4c-105c-4e4f-9e74-3355ef644c79)

**Comment by ajtruckle** [comment]
@cengizu 

I want to thank you for all your hard work in putting together a proposal. It was not an easy feat by any means! 🙏

I have made some minor changes and taken on board some private feedback from @stecchio66 .

This is the current layout:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/fe3cfbd7-8548-4eb8-85d4-ef95278e0a3b)

* The Student Bible reading **material** is to be moved out from the Materials window.
* We have scope to further adjust the widths of the name drop-lists. Just tell me what you think. 🤔

I have decided to simplify things further. This lefthand side will now stay the same size when the window is **maximised**. The viewing area is enlarged instead. Example:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/7eff4afe-220a-4c68-b65b-66d7edff9189)

I am still working on interfacing the new changes into the editor.

**Comment by ajtruckle** [comment]
@cengizu @stecchio66 
I will permanently disable the additional Bible Reading controls. Only the first set need to be enabled for setting the study point, material and time.

- The controls for class 1 / 2 could be automatically kept in sync as changes are made for the Main Hall assignment.
- Or, we don't show the material etc. for class 1 / 2. But then we have a lot of wasted space.

**Comment by cengizu** [comment]
@ajtruckle 

Additional Bible Reading controls can remain, but disabled for reference only. They provide a visual reference for users and fills the gaps.  The first control is for user input, the other controls will be mirroring it. 

Additionally, slight improvements could be made to the layout of the controls so that there is more symmetry and alignment. OCD Alert! 😁

**Comment by ajtruckle** [comment]
@cengizu @stecchio66 

I have standardized all name controls wo be 100 pixels wide and done some minor changes to alignments.


https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/27f44543-9a07-4f6f-b409-174e8f198831

**Comment by ajtruckle** [comment]
@cengizu 

> Additionally, slight improvements could be made to the layout of the controls so that there is more symmetry and alignment. OCD Alert! 😁

Are you  referring to the TFGW section specifically, or was that a general statement? I ask because I have made some refinements, as shown in my video.

**Comment by cengizu** [comment]
@ajtruckle 

it was before you posted the video. It looks better now.

**Comment by ajtruckle** [comment]
@cengizu  @stecchio66 

New Weekend Meeting window:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/5076fc77-da9d-44f8-9620-f1468a7785ab)

### Other Improvement: ###

- **Notes and Images** are now available via _hamburger_ buttons.

**Comment by ajtruckle** [comment]
@cengizu @stecchio66 

Idea:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/519af241-b006-49f2-8a15-4d8f5f5e72af)

Both editors would be the same.

**Comment by cengizu** [comment]
Looks good 👍
**Midweek Editor**
![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/ef054578-9714-487e-b6b4-00ef1d86ad8d)

**Weekend Editor**
![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/eeb4309b-7eaf-49df-9320-0a13697de2b5)

**Comment by stecchio66** [comment]
In my tests of the last beta I noticed that although I entered 2 auxiliary classes in the student assignment window, the fields were not enabled.

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/118082203/bbe14d73-e333-4cf2-9df9-1b148da35ccc)

**Comment by Fahdeya** [comment]
I faced this too. But the Classes field was set to 1 instead of 2. And the names that were previously assigned to the 2nd class were dimmed. When I change the number of Classes to 2, it works properly

**Comment by ajtruckle** [comment]
@stecchio66  @Fahdeya 
I forgot that I still had the original **Aux Class 1** / **Aux Class 2** checkboxes on the editor. They were set to be _hidden_. I have now removed them from the application and think this issue is resolved. Sending you new betas.

**Comment by Fahdeya** [comment]
It seems that there is still something wrong. When I installed the new update for this version, the Classes field is set to "1" and not as it was. It was "2"
[03 May-June.MWB.txt](https://github.com/ajtruckle/meeting-schedule-assistant-support/files/15212711/03.May-June.MWB.txt)
enclosed it the file that I open with the new version

**Comment by ajtruckle** [comment]
@Fahdeya 
Does not seem wrong to me.  Looking at your first week you only have one class. You don't have two classes. And when I click the button to display the students, you again only have students for one class.

Please keep in mind that the **Classes** setting is specifically for the number of _auxiliary classes_. The main hall audience is not included in this count.

**Comment by stecchio66** [comment]
> Sending you new betas.

@ajtruckle It seems to work well for me.

**Comment by Fahdeya** [comment]
I am saying about week starts from 6-12, we have two classes, there in the old edition the Classes field text was 2, now it is 1.

Also, all the weeks that have 2 classes are now set to 1, while the weeks that has one class is set to 0.

It seems that this is because you have added value "0" to the list. So, "1" becomes "0", etc...

**Comment by Fahdeya** [comment]
Thank you Andrew for making it clear to me. There is no problem for me now.

**Comment by ajtruckle** [comment]
@stecchio66 @cengizu @Fahdeya 
We are still working on updating all the help topics. But are we in agreement that I can now close this ticket?

**Comment by Fahdeya** [comment]
Its yes for me

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by stecchio66** [comment]
> @stecchio66 @cengizu @Fahdeya We are still working on updating all the help topics. But are we in agreement that I can now close this ticket?

@ajtruckle Yes
