### ISSUE TITLE
Add Zoom feature to Script Editor

### ISSUE THREAD

**Issue by ajtruckle** [ajtruckle/meeting-schedule-assistant-support#70]
**Is your feature request related to a problem? Please describe.**
It would be useful to have the ability to make the code smaller / larger in the Script Editor.

**Describe the solution you'd like**
Implement a Zoom feature, similar to the one in NotePad++:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/e9ec193a-5568-4c66-b35e-cc750d4c9d8e)

**Additional context**
-  Scintilla Reference: https://www.scintilla.org/ScintillaDoc.html#Zooming
-  Notepad++ Localization: https://github.com/notepad-plus-plus/notepad-plus-plus/tree/master/PowerEditor/installer/nativeLang

**Comment by cengizu** [comment]
@ajtruckle 
Sure, this will be a nice and subtle touch. 👍

**Comment by ajtruckle** [comment]
@cengizu 
Here is the new wording for the help topic:

> ## Zoom
> Flyout menu:
> ![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/f272ab46-4187-4e77-bbc3-2617d41bde56)
> ### Zoom In (Ctrl+Mouse Wheel Up / Ctrl+Num +):
> - Use this option to magnify the content of your current document, making text appear larger and more readable.
> - Shortcut: Hold down the Ctrl key and scroll up with your mouse wheel, or press Ctrl+Num + on your keyboard.
> ### Zoom Out (Ctrl+Mouse Wheel Down / Ctrl+Num -):
> - This option reduces the size of the content on your screen, allowing you to see more of your document at once.
> - Shortcut: Hold down the Ctrl key and scroll down with your mouse wheel, or press Ctrl+Num - on your keyboard.
> ### Restore Default Zoom (Ctrl+Num /):
> - If you’ve zoomed in or out and want to return to the default view size, select this option.
> - Shortcut: Press Ctrl+Num / on your keyboard.
