### ISSUE TITLE
Missing Living as Christian items on schedule preview

### ISSUE THREAD

**Issue by ajtruckle** [ajtruckle/meeting-schedule-assistant-support#73]
**Describe the bug**
Received from a brother:

> There is an issue with the appearance in the program as you will see in the images.
In the print file it does not display the 2 parts.

**To Reproduce**

1. Set the number of Living as Christian items to 2 or 3
2. Refresh the display (F5)
3. See error

**Expected behavior**
Only the first item is displayed on the schedule.

**Screenshots**
![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/350bf714-4b85-4b2d-9fea-b744862a6adb)

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/ce4fa4eb-0755-4f4f-8c96-2025ac2e3992)

**Additional context**
This started happening  with version 24.8.0.

**Comment by ajtruckle** [comment]
Thank you for bringing this issue to my attention! I think I have corrected the issue.

**Comment by KOUKLHS** [comment]
το σφάλμα αποκαταστάθηκε με την εκδοση 24.8.1 βετα
![303](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/156582027/732590a7-d88e-465b-a030-0d6025ec1f9d)
![304](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/156582027/b9a09666-e9d1-4e3b-8e19-a5adf9f94757)
