### ISSUE TITLE
Using Find / Find Next in the Script Editor

### ISSUE THREAD

**Issue by ajtruckle** [ajtruckle/meeting-schedule-assistant-support#74]
**Describe the bug**
The Find/Find Next function works really well in the Script Editor. However, there are times when the highlighted text becomes unreadable due to the low contrast between the text colour and the highlight colour.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open or create a schedule using the Meeting Editor.
2. Right-click on the schedule preview and select View > View XSL.
3. Activate the Find feature.
4. Enter a word or phrase that you know is within a `<!-- .... -->` comment.
5. Observe the error.

**Expected behaviour**
Highlighted text must always remain legible.

**Screenshots**

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/44c3a842-cce1-41a9-899f-d8599b98609b)

**Comment by ajtruckle** [comment]
This looks better IMHO:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/ef7ed543-0289-4422-87e8-2aa1ea32212a)

**Comment by ajtruckle** [comment]
The current line is now highlighted with a light grey background:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/109098f9-2d23-47b3-a488-abb192f33a3b)

And I should clarify that all selected text will display like this now _when the editor has focus_:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/d385b924-5bd0-4c5c-b3e1-1e99aff4bc7f)

**Comment by cengizu** [comment]
@ajtruckle 

This one is good for light theme. For dark theme users, it would be good to do some tests to make sure grey and blue bg will be visible or set another color for them.

> The current line is now highlighted with a light grey background:
> 
> ...
> 
> And I should clarify that all selected text will display like this now _when the editor has focus_:
> 
> ...

**Comment by ajtruckle** [comment]
@cengizu 
I use dark theme on Windows 11 and you can see my screenshots already. But note that MSA itself does not support a light / dark theme concept and never will. The MFC framework does not support it.
