### ISSUE TITLE
Add Indent / Outdent to Script Editor

### ISSUE THREAD

**Issue by ajtruckle** [ajtruckle/meeting-schedule-assistant-support#80]
**Is your feature request related to a problem? Please describe.**
Add ability to outdent / indent selected to to Script Editor

**Describe the solution you'd like**
Add Indent flyout to Edit menu with:

* Increase Line Indent
* Decrease Line Indent

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/f8192429-d3cf-49a4-a961-9d57379e9b5d)

**Describe alternatives you've considered**
Pressing TAB will indent but pressing BACKSPACE deletes the selected text.

**Translations** 
Fortunately, Notepad++ has their [translations](https://github.com/notepad-plus-plus/notepad-plus-plus/tree/master/PowerEditor/installer/nativeLang) available online! So I have collated the ones we need:

| Language | Translation         | Translation                            | Translation                             |
|----------|---------------------|----------------------------------------|-----------------------------------------|
| eng      | Indent              | Increase Line Indent                   | Decrease Line Indent                    |
| csy      | Odsazení            | Vložit tabulátor (zvětšit odsazení)    | Odstranit tabulátor (zmenšit odsazení)  |
| dan      | Indrykning          | Forøg linieindrykning                  | Formindsk linieindrykning               |
| deu      | Einrückung          | Zeileneinzug vergrößern                | Zeileneinzug verkleinern                |
| ell      | Εσοχή               | Αύξηση Εσοχής Γραμμής                  | Μείωση Εσοχής Γραμμής                   |
| esp      | Tabulación          | Aumentar                               | Reducir                                 |
| fin      | Sisennys            | Sisennä enemmän                        | Vähennä sisennystä                      |
| fra      | Indentation         | Augmenter l’indentation                | Réduire l’indentation                   |
| hun      | Behúzás             | Behúzás növelése (Tabulátor beszúrása) | Behúzás csökkentése (Tabulátor törlése) |
| ita      | Indenta             | Inserisci tabulazione (indent)         | Rimuovi tabulazione (outdent)           |
| jpn      | インデント          | インデントを増やす                     | インデントを減らす                      |
| nld      | Inspringing tekst   | Inspringing van regel vergroten        | Inspringing van regel verkleinen        |
| plk      | Wcięcie             | Zwiększ wcięcie                        | Zmniejsz wcięcie                        |
| ptb      | Indentar            | Inserir tabulação                      | Remover tabulação                       |
| ptg      | Indentação          | Aumentar indentação da linha           | Diminuir indentação da linha            |
| rom      | Indentare           | Mărire indentare linie                 | Reducere indentare linie                |
| rus      | Отступы (табуляция) | Вставить Отступ (табуляция)            | Убрать Отступ (табуляция)               |
| slv      | Zamik               | Povečaj zamik vrstice                  | Zmanjšaj zamik vrstice                  |
| sqi      | Kryeradhë           | Rrit linjën e kryeradhës               | Ul linjën e kryeradhës                  |
| sve      | Indrag              | Öka indrag (infoga tabb)               | Minska indrag (ta bort tabb)            |
| trk      | Satır Girintisi     | Girintiyi Artır                        | Girintiyi Azalt                         |
| ukr      | Відступ             | Збільшити відступ рядка                | Зменшити відступ рядка                  |

**Comment by ajtruckle** [comment]
I have added the Indent/Outdent feature to the Script Editor.

**Comment by ajtruckle** [comment]
## Help Text
* Increase Line Indent
Moves the selected line or paragraph to the right, adding an additional level of indentation. This is useful for organizing text hierarchically, such as in outlines or nested lists.
Shortcut: Tab

* Decrease Line Indent
Moves the selected line or paragraph to the left, reducing the level of indentation. This helps in restructuring the text to a higher level in the hierarchy or aligning it with less indented text.
Shortcut: Shift+Tab

**Comment by cengizu** [comment]
Nice addition, it works as expected.
