### ISSUE TITLE
Add Confirmed field for Public Talk assignment

### ISSUE THREAD

**Issue by ajtruckle** [ajtruckle/meeting-schedule-assistant-support#82]
_Originally posted by @ajtruckle in https://github.com/ajtruckle/meeting-schedule-assistant-support/issues/51#issuecomment-2137874310_

**Comment by ajtruckle** [comment]
Use this icon:

https://www.flaticon.com/free-icon-font/user-time_3914150?page=1&position=68&term=clock&origin=search&related_id=3914150

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/7938287c-fdaa-4e47-92ec-e8308d0b5b92)

Sized to 16 pixels.

**Comment by ajtruckle** [comment]
Progress:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/70fe3f6c-f7cc-4cbd-85b1-09ee63233257)

* Check the option to indicate the exchange is confirmed. This is the default setting.
* The icon is enabled when the exchange is confirmed.
* Hover over button to see status message.
* Clicking button shows same status message in popup window.
* Uncheck to disable the button and indicate as not confirmed.
* Save to MWB saves the confirmed status.
* Read from MWB reads the confirmed status and defaults to confirmed for older files.
* Swapping talks also swaps the confirmed status.

**Comment by cengizu** [comment]
@ajtruckle 
Simple and clear. It makes sense to have this feature. The visuals can be improved over time, if needed.

**Comment by ajtruckle** [comment]
@cengizu 
Thanks for the feedback. 😊 There are still some scenarios that I have to revise in the coming days to complete this feature.

**Comment by ajtruckle** [comment]
Progress:

* Add `PublicTalkConfirmed` node to history database.

**Comment by ajtruckle** [comment]
Progress:

* Include away talk confirmed status in history database.
* Handle away talk confirmed status when swapping talks.
* Handle away talk confirmed status when reading / writing to MWB.

Things became a bit more complicated when it came to serialization of away talk data. But I think I have overcome the hurdles that I encountered.

There are several things that I would still like to address:

1. Default the away talk confirmed status to true for new away talks.
2. Consider adding an away talk confirmed status column to the away talk grid. My only concern is that it is getting cramped.
3. Update the Import feature (from PTS) to include the inverse of the Tentative field during importing.
4. Update some of the Congregation  reports to show unconfirmed exchanges in a red font.

**Comment by ajtruckle** [comment]
Progress:

* Default the away talk confirmed status to true for new away talks.
* Update the Import feature (from PTS) to include the inverse of the Tentative field during importing.

We could possibly add a new setting to the software to let the user specify what the default "Confirmed" setting should be.

**Comment by ajtruckle** [comment]
> 4. Update some of the Congregation reports to show unconfirmed exchanges in a red font.

The Public Talks [Summary](https://www.publictalksoftware.co.uk/help-pts/pts-talks-summary-setup.html) report has a setting for the tentative colour:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/929fa804-38dd-47f7-a8be-e35e204c92b7)

We could add that setting the to Meeting Schedule Assistant version of the [Summary](https://www.publictalksoftware.co.uk/help-msa/msa-talkdb-report-viewer-setup.html#SUMMARY) report:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/1c211eea-632e-43f0-aa53-06e2fe615968)

**Comment by ajtruckle** [comment]
Progress:

* Revised the **Talk DB--Public Talks Report** (_Summary_ mode) to display unconfirmed talk exchanges with blue text.
