### ISSUE TITLE
Improved Filter function

### ISSUE THREAD

**Issue by cengizu** [ajtruckle/meeting-schedule-assistant-support#92]
**Is your feature request related to a problem? Please describe.**
In the current operation, filters can be applied to the publisher thanks to the filter feature in the Publisher Database window. When several filters are selected, the selected filters have to be manually removed again to return to initial view.

**Describe the solution you'd like**
A clear filters button would be practical. Also, Brother and Sister filters can also be added.

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/f2c18015-6217-4de2-b2d4-8db3afb04e04)

**Comment by ajtruckle** [comment]
@cengizu 
> A clear filters button would be practical. 

Thanks for your suggestion.💡 So clicking the **Reset** button would untick all the filtered choices. This is a useful feature!

> Brother and Sister filters can also be added.

I never thought about adding those. No reason not to! This is the existing drop-down menu:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/04dfc7c3-ccbb-4dab-af79-4c7c8d662690)

Should we add these new filters to the top of the menu, followed by a separator? Or at the bottom?

>[!NOTE]
> Please attach the **icon** you used to this ticket and provide the **url**. 🙏

**Comment by cengizu** [comment]
@ajtruckle 
These can be added to top followed by a seperator.

**Comment by cengizu** [comment]
@ajtruckle 

Here is the clear filter icon: https://www.flaticon.com/free-icon/clear-filter_7794671?related_id=7794671

**Comment by ajtruckle** [comment]
@cengizu 
Thanks for the link to the icon. I attach it here for convenience.

![clear-filter](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/f79f28b3-7491-4f89-b3de-83d48a2b5fcf)

Attribution (for Credits):

```html
<a href="https://www.flaticon.com/free-icons/filter" title="filter icons">Filter icons created by Rahul Kaklotar - Flaticon</a>
```

**Comment by ajtruckle** [comment]
@cengizu 
The improvements have been implemented. A beta version is now available for you to try.

**Comment by cengizu** [comment]
@ajtruckle 

Clear filter works nice. 👍

**Comment by ajtruckle** [comment]
@cengizu
I am pleased that it works well for you. Thanks for suggesting it!

Updated help topics:

* https://github.com/ajtruckle/meeting-schedule-assistant-support/wiki/msa-revision-history
* https://github.com/ajtruckle/meeting-schedule-assistant-support/wiki/msa-database-publishers#extra-publisher-filters

**Comment by cengizu** [comment]
@ajtruckle 

Just remarked this little issue when resizing the publisher window.
![Recording 2024-07-08 111808](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/66d82f7a-9877-417b-b9ff-b16fe12df386)

**Comment by ajtruckle** [comment]
@cengizu 
Well spotted! 👀 Thanks for bring the issue to my attention. And, thanks for sending me updated screenshots for the help documentation. 🙏

New beta on it's way to you. 🚀
