### ISSUE TITLE
Gender related appointments in Publisher Database

### ISSUE THREAD

**Issue by cengizu** [ajtruckle/meeting-schedule-assistant-support#93]
**Is your feature request related to a problem? Please describe.**
In the Publisher window, the Appointed As list is open regardless of gender selection. 

**Describe the solution you'd like**
Since it is unlikely that a sister will be appointed to one of these posts, it is better to deactivate this list when Sister is selected. 

**Bonus**
The Assignments list can also be made smarter. When a sister is selected, tasks that only sisters can do can be automatically selected. If the person is an elder or MS, appropriate tasks can be selected by default, etc.

![Recording 2024-07-05 103221](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/763dddd5-fe4b-49a1-9601-5cd8dc1e47cd)

**Comment by ajtruckle** [comment]
@cengizu 
> Since it is unlikely that a sister will be appointed to one of these posts, it is better to deactivate this list when Sister is selected.

Thanks for your suggestion. I admit that sisters don't get appointed as Ministerial Servants or Elders and it makes sense to disable this controls for clarity. I would be interested in the thoughts of other users about this proposal. 🤔

> The Assignments list can also be made smarter. When a sister is selected, tasks that only sisters can do can be automatically selected. If the person is an elder or MS, appropriate tasks can be selected by default, etc.

I see where your coming from, but please keep in mind that we have _finer_ levels of assignments in the list. The way it is set up means the maintainer has to specifically set the roles for the publishers. If we used defaults then they may overlook the _finer tweaks_ that they can take advantage of. Eg:

* Some sisters are only assistants on the school.
* Some brothers only do Bible readings on the school or they don't do talks etc.

**Comment by stecchio66** [comment]
@ajtruckle 
Could be a good idea to disable the Appointed combo when the Gender is set to Sister.

**Comment by ajtruckle** [comment]
@cengizu @stecchio66 
I have now implemented this adjustment to the GUI. A beta is on its way to you for testing. 📫

**Comment by cengizu** [comment]
Tested, and it works nice. 

When sister is selected, **Appointed As** dropdown list becomes disabled.

**Comment by ajtruckle** [comment]
Updated help topics:

* https://github.com/ajtruckle/meeting-schedule-assistant-support/wiki/msa-revision-history
