### ISSUE TITLE
Failure of the history feature to track a congregation name change

### ISSUE THREAD

**Issue by cengizu** [ajtruckle/meeting-schedule-assistant-support#94]
**Describe the bug**
When a congregation name is changed, the new congregation name appears in the assignment history panel, but all assignments performed by that congregation under the old name are reset. 

**To Reproduce**
1. Go to Database > Congregations > Edit > [Congregation Name]
2. Change name to [new name]
3. Click OK
4. Check Assignment History panel for that congregation

**Expected behavior**
When the name of the congregation is changed, the History database should also be updated.

**Screenshots**
![image](https://github.com/user-attachments/assets/4ca80a12-9529-497d-96b5-b0fb17b73d1a)
**Khazad-dûm** before name change

![image_2024-07-16_17-21-10](https://github.com/user-attachments/assets/9cd1eab2-3ab9-4305-b936-a6c70211725f)
**Khazad-dûm** after name changed to **Isengard**

**Comment by ajtruckle** [comment]
@cengizu 
Thanks for raising the issue. There are several actions that need to be improved:

- Rename Congregation
- Rename Speaker
- Delete Congregation
- Delete Speaker

All of these actions need to update the history database to keep it intact.

> [!NOTE]
> The delete actions should set the value as `¬DELETED¬` for consistency with the **Publisher Database**.

**Comment by ajtruckle** [comment]
@cengizu 
I am sending you a beta with the following improvements:

* Changing the name of an existing congregation should propagate the change throughout the assignment history database.

> [!NOTE]
> I have not tested this.

**Comment by cengizu** [comment]
@ajtruckle 

Seems to be working. Issue solved from my perspective. 👍

**Comment by ajtruckle** [comment]
@cengizu 
Great! I am sending you another beta with the following updates:

* Renaming a speaker should now propagate the changes into the history database.

There are somethings to keep in mind:

* It will only update the history where all the xml elements are present for the meeting
* It will not update the PrayerClose element for the weekend meeting.
