### ISSUE TITLE
Availability of speakers

### ISSUE THREAD

**Issue by cengizu** [ajtruckle/meeting-schedule-assistant-support#95]
**Is your feature request related to a problem? Please describe.**
The Speakers window uses a list of dates to determine when a speaker is available, with a box next to each date. By default, these boxes are not selected. Novice users will logically try to select these boxes one by one to indicate the dates when a speaker is available. However, the fact that none of the boxes are selected already indicates that the speaker is available. This confusion should be cleared up.

![image](https://github.com/user-attachments/assets/da1cb0df-4fcc-4ea4-a532-e77912391f1e)
Without a visual clue on the dates, the “not available at all” checkbox at the bottom doesn't seem to make sense either.

**Describe the solution you'd like**
The solution is simple, the same process as in the Publisher window should be adopted here. **Initially all checkboxes are selected, only the checkboxes on unavailable dates are unchecked.**

![image](https://github.com/user-attachments/assets/c80db140-e2ec-419c-8de9-057427368589)
List showing availability in the Publisher window.

**Additional feature**
It can be considered whether a **date range button** can be added (same as in Publisher window) . E.g. some speakers may be unavailable for a whole month or several months and this feature would provide convenience to the user.

**Comment by ajtruckle** [comment]
@cengizu 
I appreciate you highlighting this matter! It is indeed confusing to have two distinct methods for indicating the dates when a publisher or speaker is unavailable. Addressing this issue is certainly necessary.

Additionally, there is an open bug ticket (#96) that needs fixing for both availability checklists. I will tackle this issue too.

> [!NOTE]
> The Publishers Database window displays a grid with a list of selectable dates, formatted according to the software's custom date setting (if specified). On the other hand, the Speaker window employs a basic listbox (designed as a checklist) and adheres to the short date format. I have a preference for the standard listbox. I'm open to your opinions 🤔 - we might decide to keep them unchanged.

**Comment by ajtruckle** [comment]
@cengizu 
I am forwarding a beta version with the following updates:

* The speaker date list now uses the custom date format setting.
* The logic for the speaker date list is now consistent with that of the Publisher Database window.

**Comment by ajtruckle** [comment]
@cengizu 
I am forwarding another beta version with the following updates:

- Add **Date Range** button handler
- Disable dates list when **Not available as all** is checked.

**Comment by cengizu** [comment]
@ajtruckle 
> Disable dates list when Not available as all is checked.

This is a nice touch! Thank you, all works fine

**Comment by ajtruckle** [comment]
@cengizu 
I am forwarding another beta version with the following update:

* Updated the Publishers Database window to display the dates list as a **checkable list box** instead of a **grid control**.

**Comment by cengizu** [comment]
@ajtruckle 
🥳
![MSA-update](https://github.com/user-attachments/assets/7794b0bd-3e11-49b0-a894-214b16750388)

a more harmonized interface

**Comment by ajtruckle** [comment]
@cengizu 
Thanks for testing! 🙏 I am closing the ticket now, and we can proceed to update the help documentation as necessary next week. 👍
