### ISSUE TITLE
It is impossible to reset a speakers unavailable dates list in the database.

### ISSUE THREAD

**Issue by ajtruckle** [ajtruckle/meeting-schedule-assistant-support#96]
**Describe the bug**
There is a problem with updating the availability of a speaker.

**To Reproduce**

1. Click the 'Clear All Dates' button to uncheck all dates.
2. Click 'OK' to close the window.
3. Exit the MSA program entirely.
4. Reopen MSA and select the same speaker.
5. Observe the error: the changes have not been saved, and the dates remain as they were originally.

**Expected behavior**
None of the dates should have been checked, as I specifically requested to clear them all.

**Screenshots**
See this video provided by @cengizu:

https://github.com/user-attachments/assets/dec01175-997b-4c59-9e29-f2249dbc0d73

**Additional context**
It is impossible to reset a speakers unavailable dates list in the database.

**Comment by ajtruckle** [comment]
@cengizu
I have been checking the code and I can see the mistake! 🤭 I know how to fix this bug 🪲.

> [!NOTE]
> In-fact, the same bug can be repeated on the Publishers Database window. So, I'll fix both at the same time. 👍

**Comment by ajtruckle** [comment]
@cengizu
I am forwarding a beta version that resolves the issue for both the Publisher Database and Speaker windows.

**Comment by cengizu** [comment]
@ajtruckle 

Tested the beta. Now Clear All Dates button works as expected.
